# Generated by Django 6.0 on 2026-04-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governance",
            "0004_rename_access_certifications_tenant_user_idx_access_cert_tenant__6415d5_idx_and_more",
        ),
        ("marketplace", "0007_marketplace_stripe_webhook_and_payment_refund"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Marketplace order that triggered this access request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="governance_access_requests",
                to="marketplace.order",
            ),
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["order"], name="access_requ_order_i_aee1f3_idx"),
        ),
    ]
