# Generated by Django 6.0 on 2026-04-14 19:32
# Phase 313 — made core-only safe: the marketplace dependency is REMOVED and
# the FK + index are created CONDITIONALLY (only when the paid marketplace
# app is installed). State operations remain so the full-mode model state is
# unchanged; core-only makemigrations drift for this column is the documented
# known gap (paid-ward FK migration, post-launch).

import django.db.models.deletion
from django.db import migrations, models


def _add_order_fk_conditionally(apps, schema_editor):
    if "marketplace" not in apps.all_models:
        return  # core-only: no marketplace table to reference
    model = apps.get_model("governance", "AccessRequest")
    field = models.ForeignKey(
        "marketplace.Order",
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.SET_NULL,
        related_name="governance_access_requests",
    )
    field.set_attributes_from_name("order")
    schema_editor.add_field(model, field)
    schema_editor.add_index(
        model, models.Index(fields=["order"], name="access_requ_order_i_aee1f3_idx")
    )


def _drop_order_fk_conditionally(apps, schema_editor):
    if "marketplace" not in apps.all_models:
        return
    model = apps.get_model("governance", "AccessRequest")
    try:
        field = model._meta.get_field("order")
    except Exception:
        return
    schema_editor.remove_field(model, field)


class Migration(migrations.Migration):

    dependencies = [
        (
            "governance",
            "0004_rename_access_certifications_tenant_user_idx_access_cert_tenant__6415d5_idx_and_more",
        ),
        # Phase 313 — the marketplace dependency is REMOVED; the FK is
        # created conditionally below (core-only has no marketplace).
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    _add_order_fk_conditionally,
                    reverse_code=_drop_order_fk_conditionally,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="accessrequest",
                    name="order",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Marketplace order that triggered this access request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="governance_access_requests",
                        to="marketplace.order",
                    ),
                ),
                migrations.AddIndex(
                    model_name="accessrequest",
                    index=models.Index(fields=["order"], name="access_requ_order_i_aee1f3_idx"),
                ),
            ],
        ),
    ]
