# Generated by Django 6.0.4 on 2026-05-14 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0011_approval_delegation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accessrequestcomment',
            name='ar_comment_thread_idx',
        ),
        migrations.RenameIndex(
            model_name='retentionpolicy',
            new_name='retention_p_tenant__4d8178_idx',
            old_name='ret_pol_tenant_tomb_ix',
        ),
        migrations.AlterField(
            model_name='accessrequestcomment',
            name='access_request',
            field=models.ForeignKey(help_text='Access request this comment is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='governance.accessrequest'),
        ),
        migrations.AlterField(
            model_name='accessrequestcomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='hard_delete_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='UTC deadline after tombstone grace (90 calendar days by default auto-sweep).', null=True),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='regulation_keys',
            field=models.JSONField(blank=True, default=list, help_text='Regime keys (uppercase strings) attached to TIME_BASED policies; when non-empty they drive retention_period_days automatically.'),
        ),
        migrations.AlterField(
            model_name='retentionpolicy',
            name='tombstoned_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when the Phase 232.7 auto-sweep first soft-deleted the resource.', null=True),
        ),
    ]
