# Generated by Django 6.0 on 2026-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0014_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesspolicy",
            name="conditions",
            field=models.JSONField(
                default=dict,
                help_text="Policy conditions (user attributes, resource attributes, environment)",
            ),
        ),
    ]
