"""
Audit Logging Views

REST API views for querying and exporting audit events.
"""

import csv
import json
import uuid
from datetime import datetime, timedelta, timezone as dt_timezone

from django.http import HttpResponse
from django.utils import timezone
from drf_spectacular.types import OpenApiTypes
from drf_spectacular.utils import OpenApiParameter, extend_schema, extend_schema_view
from rest_framework import permissions, serializers as drf_serializers, status, viewsets
from rest_framework.decorators import action
from rest_framework.renderers import BaseRenderer, JSONRenderer
from rest_framework.response import Response

from hub.apps.auth.permissions import HasAnyRole, HasRole
from hub.apps.tenants.request_tenant import get_request_tenant_id

from . import event_types as _audit_et
from .involvement import user_is_involved
from .models import AuditEvent, AuditEventRetentionPolicy
from .serializers import (
    AuditEventRetentionPolicySerializer,
    AuditEventSerializer,
    ResourceActivityEventSerializer,
)
from .utils import create_audit_event

# Roles allowed to read raw audit events (list / retrieve / export).
# ``HasAnyRole`` internally bypasses the check for the ``is_platform_admin``
# boolean flag, but Phase 225.3.1 requires the *named* ``PLATFORM_ADMIN``
# role to also grant access — so we list it explicitly here.
AUDIT_READ_ROLES = ["TENANT_ADMIN", "AUDITOR", "PLATFORM_ADMIN"]


class CSVRenderer(BaseRenderer):
    """
    Custom CSV renderer to satisfy DRF's content negotiation.

    This renderer accepts 'text/csv' in the Accept header, allowing
    DRF's content negotiation to pass. The actual CSV response is
    generated by the viewset action using HttpResponse.
    """

    media_type = "text/csv"
    format = "csv"

    def render(self, data, accepted_media_type=None, renderer_context=None):
        # This should never be called since the action returns HttpResponse directly
        # But we implement it to satisfy the interface
        return data


_AUDIT_LIST_QUERY_PARAMS = [
    OpenApiParameter(
        name="resource_type",
        type=str,
        location=OpenApiParameter.QUERY,
        required=False,
        description=(
            "Filter audit events by resource type "
            "(e.g. ``ASSET``, ``CONTRACT``, ``FILE``, ``DATASET``)."
        ),
    ),
    OpenApiParameter(
        name="resource_id",
        type=OpenApiTypes.UUID,
        location=OpenApiParameter.QUERY,
        required=False,
        description=(
            "Phase 260.4.H — narrow the audit log to a single resource "
            "UUID. Used by the admin audit-log search page to deep-link "
            "from detail pages (``?resource_type=FILE&resource_id={id}``). "
            "Malformed UUIDs return an empty list (no 500 leak)."
        ),
    ),
    OpenApiParameter(
        name="action",
        type=str,
        location=OpenApiParameter.QUERY,
        required=False,
        description="Filter by audit action (e.g. ``CREATED``, ``FILE_RENAMED``).",
    ),
    OpenApiParameter(
        name="actor_user_id",
        type=OpenApiTypes.UUID,
        location=OpenApiParameter.QUERY,
        required=False,
        description="Filter by acting user UUID.",
    ),
    OpenApiParameter(
        name="start_date",
        type=OpenApiTypes.DATETIME,
        location=OpenApiParameter.QUERY,
        required=False,
        description="ISO-8601 lower bound (inclusive) on ``timestamp``.",
    ),
    OpenApiParameter(
        name="end_date",
        type=OpenApiTypes.DATETIME,
        location=OpenApiParameter.QUERY,
        required=False,
        description="ISO-8601 upper bound (inclusive) on ``timestamp``.",
    ),
    OpenApiParameter(
        name="q",
        type=str,
        location=OpenApiParameter.QUERY,
        required=False,
        description=(
            "Phase 234.6 — Postgres full-text search over the audit "
            "event's ``action``, ``resource_type`` and ``details_json``. "
            "Uses ``websearch_to_tsquery('english', :q)`` so the SPA can "
            "pass user input verbatim (supports quoted phrases, "
            "``-negation``, ``or``). Results are ordered by ``ts_rank`` "
            "descending and then by ``timestamp`` descending. ALWAYS "
            "ANDed with the existing tenant-scope filter — a search "
            "from tenant A can never surface tenant B's rows."
        ),
    ),
]


@extend_schema_view(
    list=extend_schema(parameters=_AUDIT_LIST_QUERY_PARAMS),
)
class AuditEventViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for audit event querying and export.

    Tenant-scoped: users can only see audit events for their tenant.
    Platform admins can see all audit events.
    """

    queryset = AuditEvent.objects.all()
    serializer_class = AuditEventSerializer
    permission_classes = [permissions.IsAuthenticated]
    lookup_field = "id"

    def get_permissions(self):
        """Role-gate raw audit access; leave resource-activity open.

        Phase 224.3.1: list/retrieve/export of raw audit events are restricted
        to ``TENANT_ADMIN``/``AUDITOR`` (platform admins bypass via
        ``HasAnyRole``). The ``resource_activity`` action remains open to any
        authenticated tenant user because it returns a sanitized feed scoped
        to a single resource the user can already see.
        """
        if getattr(self, "action", None) == "resource_activity":
            return [permissions.IsAuthenticated()]
        return [permissions.IsAuthenticated(), HasAnyRole(AUDIT_READ_ROLES)]

    def perform_content_negotiation(self, request, force=False):
        """
        For export with invalid ?format=, force JSON so the view can return
        a JSON 404 (API returns 404 with application/json for clients).
        """
        path = getattr(request, "path", "") or request.META.get("PATH_INFO", "")
        if path.rstrip("/").endswith("/export"):
            format_param = (
                request.GET.get("format", "") or request.query_params.get("format", "")
            ).lower().strip()
            if format_param and format_param not in ("csv", "json"):
                return (JSONRenderer(), "application/json")
        return super().perform_content_negotiation(request, force=force)

    def get_queryset(self):
        """Filter queryset based on user permissions and filters"""
        user = self.request.user

        # Platform admins can see all audit events
        if hasattr(user, "is_platform_admin") and user.is_platform_admin:
            queryset = AuditEvent.objects.all()
        else:
            # Regular users can only see audit events for their tenant
            # Use central helper for tenant resolution (Phase 10.1.3)
            tenant_id = get_request_tenant_id(self.request)
            if tenant_id:
                queryset = AuditEvent.objects.filter(tenant_id=tenant_id)
            else:
                queryset = AuditEvent.objects.none()

        # Apply filters
        resource_type = self.request.query_params.get("resource_type")
        if resource_type:
            queryset = queryset.filter(resource_type=resource_type)

        resource_id = self.request.query_params.get("resource_id")
        if resource_id:
            # Validate as UUID to avoid Django throwing DataError on bad input.
            try:
                resource_uuid = uuid.UUID(str(resource_id))
            except (ValueError, TypeError):
                # Unknown UUID → no rows; fall through with a sentinel filter.
                queryset = queryset.none()
            else:
                queryset = queryset.filter(resource_id=resource_uuid)

        action_filter = self.request.query_params.get("action")
        if action_filter:
            queryset = queryset.filter(action=action_filter)

        actor_user_id = self.request.query_params.get("actor_user_id")
        if actor_user_id:
            queryset = queryset.filter(actor_user_id=actor_user_id)

        # Phase 277.B.111 — filter by OTel trace_id
        trace_id = self.request.query_params.get("trace_id")
        if trace_id:
            queryset = queryset.filter(trace_id=trace_id)

        # Time range filters
        from datetime import timezone as dt_timezone

        start_date = self.request.query_params.get("start_date")
        if start_date:
            try:
                # Parse ISO format date string
                # Handle both 'Z' and timezone offset formats, and spaces
                date_str = start_date.replace("Z", "+00:00").replace(" ", "+")
                # Fix any remaining space issues (e.g., "2025-11-18T04:54:41.073010 00:00")
                if " " in date_str and "+" not in date_str:
                    # Replace space before timezone with +
                    import re

                    date_str = re.sub(r"(\d)\s+([+-]\d{2}:\d{2})", r"\1\2", date_str)
                start_dt = datetime.fromisoformat(date_str)
                # Ensure timezone-aware datetime in UTC
                if start_dt.tzinfo is None:
                    start_dt = timezone.make_aware(start_dt, dt_timezone.utc)
                else:
                    # Convert to UTC if not already
                    start_dt = start_dt.astimezone(dt_timezone.utc)
                # Django ORM handles timezone-aware datetimes correctly
                # Filter for events on or after start_date
                queryset = queryset.filter(timestamp__gte=start_dt)
            except (ValueError, AttributeError, TypeError) as e:
                # Invalid date format, ignore
                import logging

                logger = logging.getLogger(__name__)
                logger.warning(f"Invalid start_date format: {start_date}, error: {e}")
                pass

        end_date = self.request.query_params.get("end_date")
        if end_date:
            try:
                # Parse ISO format date string
                # Handle both 'Z' and timezone offset formats, and spaces
                date_str = end_date.replace("Z", "+00:00").replace(" ", "+")
                # Fix any remaining space issues (e.g., "2025-11-18T04:54:41.073010 00:00")
                if " " in date_str and "+" not in date_str:
                    # Replace space before timezone with +
                    import re

                    date_str = re.sub(r"(\d)\s+([+-]\d{2}:\d{2})", r"\1\2", date_str)
                end_dt = datetime.fromisoformat(date_str)
                # Ensure timezone-aware datetime in UTC
                if end_dt.tzinfo is None:
                    end_dt = timezone.make_aware(end_dt, dt_timezone.utc)
                else:
                    # Convert to UTC if not already
                    end_dt = end_dt.astimezone(dt_timezone.utc)
                queryset = queryset.filter(timestamp__lte=end_dt)
            except (ValueError, AttributeError, TypeError) as e:
                # Invalid date format, ignore
                import logging

                logger = logging.getLogger(__name__)
                logger.warning(f"Invalid end_date format: {end_date}, error: {e}")
                pass

        # Phase 234.6 — Postgres FTS over the GENERATED tsvector column.
        # The ``q`` filter is the LAST clause appended so it ALWAYS runs
        # after the tenant scope already attached above (AUDIT.3): a
        # search from tenant A's user can never bleed into tenant B's
        # rows because by the time we add the ``@@`` predicate the
        # queryset is already filtered to ``tenant_id=request.tenant``.
        #
        # ``search_type="websearch"`` accepts user input verbatim —
        # quoted phrases, ``-negation`` and ``or`` syntax map straight
        # to ``websearch_to_tsquery``, the same parser the SPA's
        # search-box semantics expect.
        #
        # The timer that emits ``audit_search_query_duration_seconds``
        # wraps the eventual SQL execution — see :meth:`list` below,
        # which calls ``super().list`` inside :func:`time_search_query`.
        # Here we only build the queryset (Django is lazy); evaluation
        # happens during DRF's pagination/render path.
        q_raw = self.request.query_params.get("q")
        q = (q_raw or "").strip()
        if q:
            from django.contrib.postgres.search import SearchQuery, SearchRank
            from django.db.models import F

            sq = SearchQuery(q, search_type="websearch", config="english")
            queryset = (
                queryset.filter(details_json_tsvector=sq)
                .annotate(rank=SearchRank(F("details_json_tsvector"), sq))
                .order_by("-rank", "-timestamp")
            )
            return queryset

        return queryset.order_by("-timestamp")

    def list(self, request, *args, **kwargs):
        """List audit events with filtering.

        Phase 234.6.AUDIT.4 — when ``?q=`` is present we time the entire
        list response (queryset evaluation + count query + serialization)
        and record the elapsed seconds on the
        ``audit_search_query_duration_seconds`` histogram. The
        observation fires whether the request succeeds or raises so
        a 500 still contributes to the latency curve — a query that
        takes 8 seconds before crashing is operationally identical to
        one that takes 8 seconds and returns.

        The non-``?q=`` path does NOT emit on this histogram (would
        pollute the percentile with discrete-filter queries that don't
        share the FTS code path).
        """
        q_raw = request.query_params.get("q") if hasattr(request, "query_params") else None
        q = (q_raw or "").strip()
        if q:
            from hub.apps.audit.metrics import time_search_query

            tenant_label = str(get_request_tenant_id(request) or "__platform__")
            with time_search_query(tenant_id=tenant_label):
                return super().list(request, *args, **kwargs)
        return super().list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """Retrieve audit event by ID"""
        return super().retrieve(request, *args, **kwargs)

    @action(
        detail=False,
        methods=["get"],
        url_path="resource-activity",
        url_name="resource-activity",
    )
    def resource_activity(self, request):
        """Backwards-compat shim — delegates to :class:`ResourceActivityViewSet`.

        Kept so existing frontend callers at
        ``/api/v1/audit/audit-events/resource-activity/`` keep working while
        clients migrate to the new top-level ``/api/v1/audit/resource-activity/``
        route.  All scoping / sanitization rules are identical because both
        paths share the same helper.
        """
        return _resource_activity_response(request)

    @extend_schema(
        parameters=[
            OpenApiParameter(
                name="format",
                type=str,
                location=OpenApiParameter.QUERY,
                required=False,
                description="Export format: ``csv`` or ``json`` (default ``json``).",
                enum=["csv", "json"],
            ),
            *_AUDIT_LIST_QUERY_PARAMS,
        ],
    )
    @action(
        detail=False,
        methods=["get"],
        url_path="export",
        url_name="export",
        renderer_classes=[CSVRenderer, JSONRenderer],
    )
    def export(self, request):
        """
        Export audit events to CSV or JSON.

        Query params:
        - format: 'csv' or 'json' (default: 'json')
        - All other filters from list endpoint apply

        Note: DRF may interpret ?format=csv as a format suffix, causing routing issues.
        This method prioritizes query parameter over format suffix to avoid conflicts.
        """
        # Handle Http404 from content negotiation for invalid formats
        from django.http import Http404
        try:
            # Get format from query params - prioritize query param over format suffix
            # DRF's DefaultRouter creates format suffix patterns that can interfere with query params
            format_type = "json"  # default

            # CRITICAL: Check query parameter FIRST before any format suffix handling
            # This ensures ?format=csv works even if DRF tries to interpret it as a suffix
            # Use request.GET for Django's QueryDict to ensure we get the actual query parameter
            format_param = request.GET.get("format", "").lower().strip()
            if not format_param:
                # Fallback to query_params (DRF's version)
                format_param = request.query_params.get("format", "").lower().strip()

            if format_param in ["csv", "json"]:
                format_type = format_param
            # Also check DRF's format attribute (set by format suffix pattern) as fallback
            elif hasattr(request, "format") and request.format:
                format_type = request.format.lower()
            # Check Accept header for content negotiation (last resort)
            else:
                accept_header = request.META.get("HTTP_ACCEPT", "")
                if "text/csv" in accept_header.lower():
                    format_type = "csv"

            # If format is invalid and not in accepted formats, return JSON 404
            if format_param and format_param not in ["csv", "json"]:
                return Response(
                    {"detail": "Invalid format. Supported formats: csv, json"},
                    status=status.HTTP_404_NOT_FOUND,
                )

            # Get filtered queryset
            queryset = self.get_queryset()

            # Limit export size (safety measure)
            max_export_size = 10000
            queryset_count = queryset.count()
            if queryset_count > max_export_size:
                return Response(
                    {
                        "error": f"Export size exceeds maximum of {max_export_size} events. Please use filters to reduce the result set."
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )

            events = list(queryset[:max_export_size])

            if format_type == "csv":
                return self._export_csv(events)
            else:
                return self._export_json(events)
        except Http404:
            # DRF's content negotiation raised Http404 for invalid format
            # Return JSON 404 response as expected by the test
            return Response(
                {"detail": "Invalid format. Supported formats: csv, json"},
                status=status.HTTP_404_NOT_FOUND,
            )

    def _export_csv(self, events):
        """Export events as CSV"""
        from django.http import HttpResponse

        response = HttpResponse(content_type="text/csv; charset=utf-8")
        response["Content-Disposition"] = 'attachment; filename="audit_events.csv"'

        writer = csv.writer(response)
        writer.writerow(
            [
                "ID",
                "Timestamp",
                "Tenant",
                "Actor User",
                "Resource Type",
                "Resource ID",
                "Action",
                "Result",
                "Details",
            ]
        )

        for event in events:
            writer.writerow(
                [
                    str(event.id),
                    event.timestamp.isoformat(),
                    event.tenant.name if event.tenant else "",
                    event.actor_user.email if event.actor_user else "",
                    event.resource_type,
                    str(event.resource_id) if event.resource_id else "",
                    event.action,
                    event.result,
                    json.dumps(event.details_json),
                ]
            )

        return response

    def _export_json(self, events):
        """Export events as JSON"""
        serializer = self.get_serializer(events, many=True)
        return Response(serializer.data)


# ---------------------------------------------------------------------------
# Phase 225.3.2 — separate ResourceActivityViewSet
# ---------------------------------------------------------------------------
#
# Exposes a narrow per-resource feed at ``/api/v1/audit/resource-activity/``
# for any authenticated user.  Unlike the raw audit log it is gated on
# *user involvement* with the resource (actor on an event OR owner via the
# ``hub.apps.audit.involvement.OWNERSHIP_RESOLVERS`` registry) rather than
# on a role.  Admins bypass the filter; cross-tenant callers get an empty
# feed (not 403) so the endpoint does not leak resource existence across
# tenants.


def _resource_activity_response(request):
    """Shared implementation between :class:`ResourceActivityViewSet` and
    the backwards-compat action on :class:`AuditEventViewSet`.

    Steps:
      1. Parse & validate ``resource_type`` / ``resource_id`` query params.
      2. Resolve the caller's tenant. A user with no tenant membership in
         scope for this resource receives an empty feed (tenant-existence
         non-disclosure).
      3. Check ``user_is_involved`` — admins bypass, otherwise we require
         either an actor match or an ownership match.
      4. Filter the AuditEvent queryset, cap at 200 rows newest-first,
         and serialise via :class:`ResourceActivityEventSerializer` which
         scrubs ``details_json``.
    """
    resource_type = (request.query_params.get("resource_type") or "").strip()
    resource_id_raw = (request.query_params.get("resource_id") or "").strip()
    if not resource_type or not resource_id_raw:
        return Response(
            {"detail": "resource_type and resource_id are required."},
            status=status.HTTP_400_BAD_REQUEST,
        )
    try:
        resource_uuid = uuid.UUID(resource_id_raw)
    except (ValueError, TypeError):
        return Response(
            {"detail": "resource_id must be a valid UUID."},
            status=status.HTTP_400_BAD_REQUEST,
        )

    user = request.user
    is_platform_admin = bool(getattr(user, "is_platform_admin", False))

    if is_platform_admin:
        qs = AuditEvent.objects.all()
        tenant_id = None  # admins see cross-tenant by design
    else:
        tenant_id = get_request_tenant_id(request)
        if not tenant_id:
            # No tenant context → nothing to show. Empty (not 403) to
            # avoid disclosing the resource's existence in other tenants.
            return Response({"results": []}, status=status.HTTP_200_OK)
        qs = AuditEvent.objects.filter(tenant_id=tenant_id)

    # Short-circuit cross-tenant / non-existent: if there are no events
    # for this (tenant, resource), hand back an empty feed regardless of
    # the involvement predicate. This avoids a confusing 403 for users
    # hitting an unknown or cross-tenant UUID (existence non-disclosure)
    # and also covers owners whose resource has no audit trail yet.
    scoped = qs.filter(resource_type=resource_type, resource_id=resource_uuid)
    if not scoped.exists():
        return Response({"results": []}, status=status.HTTP_200_OK)

    # Involvement gate — admins pass through inside user_is_involved().
    if not user_is_involved(
        user,
        resource_type=resource_type,
        resource_id=resource_uuid,
        tenant_id=tenant_id,
    ):
        return Response(
            {"detail": "Not involved with this resource."},
            status=status.HTTP_403_FORBIDDEN,
        )

    events = scoped.order_by("-timestamp")[:200]
    serializer = ResourceActivityEventSerializer(events, many=True)
    return Response({"results": serializer.data})


class ResourceActivityViewSet(viewsets.ViewSet):
    """Per-resource sanitized audit feed.

    Mounted at ``/api/v1/audit/resource-activity/``.  List-only (no
    retrieve / create / update / destroy).  Authentication required;
    authorization is handled per-request via the involvement predicate
    so role-based gating cannot be used to starve legitimate owners.
    """

    permission_classes = [permissions.IsAuthenticated]

    def list(self, request):
        return _resource_activity_response(request)


# ---------------------------------------------------------------------------
# Phase 234.1.8 — integrity verification endpoint
# ---------------------------------------------------------------------------


def _parse_iso(value: str | None):
    """Lenient ISO-8601 parser that tolerates ``Z`` suffix and naive input."""
    if not value:
        return None
    s = value.strip()
    if not s:
        return None
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.fromisoformat(s)
    except ValueError:
        return None
    if dt.tzinfo is None:
        # Naive datetimes are an explicit input error from the client, but
        # we accept them defensively and interpret as UTC — the Phase 234
        # contract pins ALL chain timestamps to UTC so any other policy
        # would create an attack surface where mismatched timezones flip
        # the verifier outcome.
        dt = dt.replace(tzinfo=dt_timezone.utc)
    return dt


@extend_schema(
    tags=["Audit"],
    parameters=[
        OpenApiParameter(
            name="tenant_id",
            type=OpenApiTypes.UUID,
            location=OpenApiParameter.QUERY,
            required=False,
            description=(
                "Verify the chain for this tenant. Defaults to the requesting "
                "user's tenant. Platform admins may supply any tenant UUID; "
                "non-admins are restricted to their own tenant (403 otherwise)."
            ),
        ),
        OpenApiParameter(
            name="since",
            type=OpenApiTypes.DATETIME,
            location=OpenApiParameter.QUERY,
            required=False,
            description="ISO-8601 lower bound on ``timestamp`` (inclusive).",
        ),
        OpenApiParameter(
            name="until",
            type=OpenApiTypes.DATETIME,
            location=OpenApiParameter.QUERY,
            required=False,
            description="ISO-8601 upper bound on ``timestamp`` (exclusive).",
        ),
        OpenApiParameter(
            name="include_snapshots",
            type=bool,
            location=OpenApiParameter.QUERY,
            required=False,
            description=(
                "When ``true``, also recompute the Merkle root for every "
                "``AuditMerkleSnapshot`` covering the window and compare "
                "against the signed root. Catches full-chain rewrite that "
                "the per-row check cannot. Defaults to ``false`` for "
                "backwards compatibility."
            ),
        ),
    ],
    responses={
        200: OpenApiTypes.OBJECT,
        400: OpenApiTypes.OBJECT,
        403: OpenApiTypes.OBJECT,
    },
)
class AuditIntegrityVerifyView(viewsets.ViewSet):
    """Phase 234.1.8 — ``GET /api/v1/audit/integrity/verify``.

    Re-runs :func:`hub.apps.audit.chain.verify_chain_segment` over the
    requested window and returns the structured outcome:

    .. code-block:: json

        {
          "verified": true,
          "checked": 42,
          "mismatches": [],
          "gaps": []
        }

    Tampering surfaces as one or more ``mismatches`` entries (with the
    offending ``event_id``, ``chain_sequence``, and a ``reason`` code
    of ``chain_hash_mismatch`` or ``prev_link_mismatch``). GDPR-erasure
    holes surface as ``gaps`` and do NOT flip ``verified`` to false
    on their own — per the cross-spec contract with 232.2.
    """

    permission_classes = [permissions.IsAuthenticated]

    def list(self, request):
        # Local imports to keep chain logic out of module-import-time
        # dependencies and to mirror the verifier the backfill command
        # uses.
        from hub.apps.audit.chain import (
            verify_chain_against_snapshots,
            verify_chain_segment,
        )
        from hub.apps.audit.merkle import verify_root_signature
        from hub.apps.audit.models import AuditMerkleSnapshot

        # ---- tenant authorization -----------------------------------------
        user = request.user
        is_platform_admin = bool(getattr(user, "is_platform_admin", False))
        requested_tenant_id = request.query_params.get("tenant_id") or None
        own_tenant_id = get_request_tenant_id(request)
        if requested_tenant_id:
            if not is_platform_admin and str(requested_tenant_id) != str(own_tenant_id or ""):
                return Response(
                    {"detail": "Cannot verify another tenant's chain."},
                    status=status.HTTP_403_FORBIDDEN,
                )
            tenant_filter = requested_tenant_id
        else:
            tenant_filter = own_tenant_id
        if not tenant_filter:
            return Response(
                {"detail": "tenant_id is required (no tenant context on request)."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # ---- role gate (mirror AuditEventViewSet) -------------------------
        role_check = HasAnyRole(AUDIT_READ_ROLES)
        if not role_check.has_permission(request, self):
            return Response(
                {"detail": "Requires TENANT_ADMIN / AUDITOR / PLATFORM_ADMIN."},
                status=status.HTTP_403_FORBIDDEN,
            )

        # ---- window parsing ----------------------------------------------
        since = _parse_iso(request.query_params.get("since"))
        until = _parse_iso(request.query_params.get("until"))

        qs = AuditEvent.all_objects.filter(
            tenant_id=tenant_filter,
            chain_hash__isnull=False,
        )
        if since is not None:
            qs = qs.filter(timestamp__gte=since)
        if until is not None:
            qs = qs.filter(timestamp__lt=until)
        events = list(qs.order_by("chain_sequence"))
        result = verify_chain_segment(events)

        # ---- optional snapshot cross-check --------------------------------
        # The in-row verifier above catches single-row forgery and
        # neighbour-link forgery (no-gap case). It CANNOT catch a
        # full-chain rewrite where every row's chain_hash + prev_chain_hash
        # are forged to be internally consistent. The signed Merkle
        # snapshots are the cryptographic anchor for that case: re-hashing
        # the current rows must reproduce the signed root.
        include_snapshots = (
            str(request.query_params.get("include_snapshots") or "")
            .strip().lower()
            in ("1", "true", "yes")
        )
        if include_snapshots:
            snap_qs = AuditMerkleSnapshot.objects.filter(tenant_id=tenant_filter)
            if since is not None:
                snap_qs = snap_qs.filter(period_end__gte=since)
            if until is not None:
                snap_qs = snap_qs.filter(period_start__lt=until)
            snapshots = list(snap_qs.order_by("period_end"))

            # For each snapshot resolve its window-leaf set from the CURRENT
            # rows (filter chain_hash__isnull=False so pre-backfill rows
            # don't perturb the recomputed root).
            pairs: list[tuple[AuditMerkleSnapshot, list[AuditEvent]]] = []
            for snap in snapshots:
                window_events = list(
                    AuditEvent.all_objects.filter(
                        tenant_id=tenant_filter,
                        chain_hash__isnull=False,
                        timestamp__gte=snap.period_start,
                        timestamp__lt=snap.period_end,
                    ).order_by("chain_sequence")
                )
                pairs.append((snap, window_events))

            result = verify_chain_against_snapshots(
                base=result,
                snapshot_pairs=pairs,
                signature_verifier=verify_root_signature,
            )

        # ---- Phase 234.7.2 / 234.7.1 — observability + meta-audit -------
        # Counter (one increment PER mismatch row, per-reason) drives the
        # ``AuditChainBreakDetected`` PagerDuty alert. Then we emit the
        # AUDIT_INTEGRITY_VERIFIED / _MISMATCH meta-audit so an auditor
        # reconstructing a regulatory-period timeline from the audit log
        # alone can see when the chain was last machine-verified — not
        # just rely on Grafana history.
        from hub.apps.audit.metrics import observe_chain_break
        from hub.apps.audit.utils import create_audit_event
        from hub.apps.audit import event_types as _audit_et

        tenant_label = str(tenant_filter) if tenant_filter else "__platform__"
        for m in result.mismatches:
            observe_chain_break(tenant_id=tenant_label, reason=m.reason)
        snapshot_mismatch_count = len(getattr(result, "snapshot_mismatches", []) or [])
        for _snap_m in getattr(result, "snapshot_mismatches", []) or []:
            observe_chain_break(
                tenant_id=tenant_label, reason="snapshot_root_mismatch"
            )

        # Resolve the tenant ORM row for the meta-audit FK (None for the
        # platform chain — when ``tenant_filter`` is the literal string
        # "__platform__" we treat as no tenant context, mirroring the
        # convention used elsewhere in this module).
        meta_tenant = None
        if tenant_filter and str(tenant_filter) != "__platform__":
            from hub.apps.tenants.models import Tenant

            meta_tenant = Tenant.objects.filter(id=tenant_filter).first()

        if result.verified:
            create_audit_event(
                resource_type="JOB",
                action=_audit_et.AUDIT_INTEGRITY_VERIFIED,
                actor_user=request.user if request.user.is_authenticated else None,
                tenant=meta_tenant,
                resource_id=None,
                result="SUCCESS",
                details={
                    "tenant_id": tenant_label,
                    "checked": result.checked,
                    "gaps": len(result.gaps),
                    "include_snapshots": include_snapshots,
                    "snapshots_checked": getattr(result, "snapshots_checked", 0),
                },
                request=request,
                infer_tenant_from_actor=False,
            )
        else:
            sample = [
                {
                    "event_id": m.event_id,
                    "chain_sequence": m.chain_sequence,
                    "reason": m.reason,
                }
                for m in result.mismatches[:10]
            ]
            create_audit_event(
                resource_type="JOB",
                action=_audit_et.AUDIT_INTEGRITY_MISMATCH,
                actor_user=request.user if request.user.is_authenticated else None,
                tenant=meta_tenant,
                resource_id=None,
                result="FAILURE",
                details={
                    "tenant_id": tenant_label,
                    "checked": result.checked,
                    "mismatch_count": len(result.mismatches),
                    "mismatches": sample,
                    "gaps": len(result.gaps),
                    "snapshot_mismatches": snapshot_mismatch_count,
                    "include_snapshots": include_snapshots,
                },
                request=request,
                infer_tenant_from_actor=False,
            )

        return Response(result.to_dict(), status=status.HTTP_200_OK)


# ---------------------------------------------------------------------------
# Phase 234.5 — Per-event-type audit retention policy CRUD
# ---------------------------------------------------------------------------


class AuditEventRetentionPolicyViewSet(viewsets.ModelViewSet):
    """Phase 234.5 — TENANT_ADMIN CRUD over ``AuditEventRetentionPolicy``.

    Mounted under ``/api/v1/audit/event-retention-policies/``. Tenant-scoped:
    the queryset is filtered to ``request.tenant`` at every action and
    the ``perform_create`` hook stamps the tenant FK from the request
    context (the wire payload's ``tenant`` field is read-only on the
    serializer — see :class:`AuditEventRetentionPolicySerializer`).

    Permissions: ``TENANT_ADMIN`` role required. ``PLATFORM_ADMIN`` is
    accepted via :class:`HasRole`'s flag-bypass shape.

    Audit emission: every successful CRUD action emits one
    ``AUDIT_EVENT_RETENTION_POLICY_{CREATED,UPDATED,DELETED}`` row
    against the tenant. ``details_json`` carries the policy id, event
    type, resolved retention days, regulation key list, and (on
    update) the previous retention days for replay-time reconstruction.
    """

    serializer_class = AuditEventRetentionPolicySerializer
    lookup_field = "id"

    def get_permissions(self):
        # DRF instantiates each entry in ``permission_classes`` via
        # ``permission()`` (rest_framework/views.py:284). ``HasRole`` takes
        # a required-role argument at construction, so pre-instantiated
        # entries in ``permission_classes`` raise
        # ``TypeError: 'HasRole' object is not callable`` at request time
        # AND at schema-generation time — the latter kills the entire
        # drf-spectacular OpenAPI build and forces the 5-path fallback
        # stub in ``hub/apps/api/views.py``. Match the override pattern
        # used at ``audit/views.py`` line 140 and ``semantic/views.py``
        # line 1398 to return pre-instantiated permissions directly.
        return [permissions.IsAuthenticated(), HasRole("TENANT_ADMIN")]

    def get_queryset(self):
        tenant_id = get_request_tenant_id(self.request)
        if not tenant_id:
            return AuditEventRetentionPolicy.objects.none()
        return AuditEventRetentionPolicy.objects.filter(
            tenant_id=tenant_id
        ).order_by("event_type")

    def _resolve_tenant(self):
        """Return the tenant ORM row for the request, or 400-equivalent None."""
        from hub.apps.tenants.models import Tenant

        tenant_id = get_request_tenant_id(self.request)
        if not tenant_id:
            return None
        return Tenant.objects.filter(id=tenant_id).first()

    def perform_create(self, serializer):
        tenant = self._resolve_tenant()
        if tenant is None:
            # Defensive: should not happen because IsAuthenticated +
            # HasRole(TENANT_ADMIN) already imply a tenant context, but
            # we don't want a server-side IntegrityError if the
            # middleware ever resolves to None.
            raise drf_serializers.ValidationError(
                "Tenant context is required to create an audit retention policy."
            )
        instance = serializer.save(tenant=tenant, created_by=self.request.user)
        create_audit_event(
            resource_type="AUDIT_EVENT_RETENTION_POLICY",
            action=_audit_et.AUDIT_EVENT_RETENTION_POLICY_CREATED,
            actor_user=self.request.user,
            tenant=tenant,
            resource_id=str(instance.id),
            details={
                "policy_id": str(instance.id),
                "event_type": instance.event_type,
                "retention_days": instance.retention_days,
                "regulation_keys": list(instance.regulation_keys or []),
                "enabled": instance.enabled,
            },
            request=self.request,
        )

    def perform_update(self, serializer):
        tenant = self._resolve_tenant()
        previous_retention_days = serializer.instance.retention_days
        instance = serializer.save()
        create_audit_event(
            resource_type="AUDIT_EVENT_RETENTION_POLICY",
            action=_audit_et.AUDIT_EVENT_RETENTION_POLICY_UPDATED,
            actor_user=self.request.user,
            tenant=tenant,
            resource_id=str(instance.id),
            details={
                "policy_id": str(instance.id),
                "event_type": instance.event_type,
                "retention_days": instance.retention_days,
                "previous_retention_days": previous_retention_days,
                "regulation_keys": list(instance.regulation_keys or []),
                "enabled": instance.enabled,
            },
            request=self.request,
        )

    def perform_destroy(self, instance):
        tenant = self._resolve_tenant()
        snapshot = {
            "policy_id": str(instance.id),
            "event_type": instance.event_type,
            "retention_days": instance.retention_days,
            "regulation_keys": list(instance.regulation_keys or []),
            "enabled": instance.enabled,
        }
        instance.delete()
        create_audit_event(
            resource_type="AUDIT_EVENT_RETENTION_POLICY",
            action=_audit_et.AUDIT_EVENT_RETENTION_POLICY_DELETED,
            actor_user=self.request.user,
            tenant=tenant,
            resource_id=snapshot["policy_id"],
            details=snapshot,
            request=self.request,
        )

