"""
Audit Logging Views

REST API views for querying and exporting audit events.
"""

import csv
import json
from datetime import datetime, timedelta

from django.http import HttpResponse
from django.utils import timezone
from rest_framework import permissions, status, viewsets
from rest_framework.decorators import action
from rest_framework.renderers import BaseRenderer, JSONRenderer
from rest_framework.response import Response

from hub.apps.auth.permissions import HasRole
from hub.apps.tenants.request_tenant import get_request_tenant_id

from .models import AuditEvent
from .serializers import AuditEventSerializer


class CSVRenderer(BaseRenderer):
    """
    Custom CSV renderer to satisfy DRF's content negotiation.

    This renderer accepts 'text/csv' in the Accept header, allowing
    DRF's content negotiation to pass. The actual CSV response is
    generated by the viewset action using HttpResponse.
    """

    media_type = "text/csv"
    format = "csv"

    def render(self, data, accepted_media_type=None, renderer_context=None):
        # This should never be called since the action returns HttpResponse directly
        # But we implement it to satisfy the interface
        return data


class AuditEventViewSet(viewsets.ReadOnlyModelViewSet):
    """
    ViewSet for audit event querying and export.

    Tenant-scoped: users can only see audit events for their tenant.
    Platform admins can see all audit events.
    """

    queryset = AuditEvent.objects.all()
    serializer_class = AuditEventSerializer
    permission_classes = [permissions.IsAuthenticated]
    lookup_field = "id"

    def perform_content_negotiation(self, request, force=False):
        """
        For export with invalid ?format=, force JSON so the view can return
        a JSON 404 (API returns 404 with application/json for clients).
        """
        path = getattr(request, "path", "") or request.META.get("PATH_INFO", "")
        if path.rstrip("/").endswith("/export"):
            format_param = (
                request.GET.get("format", "") or request.query_params.get("format", "")
            ).lower().strip()
            if format_param and format_param not in ("csv", "json"):
                return (JSONRenderer(), "application/json")
        return super().perform_content_negotiation(request, force=force)

    def get_queryset(self):
        """Filter queryset based on user permissions and filters"""
        user = self.request.user

        # Platform admins can see all audit events
        if hasattr(user, "is_platform_admin") and user.is_platform_admin:
            queryset = AuditEvent.objects.all()
        else:
            # Regular users can only see audit events for their tenant
            # Use central helper for tenant resolution (Phase 10.1.3)
            tenant_id = get_request_tenant_id(self.request)
            if tenant_id:
                queryset = AuditEvent.objects.filter(tenant_id=tenant_id)
            else:
                queryset = AuditEvent.objects.none()

        # Apply filters
        resource_type = self.request.query_params.get("resource_type")
        if resource_type:
            queryset = queryset.filter(resource_type=resource_type)

        action_filter = self.request.query_params.get("action")
        if action_filter:
            queryset = queryset.filter(action=action_filter)

        actor_user_id = self.request.query_params.get("actor_user_id")
        if actor_user_id:
            queryset = queryset.filter(actor_user_id=actor_user_id)

        # Time range filters
        from datetime import timezone as dt_timezone

        start_date = self.request.query_params.get("start_date")
        if start_date:
            try:
                # Parse ISO format date string
                # Handle both 'Z' and timezone offset formats, and spaces
                date_str = start_date.replace("Z", "+00:00").replace(" ", "+")
                # Fix any remaining space issues (e.g., "2025-11-18T04:54:41.073010 00:00")
                if " " in date_str and "+" not in date_str:
                    # Replace space before timezone with +
                    import re

                    date_str = re.sub(r"(\d)\s+([+-]\d{2}:\d{2})", r"\1\2", date_str)
                start_dt = datetime.fromisoformat(date_str)
                # Ensure timezone-aware datetime in UTC
                if start_dt.tzinfo is None:
                    start_dt = timezone.make_aware(start_dt, dt_timezone.utc)
                else:
                    # Convert to UTC if not already
                    start_dt = start_dt.astimezone(dt_timezone.utc)
                # Django ORM handles timezone-aware datetimes correctly
                # Filter for events on or after start_date
                queryset = queryset.filter(timestamp__gte=start_dt)
            except (ValueError, AttributeError, TypeError) as e:
                # Invalid date format, ignore
                import logging

                logger = logging.getLogger(__name__)
                logger.warning(f"Invalid start_date format: {start_date}, error: {e}")
                pass

        end_date = self.request.query_params.get("end_date")
        if end_date:
            try:
                # Parse ISO format date string
                # Handle both 'Z' and timezone offset formats, and spaces
                date_str = end_date.replace("Z", "+00:00").replace(" ", "+")
                # Fix any remaining space issues (e.g., "2025-11-18T04:54:41.073010 00:00")
                if " " in date_str and "+" not in date_str:
                    # Replace space before timezone with +
                    import re

                    date_str = re.sub(r"(\d)\s+([+-]\d{2}:\d{2})", r"\1\2", date_str)
                end_dt = datetime.fromisoformat(date_str)
                # Ensure timezone-aware datetime in UTC
                if end_dt.tzinfo is None:
                    end_dt = timezone.make_aware(end_dt, dt_timezone.utc)
                else:
                    # Convert to UTC if not already
                    end_dt = end_dt.astimezone(dt_timezone.utc)
                queryset = queryset.filter(timestamp__lte=end_dt)
            except (ValueError, AttributeError, TypeError) as e:
                # Invalid date format, ignore
                import logging

                logger = logging.getLogger(__name__)
                logger.warning(f"Invalid end_date format: {end_date}, error: {e}")
                pass

        return queryset.order_by("-timestamp")

    def list(self, request, *args, **kwargs):
        """List audit events with filtering"""
        return super().list(request, *args, **kwargs)

    def retrieve(self, request, *args, **kwargs):
        """Retrieve audit event by ID"""
        return super().retrieve(request, *args, **kwargs)

    @action(
        detail=False,
        methods=["get"],
        url_path="export",
        url_name="export",
        renderer_classes=[CSVRenderer, JSONRenderer],
    )
    def export(self, request):
        """
        Export audit events to CSV or JSON.

        Query params:
        - format: 'csv' or 'json' (default: 'json')
        - All other filters from list endpoint apply

        Note: DRF may interpret ?format=csv as a format suffix, causing routing issues.
        This method prioritizes query parameter over format suffix to avoid conflicts.
        """
        # Handle Http404 from content negotiation for invalid formats
        from django.http import Http404
        try:
            # Get format from query params - prioritize query param over format suffix
            # DRF's DefaultRouter creates format suffix patterns that can interfere with query params
            format_type = "json"  # default

            # CRITICAL: Check query parameter FIRST before any format suffix handling
            # This ensures ?format=csv works even if DRF tries to interpret it as a suffix
            # Use request.GET for Django's QueryDict to ensure we get the actual query parameter
            format_param = request.GET.get("format", "").lower().strip()
            if not format_param:
                # Fallback to query_params (DRF's version)
                format_param = request.query_params.get("format", "").lower().strip()

            if format_param in ["csv", "json"]:
                format_type = format_param
            # Also check DRF's format attribute (set by format suffix pattern) as fallback
            elif hasattr(request, "format") and request.format:
                format_type = request.format.lower()
            # Check Accept header for content negotiation (last resort)
            else:
                accept_header = request.META.get("HTTP_ACCEPT", "")
                if "text/csv" in accept_header.lower():
                    format_type = "csv"

            # If format is invalid and not in accepted formats, return JSON 404
            if format_param and format_param not in ["csv", "json"]:
                return Response(
                    {"detail": "Invalid format. Supported formats: csv, json"},
                    status=status.HTTP_404_NOT_FOUND,
                )

            # Get filtered queryset
            queryset = self.get_queryset()

            # Limit export size (safety measure)
            max_export_size = 10000
            queryset_count = queryset.count()
            if queryset_count > max_export_size:
                return Response(
                    {
                        "error": f"Export size exceeds maximum of {max_export_size} events. Please use filters to reduce the result set."
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )

            events = list(queryset[:max_export_size])

            if format_type == "csv":
                return self._export_csv(events)
            else:
                return self._export_json(events)
        except Http404:
            # DRF's content negotiation raised Http404 for invalid format
            # Return JSON 404 response as expected by the test
            return Response(
                {"detail": "Invalid format. Supported formats: csv, json"},
                status=status.HTTP_404_NOT_FOUND,
            )

    def _export_csv(self, events):
        """Export events as CSV"""
        from django.http import HttpResponse

        response = HttpResponse(content_type="text/csv; charset=utf-8")
        response["Content-Disposition"] = 'attachment; filename="audit_events.csv"'

        writer = csv.writer(response)
        writer.writerow(
            [
                "ID",
                "Timestamp",
                "Tenant",
                "Actor User",
                "Resource Type",
                "Resource ID",
                "Action",
                "Result",
                "Details",
            ]
        )

        for event in events:
            writer.writerow(
                [
                    str(event.id),
                    event.timestamp.isoformat(),
                    event.tenant.name if event.tenant else "",
                    event.actor_user.email if event.actor_user else "",
                    event.resource_type,
                    str(event.resource_id) if event.resource_id else "",
                    event.action,
                    event.result,
                    json.dumps(event.details_json),
                ]
            )

        return response

    def _export_json(self, events):
        """Export events as JSON"""
        serializer = self.get_serializer(events, many=True)
        return Response(serializer.data)
