# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor_agreements', '0003_enable_rls_processor_agreements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetprocessormembership',
            new_name='pa_asset_pr_tenant__16b98f_idx',
            old_name='pa_ast_proc_tenant__2c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='processor',
            new_name='pa_processo_tenant__a2521f_idx',
            old_name='pa_processor_tenant__7726c5_idx',
        ),
        migrations.RenameIndex(
            model_name='processoragreement',
            new_name='pa_agreemen_tenant__1cd129_idx',
            old_name='pa_agreement_tenant__5df5b4_idx',
        ),
        migrations.RenameIndex(
            model_name='processoragreement',
            new_name='pa_agreemen_tenant__c6960d_idx',
            old_name='pa_agreement_tenant__8f3e12_idx',
        ),
        migrations.RenameIndex(
            model_name='processoragreement',
            new_name='pa_agreemen_process_0147e9_idx',
            old_name='pa_agreement_process_8a90bd_idx',
        ),
    ]
