# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0003_add_purpose_version_and_grant_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentpurpose',
            new_name='consent_pur_tenant__70e7d6_idx',
            old_name='consent_purpos_tenant__bd29e8_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_tenant__8c45ea_idx',
            old_name='consent_record_tenant__45170b_idx',
        ),
        migrations.RenameIndex(
            model_name='consentrecord',
            new_name='consent_rec_tenant__563642_idx',
            old_name='consent_record_tenant__76bb80_idx',
        ),
    ]
