# Generated by Django 6.0 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workflowdefinition',
            name='workflow_def_name_version_unique',
        ),
        migrations.RemoveConstraint(
            model_name='workflowstep',
            name='workflow_step_inst_index_unique',
        ),
        migrations.RenameIndex(
            model_name='workflowdefinition',
            new_name='workflow_de_name_060d27_idx',
            old_name='workflow_def_name_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdefinition',
            new_name='workflow_de_name_6658a0_idx',
            old_name='workflow_def_name_version_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdefinition',
            new_name='workflow_de_is_acti_136d63_idx',
            old_name='workflow_def_active_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_tenant__bd9218_idx',
            old_name='workflow_inst_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_tenant__eb9218_idx',
            old_name='workflow_inst_tenant_name_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_status_293e15_idx',
            old_name='workflow_inst_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_workflo_c26fa6_idx',
            old_name='workflow_inst_name_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowinstance',
            new_name='workflow_in_status_57a7cd_idx',
            old_name='workflow_inst_status_started_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstate',
            new_name='workflow_st_workflo_23c6e2_idx',
            old_name='workflow_state_inst_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstate',
            new_name='workflow_st_snapsho_2f0950_idx',
            old_name='workflow_state_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstep',
            new_name='workflow_st_workflo_58d189_idx',
            old_name='workflow_step_inst_status_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstep',
            new_name='workflow_st_workflo_1aceca_idx',
            old_name='workflow_step_inst_index_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstep',
            new_name='workflow_st_status_fed7f5_idx',
            old_name='workflow_step_status_created_idx',
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, help_text='List of workflow names this workflow depends on'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Workflow metadata (tags, categories, etc.)'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow_instance', 'step_index')},
        ),
    ]
