# Generated by Django 6.0 on 2026-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_remove_transformation_workflow_references'),
        ('orchestration', '0002_add_workflow_instance_to_pipeline_execution'),
    ]

    operations = [
    ]
