# Generated by Django 6.0.3 on 2026-03-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0004_defer_workflow_instance_workflow_definition_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowstep",
            name="compensation_attempt",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of compensation attempts (Phase 68.2.3)"
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PAUSED", "Paused"),
                    ("ROLLING_BACK", "Rolling Back"),
                    ("ROLLED_BACK", "Rolled Back"),
                    ("COMPENSATION_INCOMPLETE", "Compensation Incomplete"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Workflow instance status",
                max_length=30,
            ),
        ),
    ]
