# Generated by Django 5.2.8 on 2026-05-19 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_add_ingestion_pipeline_trigger_edge_types'),
        ('orchestration', '0006_unique_constraint_and_check_constraints'),
        ('tenants', '0087_add_pipeline_dependency_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_type', models.CharField(choices=[('scheduled_ingestion', 'Scheduled Ingestion'), ('scheduled_export', 'Scheduled Export'), ('transformation', 'Transformation'), ('dq', 'Data Quality'), ('compliance', 'Compliance')], help_text='Type of the upstream pipeline', max_length=32)),
                ('pipeline_id', models.UUIDField(help_text='UUID of the upstream pipeline instance')),
                ('dependency_type', models.CharField(choices=[('DATA', 'Data'), ('TRIGGER', 'Trigger'), ('MANUAL', 'Manual')], default='DATA', help_text='Dependency relationship type', max_length=16)),
                ('downstream_pipeline_type', models.CharField(choices=[('scheduled_ingestion', 'Scheduled Ingestion'), ('scheduled_export', 'Scheduled Export'), ('transformation', 'Transformation'), ('dq', 'Data Quality'), ('compliance', 'Compliance')], help_text='Type of the downstream pipeline', max_length=32)),
                ('downstream_pipeline_id', models.UUIDField(help_text='UUID of the downstream pipeline instance')),
                ('created_by', models.CharField(choices=[('AUTO', 'Auto'), ('MANUAL', 'Manual'), ('LINEAGE_SYNC', 'Lineage Sync')], default='MANUAL', help_text='How this dependency was created', max_length=16)),
                ('priority', models.IntegerField(default=0, help_text='Execution priority — higher runs first (default 0)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When False, the dependency is skipped during resolution')),
                ('alert_webhook_url', models.CharField(blank=True, help_text='Webhook URL for dependency-failure alerts (SSRF-validated)', max_length=2048, null=True)),
                ('alert_email', models.CharField(blank=True, help_text='Email address for dependency-failure alerts', max_length=320, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineage_edge', models.ForeignKey(blank=True, help_text='Lineage edge that auto-generated this dependency (null for manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_dependencies', to='contracts.lineageedge')),
                ('tenant', models.ForeignKey(help_text='Tenant this dependency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_dependencies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pipeline_dependencies',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRunDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upstream_run_type', models.CharField(choices=[('scheduled_ingestion', 'Scheduled Ingestion'), ('scheduled_export', 'Scheduled Export'), ('transformation', 'Transformation'), ('dq', 'Data Quality'), ('compliance', 'Compliance')], help_text='Type of the upstream run', max_length=32)),
                ('upstream_run_id', models.UUIDField(help_text='UUID of the upstream run instance')),
                ('downstream_run_type', models.CharField(choices=[('scheduled_ingestion', 'Scheduled Ingestion'), ('scheduled_export', 'Scheduled Export'), ('transformation', 'Transformation'), ('dq', 'Data Quality'), ('compliance', 'Compliance')], help_text='Type of the downstream run', max_length=32)),
                ('downstream_run_id', models.UUIDField(help_text='UUID of the downstream run instance')),
                ('upstream_status', models.CharField(help_text='Terminal status of the upstream run at resolution time', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_dependency', models.ForeignKey(help_text='Parent PipelineDependency definition', on_delete=django.db.models.deletion.CASCADE, related_name='run_dependencies', to='orchestration.pipelinedependency')),
                ('tenant', models.ForeignKey(help_text='Tenant this run dependency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_run_dependencies', to='tenants.tenant')),
            ],
            options={
                'db_table': 'pipeline_run_dependencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinedependency',
            index=models.Index(fields=['tenant', 'pipeline_type', 'pipeline_id'], name='pipeline_de_tenant__2fe60d_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinedependency',
            index=models.Index(fields=['tenant', 'downstream_pipeline_type', 'downstream_pipeline_id'], name='pipeline_de_tenant__9579b9_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinedependency',
            index=models.Index(fields=['tenant', 'is_active'], name='pipeline_de_tenant__5cbe50_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinedependency',
            index=models.Index(fields=['lineage_edge'], name='pipeline_de_lineage_69baca_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinedependency',
            constraint=models.UniqueConstraint(fields=('tenant', 'pipeline_type', 'pipeline_id', 'dependency_type', 'downstream_pipeline_type', 'downstream_pipeline_id'), name='uq_pipeline_dependency_scope'),
        ),
        migrations.AddIndex(
            model_name='pipelinerundependency',
            index=models.Index(fields=['tenant', 'upstream_run_type', 'upstream_run_id'], name='pipeline_ru_tenant__0bacbc_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerundependency',
            index=models.Index(fields=['tenant', 'downstream_run_type', 'downstream_run_id'], name='pipeline_ru_tenant__b0c6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pipelinerundependency',
            index=models.Index(fields=['pipeline_dependency'], name='pipeline_ru_pipelin_42786d_idx'),
        ),
    ]
