# Generated by Django 6.0 on 2026-05-24 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0009_merge"),
        ("tenants", "0097_fix_notification_opt_outs_on_tenant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pipelinedependency",
            name="uq_pipeline_dependency_scope",
        ),
        migrations.RemoveIndex(
            model_name="pipelinedependency",
            name="pipeline_de_tenant__2fe60d_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinedependency",
            name="pipeline_de_tenant__9579b9_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinedependency",
            name="pipeline_de_tenant__5cbe50_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinedependency",
            name="pipeline_de_lineage_69baca_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinerundependency",
            name="pipeline_ru_tenant__0bacbc_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinerundependency",
            name="pipeline_ru_tenant__b0c6e5_idx",
        ),
        migrations.RemoveIndex(
            model_name="pipelinerundependency",
            name="pipeline_ru_pipelin_42786d_idx",
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="alert_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="dependency_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="downstream_pipeline_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="downstream_pipeline_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="pipeline_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="pipeline_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pipelinedependency",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_dependencies",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="downstream_run_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="downstream_run_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="pipeline_dependency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="run_dependencies",
                to="orchestration.pipelinedependency",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pipeline_run_dependencies",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="upstream_run_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="upstream_run_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="pipelinerundependency",
            name="upstream_status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PAUSED", "Paused"),
                    ("ROLLING_BACK", "Rolling Back"),
                    ("ROLLED_BACK", "Rolled Back"),
                    ("COMPENSATION_INCOMPLETE", "Compensation Incomplete"),
                    ("COMPENSATING", "Compensating"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Workflow instance status",
                max_length=30,
            ),
        ),
        migrations.AlterModelTable(
            name="pipelinedependency",
            table="orchestration_pipeline_dependencies",
        ),
        migrations.AlterModelTable(
            name="pipelinerundependency",
            table="orchestration_pipeline_run_dependencies",
        ),
        migrations.RemoveField(
            model_name="pipelinedependency",
            name="alert_webhook_url",
        ),
        migrations.RemoveField(
            model_name="pipelinedependency",
            name="lineage_edge",
        ),
    ]
