# Generated by Django 6.0.4 on 2026-06-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0104_limitdimension_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMovementConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dlt_dev_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable dlt dev mode for this tenant (skips schema evolution)",
                    ),
                ),
                (
                    "max_parallel_pipelines",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Max concurrent dlt pipelines per tenant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_movement_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "data_movement_config",
            },
        ),
    ]
