# Generated by Django 6.0 on 2026-01-05 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_add_odps_refs_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the marketplace connection', primary_key=True, serialize=False)),
                ('marketplace_type', models.CharField(choices=[('SNOWFLAKE_DATA_MARKETPLACE', 'SNOWFLAKE_DATA_MARKETPLACE'), ('AWS_DATA_EXCHANGE', 'AWS_DATA_EXCHANGE'), ('DATABRICKS_MARKETPLACE', 'DATABRICKS_MARKETPLACE'), ('GOOGLE_CLOUD_MARKETPLACE', 'GOOGLE_CLOUD_MARKETPLACE'), ('AZURE_MARKETPLACE', 'AZURE_MARKETPLACE'), ('DATA_WORLD', 'DATA_WORLD'), ('KAGGLE', 'KAGGLE'), ('QUANDL', 'QUANDL'), ('APIS_GURU', 'APIS_GURU'), ('RAPIDAPI', 'RAPIDAPI'), ('PROGRAMMABLE_WEB', 'PROGRAMMABLE_WEB'), ('DATA_GOV', 'DATA_GOV'), ('EUROPEAN_DATA_PORTAL', 'EUROPEAN_DATA_PORTAL'), ('CKAN_INSTANCE', 'CKAN_INSTANCE'), ('CUSTOM', 'CUSTOM')], help_text='Type of marketplace (e.g., SNOWFLAKE_DATA_MARKETPLACE, AWS_DATA_EXCHANGE)', max_length=50)),
                ('name', models.CharField(help_text='Human-readable name for this connection (unique per tenant)', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Encrypted connection configuration (API keys, endpoints, etc.)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is active and can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_connections', to='tenants.tenant')),
            ],
            options={
                'db_table': 'marketplace_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'marketplace_type'], name='marketplace_tenant__2b1851_idx'), models.Index(fields=['tenant', 'is_active'], name='marketplace_tenant__2590c0_idx'), models.Index(fields=['marketplace_type', 'is_active'], name='marketplace_marketp_f8af2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_connection_name')],
            },
        ),
    ]
