# Generated by Django 6.0 on 2026-01-05 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('tenants', '0006_add_odps_refs_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceconnection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted connection configuration (API keys, endpoints, etc.)'),
        ),
        migrations.AlterField(
            model_name='marketplaceconnection',
            name='marketplace_type',
            field=models.CharField(choices=[('SNOWFLAKE_DATA_MARKETPLACE', 'Snowflake Data Marketplace'), ('AWS_DATA_EXCHANGE', 'Aws Data Exchange'), ('DATABRICKS_MARKETPLACE', 'Databricks Marketplace'), ('GOOGLE_CLOUD_MARKETPLACE', 'Google Cloud Marketplace'), ('AZURE_MARKETPLACE', 'Azure Marketplace'), ('DATA_WORLD', 'Data World'), ('KAGGLE', 'Kaggle'), ('QUANDL', 'Quandl'), ('APIS_GURU', 'Apis Guru'), ('RAPIDAPI', 'Rapidapi'), ('PROGRAMMABLE_WEB', 'Programmable Web'), ('DATA_GOV', 'Data Gov'), ('EUROPEAN_DATA_PORTAL', 'European Data Portal'), ('CKAN_INSTANCE', 'Ckan Instance'), ('CUSTOM', 'Custom')], help_text='Type of marketplace (e.g., SNOWFLAKE_DATA_MARKETPLACE, AWS_DATA_EXCHANGE)', max_length=50),
        ),
        migrations.CreateModel(
            name='MarketplaceSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the sync job', primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('BIDIRECTIONAL', 'Bidirectional')], help_text='Sync direction: PUSH, PULL, or BIDIRECTIONAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', help_text='Sync job status: PENDING, RUNNING, COMPLETED, FAILED, PARTIAL', max_length=20)),
                ('items_synced', models.IntegerField(default=0, help_text='Number of items successfully synced')),
                ('items_failed', models.IntegerField(default=0, help_text='Number of items that failed to sync')),
                ('errors', models.JSONField(blank=True, default=list, help_text='List of error messages encountered during sync')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the sync operation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sync job completed (success or failure)', null=True)),
                ('connection', models.ForeignKey(help_text='Marketplace connection used for this sync', on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.marketplaceconnection')),
                ('tenant', models.ForeignKey(help_text='Tenant this sync job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_sync_jobs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'marketplace_sync_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'connection'], name='marketplace_tenant__801ae8_idx'), models.Index(fields=['tenant', 'status'], name='marketplace_tenant__437c82_idx'), models.Index(fields=['connection', 'status'], name='marketplace_connect_efcfcf_idx'), models.Index(fields=['status', 'created_at'], name='marketplace_status_718840_idx')],
            },
        ),
    ]
