# Generated by Django 6.0 on 2026-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_marketplaceconnection_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesyncjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
