# Generated by Django 6.0 on 2026-01-05 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assets_tenant_health_idx_and_more'),
        ('integrations', '0003_marketplacesyncjob_updated_at'),
        ('tenants', '0006_add_odps_refs_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the mapping', primary_key=True, serialize=False)),
                ('external_listing_id', models.CharField(help_text='External marketplace listing identifier', max_length=255)),
                ('external_resource_ids', models.JSONField(blank=True, default=list, help_text='List of external resource identifiers (e.g., dataset IDs, file IDs)')),
                ('sync_metadata', models.JSONField(blank=True, default=dict, help_text='Metadata about the synchronization (last sync status, errors, etc.)')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful synchronization', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text='Marketplace connection this mapping is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.marketplaceconnection')),
                ('hub_asset', models.ForeignKey(help_text='Hub asset being mapped to external marketplace', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='assets.asset')),
                ('tenant', models.ForeignKey(help_text='Tenant this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_mappings', to='tenants.tenant')),
            ],
            options={
                'db_table': 'marketplace_mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'connection'], name='marketplace_tenant__43e923_idx'), models.Index(fields=['connection', 'hub_asset'], name='marketplace_connect_0b2496_idx'), models.Index(fields=['tenant', 'hub_asset'], name='marketplace_tenant__58c3cc_idx'), models.Index(fields=['external_listing_id'], name='marketplace_externa_f710ad_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'hub_asset'), name='unique_connection_asset_mapping')],
            },
        ),
    ]
