# Generated by Django 6.0 on 2026-01-06 00:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_marketplacemapping'),
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMarketplaceSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the scheduled sync', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Scheduled sync name (unique per tenant)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('direction', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('BIDIRECTIONAL', 'Bidirectional')], help_text='Sync direction: PUSH, PULL, or BIDIRECTIONAL', max_length=20)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM_CRON', 'Custom Cron')], default='DAILY', help_text='Schedule type: DAILY, WEEKLY, MONTHLY, CUSTOM_CRON', max_length=20)),
                ('schedule_config', models.JSONField(default=dict, help_text='Schedule configuration (cron expression, timezone, days of week, time)')),
                ('sync_options', models.JSONField(blank=True, default=dict, help_text='Sync options (asset_ids, listing_ids, filters, options) to use for each sync')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='ACTIVE', help_text='Status: ACTIVE, PAUSED, ERROR', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next scheduled run time (calculated based on schedule)', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last run time', null=True)),
                ('last_sync_job_id', models.UUIDField(blank=True, help_text='ID of the last sync job created', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text='Marketplace connection to use for sync', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_syncs', to='integrations.marketplaceconnection')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this scheduled sync', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_marketplace_syncs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this scheduled sync belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_marketplace_syncs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'scheduled_marketplace_syncs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'connection'], name='scheduled_m_tenant__18b0b2_idx'), models.Index(fields=['tenant', 'status'], name='scheduled_m_tenant__c6dd2a_idx'), models.Index(fields=['status', 'next_run_at'], name='scheduled_m_status_32fd71_idx'), models.Index(fields=['connection', 'status'], name='scheduled_m_connect_aa32ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_scheduled_sync_name_per_tenant')],
            },
        ),
    ]
