# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_scheduledmarketplacesync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceconnection",
            name="marketplace_type",
            field=models.CharField(
                choices=[
                    ("SNOWFLAKE_DATA_MARKETPLACE", "Snowflake Data Marketplace"),
                    ("AWS_DATA_EXCHANGE", "Aws Data Exchange"),
                    ("DATABRICKS_MARKETPLACE", "Databricks Marketplace"),
                    ("GOOGLE_CLOUD_MARKETPLACE", "Google Cloud Marketplace"),
                    ("AZURE_MARKETPLACE", "Azure Marketplace"),
                    ("DATA_WORLD", "Data World"),
                    ("KAGGLE", "Kaggle"),
                    ("QUANDL", "Quandl"),
                    ("APIS_GURU", "Apis Guru"),
                    ("RAPIDAPI", "Rapidapi"),
                    ("PROGRAMMABLE_WEB", "Programmable Web"),
                    ("DATA_GOV", "Data Gov"),
                    ("EUROPEAN_DATA_PORTAL", "European Data Portal"),
                    ("CKAN_INSTANCE", "Ckan Instance"),
                    ("CUSTOM", "Custom"),
                    ("IN_MEMORY_FAKE", "In Memory Fake"),
                ],
                help_text="Type of marketplace (e.g., SNOWFLAKE_DATA_MARKETPLACE, AWS_DATA_EXCHANGE)",
                max_length=50,
            ),
        ),
    ]
