# Generated by Django 6.0 on 2026-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_add_syncjob_conn_status_created_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplaceconnection",
            name="consecutive_failure_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of consecutive sync failures (Phase 71 — auto-disable)"
            ),
        ),
    ]
