# Generated by Django 6.0.3 on 2026-05-01 11:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_alter_marketplaceconnection_consecutive_failure_count"),
        ("tenants", "0023_add_archival_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenLineageDeadLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_payload_encrypted",
                    models.TextField(
                        help_text="Encrypted OpenLineage event payload. Decrypt via ``hub.apps.webhooks.encryption.decrypt_secret``; never log decrypted contents."
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="OpenLineage event id (run.runId). Used for idempotent replay — a re-emitted event keeps the same id so Marquez deduplicates.",
                        max_length=255,
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="Marquez (or other receiver) URL the adapter was POSTing to.",
                        max_length=2048,
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        help_text="HTTP status / exception summary that caused the DLQ.",
                        max_length=255,
                    ),
                ),
                (
                    "failure_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full error body / stack trace (truncated to 2KB).",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=1, help_text="Total adapter delivery attempts before DLQ insert."
                    ),
                ),
                (
                    "replay_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="DLQ-replay attempts (separate from the original adapter retries).",
                    ),
                ),
                (
                    "permanently_failed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Set when ``replay_attempts >= 10``. Replay sweeps skip permanently-failed rows; ops investigates each one.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_replay_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when a replay finally succeeded; nulled rows are still pending.",
                        null=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant whose event landed in the DLQ.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openlineage_dead_letters",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenLineage Dead Letter",
                "verbose_name_plural": "OpenLineage Dead Letters",
                "db_table": "openlineage_dead_letter",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "permanently_failed", "delivered_at"],
                        name="ol_dlq_pending_idx",
                    ),
                    models.Index(fields=["event_id"], name="ol_dlq_eventid_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OpenLineageIngestApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label (e.g. 'staging-marquez', 'datakin-prod').",
                        max_length=120,
                    ),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        db_index=True,
                        help_text="First 8 characters of the plaintext key after the ``msh_ol_`` namespace prefix. Used for log-grep + UI display so operators can identify a key without seeing the secret.",
                        max_length=16,
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        help_text="Bcrypt hash of the plaintext key (cost factor 12).",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When the key stops authenticating. NULL = never expires. The rotate command sets this to ``now + 7 days`` on the outgoing key when issuing a fresh successor (REQ-LIN-F4-003).",
                        null=True,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Set when an operator explicitly revokes the key. A revoked key fails authentication immediately regardless of ``expires_at``.",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Best-effort last-authenticated-request timestamp.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who created this key.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_openlineage_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this key belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openlineage_ingest_keys",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "OpenLineage Ingest API Key",
                "verbose_name_plural": "OpenLineage Ingest API Keys",
                "db_table": "openlineage_ingest_api_key",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "revoked_at", "expires_at"],
                        name="ol_key_tenant_active_idx",
                    )
                ],
            },
        ),
    ]
