# Generated by Django 6.0 on 2025-12-25 15:15

import django.db.models.deletion
import hub.apps.mesh.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0006_add_odps_refs_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMeshDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Domain name (unique per tenant)", max_length=255),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Domain description", null=True),
                ),
                (
                    "boundaries",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Domain boundaries as JSON (data products, schemas, access patterns, etc.)",
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Domain capabilities as JSON (APIs, services, data products, etc.)",
                    ),
                ),
                (
                    "resource_quota",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Resource quotas as JSON (storage_gb, compute_hours, api_calls_per_day, etc.)",
                    ),
                ),
                (
                    "resource_usage",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Current resource usage as JSON (storage_gb_used, compute_hours_used, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        help_text="Domain status: ACTIVE, INACTIVE, or ARCHIVED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this domain",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_mesh_domains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this domain belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesh_domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "data_mesh_domains",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant"], name="data_mesh_d_tenant__1b5fcf_idx"),
                    models.Index(fields=["owner"], name="data_mesh_d_owner_i_270aae_idx"),
                    models.Index(fields=["status"], name="data_mesh_d_status_b39db4_idx"),
                    models.Index(fields=["created_at"], name="data_mesh_d_created_14f59d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "name"), name="unique_domain_name_per_tenant"
                    )
                ],
            },
        ),
    ]
