# Generated by Django 6.0 on 2025-12-25 15:42

import django.db.models.deletion
import hub.apps.mesh.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_remove_asset_assets_tenant_health_idx_and_more"),
        (
            "governance",
            "0004_rename_access_certifications_tenant_user_idx_access_cert_tenant__6415d5_idx_and_more",
        ),
        ("mesh", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NON_COMPLIANT", "Non-Compliant"),
                            ("PARTIAL", "Partially Compliant"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Compliance status: COMPLIANT, NON_COMPLIANT, PARTIAL, or UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "violations",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Violations as JSON (list of violation objects with type, severity, description, etc.)",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when report was generated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset this compliance report is for (optional, for asset-specific reports)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mesh_compliance_reports",
                        to="assets.asset",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="Domain this compliance report is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_reports",
                        to="mesh.datameshdomain",
                    ),
                ),
            ],
            options={
                "db_table": "mesh_compliance_reports",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["domain"], name="mesh_compli_domain__57b446_idx"),
                    models.Index(fields=["asset"], name="mesh_compli_asset_i_f5e259_idx"),
                    models.Index(
                        fields=["compliance_status"], name="mesh_compli_complia_f8c2e7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "overrides",
                    models.JSONField(
                        blank=True,
                        default=hub.apps.mesh.models.default_empty_dict,
                        help_text="Policy overrides as JSON (conditions, effect, priority, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPLIED", "Applied"),
                            ("FAILED", "Failed"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        help_text="Application status: PENDING, APPLIED, FAILED, or REVOKED",
                        max_length=20,
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when policy was applied", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who applied this policy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_mesh_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        help_text="Domain this policy is applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_applications",
                        to="mesh.datameshdomain",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Policy being applied (nullable if policy is deleted)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mesh_domain_applications",
                        to="governance.accesspolicy",
                    ),
                ),
            ],
            options={
                "db_table": "policy_applications",
                "ordering": ["-applied_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["domain"], name="policy_appl_domain__bff283_idx"),
                    models.Index(fields=["policy"], name="policy_appl_policy__e1c40d_idx"),
                    models.Index(fields=["status"], name="policy_appl_status_fa79f8_idx"),
                ],
            },
        ),
    ]
