# Generated by Django 6.0 on 2025-12-26 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0002_compliancereport_policyapplication'),
        ('orchestration', '0002_add_workflow_instance_to_pipeline_execution'),
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datameshdomain',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, help_text='Workflow instance that created this domain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domains', to='orchestration.workflowinstance'),
        ),
        migrations.AddIndex(
            model_name='datameshdomain',
            index=models.Index(fields=['workflow_instance'], name='data_mesh_d_workflo_5ce065_idx'),
        ),
    ]
