# Generated by Django 4.2.16 on 2025-11-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_tenant__a46df1_idx",
            old_name="jobs_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_tenant__056fbf_idx",
            old_name="jobs_tenant_type_status_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_resourc_f8bc8a_idx",
            old_name="jobs_resource_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_status_24a2b0_idx",
            old_name="jobs_status_created_idx",
        ),
    ]
