# Generated by Django 6.0 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_jobs_tenant_status_idx_jobs_tenant__a46df1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('DQ_RUN', 'Data Quality Run'), ('COMPLIANCE_RUN', 'Compliance Run'), ('CONTRACT_VALIDATION', 'Contract Validation'), ('SEMANTIC_MAPPING', 'Semantic Mapping'), ('CONTRACT_MIGRATION', 'Contract Migration'), ('SCHEDULED_INGESTION', 'Scheduled Ingestion'), ('RETENTION_POLICY_ENFORCEMENT', 'Retention Policy Enforcement'), ('SEARCH_INDEX_UPDATE', 'Search Index Update'), ('ODPS_NORMALIZATION', 'ODPS Normalization'), ('ODPS_REF_RESOLUTION', 'ODPS $ref Resolution'), ('ODPS_EXPORT', 'ODPS Export'), ('ODPS_SEMANTIC_MAPPING', 'ODPS Semantic Mapping'), ('ODPS_LINKING', 'ODPS Linking'), ('TRANSFORMATION_PIPELINE_EXECUTION', 'Transformation Pipeline Execution')], help_text='Job type: DQ_RUN, COMPLIANCE_RUN, CONTRACT_VALIDATION, etc.', max_length=50),
        ),
    ]
