# Generated by Django 6.0 on 2026-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_job_priority'),
        ('jobs', '0005_remove_transformation_job_references'),
    ]

    operations = [
    ]
