# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_merge_20260116_1227"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_priorit_d307fb_idx",
            old_name="jobs_priority_status_idx",
        ),
        migrations.RenameIndex(
            model_name="job",
            new_name="jobs_tenant__171f46_idx",
            old_name="jobs_tenant_priority_status_idx",
        ),
    ]
