# Generated by Django 6.0 on 2026-03-19 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("jobs", "0007_rename_jobs_priority_status_idx_jobs_priorit_d307fb_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SideEffect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "run_object_id",
                    models.UUIDField(help_text="Primary key of the related run instance"),
                ),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("COST_TRACKING", "Cost Tracking"),
                            ("DLQ_SYNC", "DLQ Sync"),
                            ("NOTIFICATION", "Notification"),
                            ("AUDIT_EVENT", "Audit Event"),
                        ],
                        help_text="Side-effect type: COST_TRACKING, DLQ_SYNC, NOTIFICATION, AUDIT_EVENT",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Execution status: PENDING, COMPLETED, FAILED",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message on last failure", null=True
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of execution attempts so far"
                    ),
                ),
                (
                    "context_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Serialised context needed to replay the side effect (e.g. run_id, status)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_content_type",
                    models.ForeignKey(
                        help_text="ContentType of the run (ScheduledIngestionRun or ScheduledExportRun)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "side_effects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "attempt_count", "updated_at"],
                        name="side_effect_status_129088_idx",
                    ),
                    models.Index(
                        fields=["run_content_type", "run_object_id"],
                        name="side_effect_run_con_a44d82_idx",
                    ),
                ],
            },
        ),
    ]
