# Generated by Django 6.0.3 on 2026-03-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("jobs", "0011_add_ml_job_types"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="job_status_valid",
        ),
        migrations.RemoveIndex(
            model_name="failedjobdlq",
            name="dlq_tenant_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="failedjobdlq",
            name="dlq_resolved_idx",
        ),
        migrations.RemoveIndex(
            model_name="failedjobdlq",
            name="dlq_queue_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="sideeffect",
            name="side_effect_status_129088_idx",
        ),
        migrations.RemoveIndex(
            model_name="sideeffect",
            name="side_effect_run_con_a44d82_idx",
        ),
        migrations.AlterField(
            model_name="failedjobdlq",
            name="resolved_at",
            field=models.DateTimeField(blank=True, help_text="When resolved", null=True),
        ),
        migrations.AlterField(
            model_name="failedjobdlq",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of times retried"),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("DQ_RUN", "Data Quality Run"),
                    ("COMPLIANCE_RUN", "Compliance Run"),
                    ("CONTRACT_VALIDATION", "Contract Validation"),
                    ("SEMANTIC_MAPPING", "Semantic Mapping"),
                    ("CONTRACT_MIGRATION", "Contract Migration"),
                    ("SCHEDULED_INGESTION", "Scheduled Ingestion"),
                    ("RETENTION_POLICY_ENFORCEMENT", "Retention Policy Enforcement"),
                    ("SEARCH_INDEX_UPDATE", "Search Index Update"),
                    ("ODPS_NORMALIZATION", "ODPS Normalization"),
                    ("ODPS_REF_RESOLUTION", "ODPS $ref Resolution"),
                    ("ODPS_EXPORT", "ODPS Export"),
                    ("ODPS_SEMANTIC_MAPPING", "ODPS Semantic Mapping"),
                    ("ODPS_LINKING", "ODPS Linking"),
                    ("VIRTUAL_QUERY_EXECUTION", "Virtual Query Execution"),
                    ("MARKETPLACE_SYNC", "Marketplace Sync"),
                    ("ML_TRAINING", "ML Training"),
                    ("ML_INFERENCE", "ML Inference"),
                    ("TRANSFORMATION", "Transformation Pipeline"),
                ],
                help_text="Job type: DQ_RUN, COMPLIANCE_RUN, CONTRACT_VALIDATION, etc.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="context_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("COST_TRACKING", "Cost Tracking"),
                    ("DLQ_SYNC", "DLQ Sync"),
                    ("NOTIFICATION", "Notification"),
                    ("AUDIT_EVENT", "Audit Event"),
                ],
                help_text="Side-effect type",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="run_content_type",
            field=models.ForeignKey(
                help_text="ContentType of the related run model",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="sideeffect",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
