# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobtype_retention_enforcement_sweep'),
        ('jobs', '0018_enable_rls_failed_job_dlq'),
    ]

    operations = [
    ]
