# Generated by Django 4.2.16 on 2025-11-23 19:20

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant name (unique per environment)', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe tenant identifier', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Tenant status: ACTIVE, SUSPENDED, or DELETED', max_length=20)),
                ('kyc_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', help_text='KYC verification status: UNVERIFIED or VERIFIED', max_length=20)),
                ('region', models.CharField(blank=True, help_text='Cloud region (e.g., us-east-1, eu-west-1)', max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when tenant was marked for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['status'], name='tenants_status_80d9b6_idx'), models.Index(fields=['kyc_status'], name='tenants_kyc_sta_93528b_idx'), models.Index(fields=['region'], name='tenants_region_097198_idx')],
            },
        ),
    ]
