# Generated by Django 6.0 on 2025-12-08 10:37

import hub.apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_tenant_config'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantconfig',
            new_name='tenant_conf_tenant__37e737_idx',
            old_name='tenant_configs_tenant_idx',
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='allowed_compliance_regimes',
            field=models.JSONField(blank=True, default=hub.apps.tenants.models.default_empty_list, help_text="List of compliance regimes available to this tenant (e.g., ['GDPR', 'LGPD', 'CCPA'])"),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='default_compliance_regimes',
            field=models.JSONField(blank=True, default=hub.apps.tenants.models.default_empty_list, help_text='Default compliance regimes applied to intake flows (subset of allowed_compliance_regimes)'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='rate_limits',
            field=models.JSONField(blank=True, default=hub.apps.tenants.models.default_empty_dict, help_text='Per-endpoint category rate limits (JSON structure)', null=True),
        ),
    ]
