# Generated by Django 6.0 on 2025-12-16 13:34

import hub.apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_sso_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantconfig',
            name='sso_config',
            field=models.JSONField(blank=True, default=hub.apps.tenants.models.default_empty_dict, help_text='SSO configuration (SAML and OIDC settings)', null=True),
        ),
    ]
