# Generated by Django 6.0 on 2025-12-19 17:59

import hub.apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantconfig_sso_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfig',
            name='odps_refs_config',
            field=models.JSONField(blank=True, default=hub.apps.tenants.models.default_empty_dict, help_text='ODPS $ref resolver configuration (URL allowlist/denylist overrides)', null=True),
        ),
    ]
