# Generated by Django 6.0.3 on 2026-03-06 19:58

import hub.apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_add_workflows_enabled"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tenant",
            new_name="tenants_plan_id_487a30_idx",
            old_name="tenant_plan_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantplan",
            new_name="tenant_plan_slug_fe3df7_idx",
            old_name="tenant_plan_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantplan",
            new_name="tenant_plan_tier_98cb12_idx",
            old_name="tenant_plan_tier_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantplan",
            new_name="tenant_plan_is_acti_09282c_idx",
            old_name="tenant_plan_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantusagesummary",
            new_name="tenant_usag_tenant__417dc1_idx",
            old_name="tenant_usage_tenant_period_start_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantusagesummary",
            new_name="tenant_usag_tenant__400e54_idx",
            old_name="tenant_usage_tenant_period_end_idx",
        ),
        migrations.RenameIndex(
            model_name="tenantusagesummary",
            new_name="tenant_usag_period__64d999_idx",
            old_name="tenant_usage_period_idx",
        ),
        migrations.AlterField(
            model_name="tenantconfig",
            name="rate_limits",
            field=models.JSONField(
                blank=True,
                default=hub.apps.tenants.models.default_empty_dict,
                help_text="Per-endpoint category rate limits (JSON). API Gateway: api_gateway_requests_per_hour (int).",
                null=True,
            ),
        ),
    ]
