# Generated by Django 6.0 on 2026-03-21 11:56

import django.core.validators
import hub.apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_add_user_tenant_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantplan",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="billing_interval",
            field=models.CharField(
                choices=[("month", "Monthly"), ("year", "Yearly")],
                default="month",
                help_text="Billing interval for recurring subscriptions",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Tier ordering for upgrade/downgrade validation (FREE=0, PRO=1, ENTERPRISE=2)",
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="price_amount_cents",
            field=models.IntegerField(
                default=0,
                help_text="Price amount in cents (e.g., 2999 = $29.99). 0 for free plans.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="price_currency",
            field=models.CharField(
                default="usd",
                help_text="ISO 4217 currency code (e.g., 'usd', 'eur', 'brl')",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID (prod_...) — one per plan, reused across subscriptions",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="limits_json",
            field=models.JSONField(
                default=hub.apps.tenants.models.default_empty_dict,
                help_text="Plan limits as JSON (e.g., {'max_assets': 10, 'max_api_calls_per_month': 10000})",
            ),
        ),
        migrations.AddIndex(
            model_name="tenantplan",
            index=models.Index(fields=["order"], name="tenant_plan_order_154bcc_idx"),
        ),
    ]
