# Generated by Django 6.0 on 2026-03-21 11:56
# Data migration: populate TenantPlan.order from tier for existing rows.

from django.db import migrations


TIER_ORDER = {
    "FREE": 0,
    "PRO": 1,
    "ENTERPRISE": 2,
}


def populate_order_from_tier(apps, schema_editor):
    """Set order field on existing TenantPlan rows based on their tier."""
    TenantPlan = apps.get_model("tenants", "TenantPlan")
    for tier_value, order_value in TIER_ORDER.items():
        TenantPlan.objects.filter(tier=tier_value, order=0).exclude(
            tier="FREE"  # FREE tier order=0 is correct, don't skip it
        ).update(order=order_value)
    # Explicitly set PRO and ENTERPRISE (FREE is already 0 by default)
    TenantPlan.objects.filter(tier="PRO").update(order=1)
    TenantPlan.objects.filter(tier="ENTERPRISE").update(order=2)


def reverse_order(apps, schema_editor):
    """Reset all order fields back to 0."""
    TenantPlan = apps.get_model("tenants", "TenantPlan")
    TenantPlan.objects.all().update(order=0)


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_billing_system_hardening_113a"),
    ]

    operations = [
        migrations.RunPython(populate_order_from_tier, reverse_order),
    ]
