# Generated by Django 6.0.3 on 2026-03-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_backfill_plan_limit_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantplan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID (price_...) — pre-created price; skips price_data when set",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
