# Generated by Django 6.0 on 2026-03-22 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_add_stripe_price_id_to_tenant_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ml_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="ML/AI package plan for this tenant",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ml_tenants",
                to="tenants.tenantplan",
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="category",
            field=models.CharField(
                choices=[("BASE", "Base Platform"), ("ML_AI", "ML / AI")],
                default="BASE",
                help_text="Plan category: BASE (platform) or ML_AI (ML/AI package)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID (price_...)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID (prod_...)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantplan",
            index=models.Index(fields=["category"], name="tenant_plan_categor_ed965c_idx"),
        ),
    ]
