# Generated by Django 6.0 on 2026-03-22 21:06

from django.db import migrations, models


def add_column_if_not_exists(apps, schema_editor):
    """Idempotent column addition — handles partially applied migration."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'tenants' AND column_name IN ('kyc_expires_at', 'kyc_verified_at')"
        )
        existing = {row[0] for row in cursor.fetchall()}

        if "kyc_expires_at" not in existing:
            cursor.execute(
                'ALTER TABLE "tenants" ADD COLUMN "kyc_expires_at" '
                "TIMESTAMP WITH TIME ZONE NULL"
            )
        if "kyc_verified_at" not in existing:
            cursor.execute(
                'ALTER TABLE "tenants" ADD COLUMN "kyc_verified_at" '
                "TIMESTAMP WITH TIME ZONE NULL"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_add_plan_category_and_ml_plan"),
    ]

    operations = [
        migrations.RunPython(add_column_if_not_exists, migrations.RunPython.noop),
    ]
