# Generated by Django 6.0 on 2026-03-30 19:05

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_encrypt_sso_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'default_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='tenant',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        # kyc_expires_at / kyc_verified_at are added in 0020_add_kyc_date_fields (RunPython).
    ]
