# Generated by Django 6.0 on 2026-04-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0022_add_ab_test_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="kyc_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when KYC verification expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="kyc_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when KYC was last verified", null=True
            ),
        ),
    ]
