# Generated by Django 6.0 on 2026-04-17 21:17
#
# The `kyc_expires_at` and `kyc_verified_at` columns are added idempotently
# in migration 0020_add_kyc_date_fields.py via a RunPython / raw SQL
# `ADD COLUMN IF NOT EXISTS` pattern. That approach is opaque to Django's
# migration autodetector, so subsequent `makemigrations` runs keep
# re-generating duplicate `AddField` operations for the same columns.
#
# This migration reconciles Django's migration state with the already-applied
# schema by using `SeparateDatabaseAndState`:
#   * `database_operations=[]` — the columns already exist (added by 0020).
#     Running `AddField` here a second time fails with PostgreSQL's
#     `column ... already exists` (this broke staging deploy on 2026-04-23).
#   * `state_operations=[AddField(...)]` — tells the autodetector that the
#     Tenant model already has these fields, so future `makemigrations`
#     invocations won't try to generate yet another duplicate.
#
# Audit migration `audit/0003_add_archival_fields.py` depends on this one
# via the standard `dependencies` chain, so this migration must remain in
# the tree to preserve migration ordering.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0022_add_ab_test_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="tenant",
                    name="kyc_expires_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when KYC verification expires",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="tenant",
                    name="kyc_verified_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when KYC was last verified",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
