# Generated by Django 5.2.8 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_tenant_compliance_consent_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='compliance_dsar_enabled',
            field=models.BooleanField(default=False, help_text='When True, public DSAR submission, statutory SLA jobs, and handler queues are active per Phase 232.2.'),
        ),
    ]
