# Generated by Django 6.0 — Phase 232.3 breach workflow flag

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0043_phase232_dsar_and_tenant_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="compliance_breach_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, breach incident APIs, supervisory notification drafts, "
                    "template overrides, and SLA jobs are enabled per Phase 232.3."
                ),
            ),
        ),
    ]
