# Generated by Django 6 — Phase 232.6 tenant flag

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0046_tenant_compliance_dpia_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="compliance_processor_agreements_enabled",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "When True, processor/agreement tracker APIs, asset processor links, "
                    "and expiry jobs are enabled per Phase 232.6."
                ),
            ),
        ),
    ]
