# Generated by Django 6.0.4 on 2026-05-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0069_phase_275_warehouse_flags"),
        ("tenants", "0071_phase_274_3_semantic_capability_flags"),
        ("tenants", "0072_ensure_warehouse_flags_columns"),
    ]

    operations = []
