# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0074_enable_rls_impersonation_session'),
        ('tenants', '0075_enable_rls_feature_flag_flip_approval'),
    ]

    operations = [
    ]
