# Generated by Django 6.0.4 on 2026-05-14 03:05
# Manually adjusted: warehouse AddField operations wrapped in SeparateDatabaseAndState
# because the columns already exist in the database (added by the RunSQL migration
# 0069_phase_275_warehouse_flags via ALTER TABLE ADD COLUMN IF NOT EXISTS).

import django.core.validators
import django.db.models.deletion
import hub.apps.tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0077_add_ux_v2_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featureflagflipapproval',
            new_name='feature_fla_tenant__2ccaae_idx',
            old_name='ffa_tenant_flag_status_ix',
        ),
        migrations.RenameIndex(
            model_name='featureflagflipapproval',
            new_name='feature_fla_status_a97884_idx',
            old_name='ffa_status_requested_ix',
        ),
        migrations.RenameIndex(
            model_name='impersonationsession',
            new_name='impersonati_imperso_f40f29_idx',
            old_name='imp_sess_impr_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationsession',
            new_name='impersonati_imperso_a0020c_idx',
            old_name='imp_sess_target_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationsession',
            new_name='impersonati_imperso_c14d5e_idx',
            old_name='imp_sess_tt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='impersonationsession',
            new_name='impersonati_status_87bc79_idx',
            old_name='imp_sess_status_exp_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='tenant',
                    name='warehouse_athena_enabled',
                    field=models.BooleanField(default=False, help_text='Phase 275 — enable Athena warehouse connector.'),
                ),
                migrations.AddField(
                    model_name='tenant',
                    name='warehouse_bigquery_enabled',
                    field=models.BooleanField(default=False, help_text='Phase 275 — enable BigQuery warehouse connector.'),
                ),
                migrations.AddField(
                    model_name='tenant',
                    name='warehouse_connectivity_enabled',
                    field=models.BooleanField(default=False, help_text='Phase 275 — master gate for all warehouse connectivity features.'),
                ),
                migrations.AddField(
                    model_name='tenant',
                    name='warehouse_databricks_enabled',
                    field=models.BooleanField(default=False, help_text='Phase 275 — enable Databricks warehouse connector.'),
                ),
                migrations.AddField(
                    model_name='tenant',
                    name='warehouse_snowflake_enabled',
                    field=models.BooleanField(default=False, help_text='Phase 275 — enable Snowflake warehouse connector.'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='featureflagflipapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text="Second PLATFORM_ADMIN who approved the request. MUST be different from ``requested_by`` — the model's :meth:`mark_approved` enforces this; the API enforces it again at the permission layer.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_feature_flag_flips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='impersonationsession',
            name='end_reason',
            field=models.CharField(blank=True, default='', help_text='``manual_exit`` (user-driven) or ``expired`` (cron-driven).', max_length=32),
        ),
        migrations.AlterField(
            model_name='impersonationsession',
            name='impersonated_tenant',
            field=models.ForeignKey(help_text='The tenant the impersonated user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_sessions_inbound', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='impersonationsession',
            name='impersonator_tenant',
            field=models.ForeignKey(blank=True, help_text="The impersonator's home tenant (typically the PLATFORM_ADMIN's operator tenant). Stored explicitly so the row survives the impersonator user being deleted/migrated.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_sessions_outbound', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='access_request_compliance_gate_enabled',
            field=models.BooleanField(default=False, help_text='Phase 272.2 — when True, access request approval requires a successful ComplianceRun with allowed_to_store=True for the referenced resource.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='compliance_consent_enabled',
            field=models.BooleanField(default=False, help_text='When True, consent APIs, signup/marketplace/webhook gates, and banner flows apply for this tenant per Phase 232.1.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='compliance_legal_basis_strict',
            field=models.BooleanField(default=hub.apps.tenants.models._default_compliance_legal_basis_strict, help_text='Phase 270.C.4 — when True, compliance scans that are missing a valid GDPR/UK_GDPR/LGPD legal_basis are rejected with HTTP 422 LEGAL_BASIS_INVALID. When False (default in staging/dev), the scan succeeds with an ERROR-severity issue in the report. Env-aware default: True in production, False otherwise.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='compliance_processor_agreements_enabled',
            field=models.BooleanField(default=False, help_text='When True, processor registry, agreement records, asset–processor links, and expiry notification jobs are enabled per this tenant.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='compliance_retention_enforcer_enabled',
            field=models.BooleanField(default=False, help_text='When True, the Phase 232.7 retention auto-sweep (tombstone + 90-day grace + hard-delete) may process TIME_BASED policies for this tenant when the CronJob executes.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='connect_enabled',
            field=models.BooleanField(default=hub.apps.tenants.models._default_connect_enabled, help_text='Phase 271.1.2 — per-tenant Stripe Connect onboarding gate. False on existing tenants (30-day opt-out window); True on new tenants. Global override: settings.STRIPE_CONNECT_ENABLED.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='file_soft_delete_grace_days',
            field=models.PositiveIntegerField(default=30, help_text='Phase 260.1.A — days after ``File`` enters DELETING before purge_deleted_files may delete the object from storage and remove the DB row. Bounds [7, 365].', validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='impersonation_allowed',
            field=models.BooleanField(default=False, help_text='Phase 235.4 — when True, PLATFORM_ADMIN may impersonate users in this tenant via ``POST /api/v1/admin/impersonate/``. Default False so the deploy does not silently grant the capability; ops flips per tenant after the customer has explicitly authorised impersonation (BAA / DPA addendum).'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='marketplace_publish_compliance_gate_enabled',
            field=models.BooleanField(default=False, help_text='Phase 274.1 — when True, listing publication is blocked if the latest ComplianceRun risk_level exceeds compliance_risk_threshold or allowed_to_store is not True.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='semantic_capabilities_enabled',
            field=models.BooleanField(default=False, help_text='Phase 274.3 (BR3) — when True, URI dereference and semantic relationship endpoints are accessible. When False, both return 403 SEMANTIC_FEATURE_DISABLED.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='semantic_export_enabled',
            field=models.BooleanField(default=False, help_text='Phase 274.3 (BR3) — when True, RDF ingest/export endpoints are accessible. When False, return 403 SEMANTIC_FEATURE_DISABLED.'),
        ),
    ]
