# Generated by Django 6.0 on 2026-05-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0078_rename_ffa_tenant_flag_status_ix_feature_fla_tenant__2ccaae_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='data_quality_advanced_enabled',
            field=models.BooleanField(default=True, help_text='Phase 240.4.B.1 — gate for advanced DQ endpoints (anomalies / trends / scorecards / root-cause-analysis). Default True per Phase 283.1.3 (GA promotion). Conjunctive with data_quality_enabled — the base flag must ALSO be True.'),
        ),
    ]
