# Generated by Django 6.0.4 on 2026-05-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0079_ga_phase1_dq_advanced_default_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='data_quality_advanced_enabled',
            field=models.BooleanField(default=True, help_text='Phase 240.4.B.1 — gate for advanced DQ endpoints (anomalies / trends / scorecards / root-cause-analysis). Default False; flip to True per-tenant after the basic DQ feature is stable. Conjunctive with data_quality_enabled — the base flag must ALSO be True.'),
        ),
    ]
