# Generated by Django 6.0.4 on 2026-05-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0081_phase285_feature_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="baas_enabled",
            field=models.BooleanField(
                default=False,
                help_text="285.5.2.7 — CANARY. Gates Backend-as-a-Service. Promote to GA after production-ready.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="developer_enabled",
            field=models.BooleanField(
                default=False,
                help_text="285.5.2.4 — DRAFT. Gates developer portal + plugins. Revisit at 50+ PRO tenants.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="transformation_enabled",
            field=models.BooleanField(
                default=False,
                help_text="285.5.2.6 — DRAFT. Gates ETL/ELT pipelines. Core engine is placeholder.",
            ),
        ),
    ]
