# Generated by Django 6.0 on 2026-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0082_alter_tenant_baas_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="data_movement_enabled",
            field=models.BooleanField(
                default=True,
                help_text="285.6.4.5 — GA. When True, tenant uses dlt for bidirectional ingestion/export.",
            ),
        ),
    ]
