# Generated by Django 6.0.4 on 2026-05-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0083_add_data_movement_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="mfa_required",
            field=models.BooleanField(
                default=False,
                help_text="285.8.1.1 — When True, PLATFORM_ADMIN and TENANT_ADMIN users must authenticate via TOTP.",
            ),
        ),
    ]
