# Generated by Django 5.2.8 on 2026-05-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0086_add_tenant_dq_warehouse_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='pipeline_dependency_enabled',
            field=models.BooleanField(default=False, help_text='285.11 — DRAFT. Gates the pipeline dependency graph, auto-derivation from lineage, and dependency-aware execution ordering.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='warehouse_compliance_enabled',
            field=models.BooleanField(default=False, help_text='285.10 — GA. Gates warehouse-native compliance scans (SQL in customer warehouse).'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='warehouse_dq_enabled',
            field=models.BooleanField(default=False, help_text='285.10 — GA. Gates warehouse-native DQ checks (SQL in customer warehouse).'),
        ),
    ]
