# Generated by Django 6.0.4 on 2026-05-19 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0087_add_pipeline_dependency_flag"),
        ("tenants", "0087_add_pipeline_dependency_models"),
    ]

    operations = []
