# Generated by Django 5.2.8 on 2026-05-20 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0088_merge_20260519_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Machine-readable limit key (e.g. 'max_assets')", max_length=128, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='What this limit controls')),
                ('category', models.CharField(default='base', help_text='Grouping category for admin UI (base, compliance, ml, marketplace)', max_length=64)),
                ('unit', models.CharField(default='count', help_text='Unit of measurement (count, bytes, requests, seconds)', max_length=32)),
                ('sort_order', models.IntegerField(default=0, help_text='Display ordering')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'limit_dimensions',
                'ordering': ['category', 'sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='tenantplan',
            name='flsc_estimate_cents',
            field=models.IntegerField(blank=True, default=None, help_text='Internal: estimated fully-loaded service cost in cents (FLSC). Never exposed via API.', null=True),
        ),
        migrations.AddField(
            model_name='tenantplan',
            name='marketplace_take_rate_bps',
            field=models.IntegerField(default=1500, help_text='Marketplace transaction take rate in basis points (default 1500 = 15%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='tenantplan',
            name='markup_bps',
            field=models.IntegerField(blank=True, default=None, help_text='Internal: markup over FLSC in basis points. Never exposed via API.', null=True),
        ),
        migrations.AlterField(
            model_name='tenantplan',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('PRO', 'Pro'), ('SCALE', 'Scale'), ('ENTERPRISE', 'Enterprise'), ('CONFIGURABLE', 'Configurable')], help_text='Plan tier: FREE, PRO, or ENTERPRISE', max_length=20),
        ),
        migrations.CreateModel(
            name='TierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text="Short marketing headline (e.g. 'For growing teams')", max_length=200)),
                ('description_markdown', models.TextField(blank=True, default='', help_text='Long-form markdown description for the pricing page')),
                ('features_highlight', models.TextField(blank=True, default='', help_text='Bullet list of key features (markdown)')),
                ('feature_checkmarks', models.JSONField(blank=True, default=dict, help_text='Feature comparison matrix: {feature_key: bool} for pricing table checkmarks')),
                ('is_recommended', models.BooleanField(default=False, help_text='When True, this plan is the recommended/highlighted tier')),
                ('is_public', models.BooleanField(default=False, help_text='When True, shown on public pricing page and self-serve flow')),
                ('self_serve', models.BooleanField(default=False, help_text='When True, tenants can self-upgrade to this tier without sales')),
                ('sales_only', models.BooleanField(default=False, help_text='When True, this tier is only available through sales (enterprise)')),
                ('sort_order', models.IntegerField(default=0, help_text='Display ordering on pricing page')),
                ('plan', models.OneToOneField(help_text='Plan this profile belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tier_profile', to='tenants.tenantplan')),
            ],
            options={
                'db_table': 'tier_profiles',
                'ordering': ['sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sales_only', True), ('self_serve', True), _negated=True), name='tier_profile_self_serve_xor_sales_only')],
            },
        ),
    ]
