# Generated by Django 6.0.4 on 2026-05-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0091_notification_opt_outs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="planpricechangeapproval",
            new_name="plan_price__tenant__1b74a6_idx",
            old_name="ppca_plan_status_idx",
        ),
        migrations.RenameIndex(
            model_name="planpricechangeapproval",
            new_name="plan_price__status_a53f5a_idx",
            old_name="ppca_status_created_idx",
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="PLATFORM_ADMIN who approved (different from requested_by).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_price_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Business justification for the price change (min 10 chars).",
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="requested_by",
            field=models.ForeignKey(
                help_text="PLATFORM_ADMIN who opened the request.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_price_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                help_text="Approval lifecycle status.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="tenant_plan",
            field=models.ForeignKey(
                help_text="Plan whose price is being changed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_change_approvals",
                to="tenants.tenantplan",
            ),
        ),
    ]
