# Generated by Django 6.0.4 on 2026-05-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0092_plan_tier_sandbox"),
        ("tenants", "0092_rename_ppca_plan_status_idx_plan_price__tenant__1b74a6_idx_and_more"),
    ]

    operations = []
