# Generated by Django 6.0.4 on 2026-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0093_merge_20260521_0321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("FREE", "Free"),
                    ("STARTER", "Starter"),
                    ("GROWTH", "Growth"),
                    ("PRO", "Pro"),
                    ("SCALE", "Scale"),
                    ("ENTERPRISE", "Enterprise"),
                    ("CONFIGURABLE", "Configurable"),
                    ("SANDBOX", "Sandbox"),
                ],
                help_text="Plan tier: FREE, PRO, or ENTERPRISE",
                max_length=20,
            ),
        ),
    ]
