# Generated by Django 6.0 on 2026-05-24 00:25

import django.contrib.postgres.fields
import django.db.models.deletion
import hub.apps.tenants.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0096_merge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="LimitDimension",
        ),
        migrations.RenameIndex(
            model_name="planpricechangeapproval",
            new_name="ppca_plan_status_idx",
            old_name="plan_price__tenant__1b74a6_idx",
        ),
        migrations.RenameIndex(
            model_name="planpricechangeapproval",
            new_name="ppca_status_created_idx",
            old_name="plan_price__status_a53f5a_idx",
        ),
        migrations.AddField(
            model_name="impersonationsession",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AddField(
            model_name="planpricechangeapproval",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AddField(
            model_name="tenantplan",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AddField(
            model_name="tenantusagesummary",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_price_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_price_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="tenant_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_change_approvals",
                to="tenants.tenantplan",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="baas_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="data_mesh_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="data_movement_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="data_quality_advanced_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Phase 240.4.B.1 — gate for advanced DQ endpoints (anomalies / trends / scorecards / root-cause-analysis). Default False; flip to True per-tenant after the basic DQ feature is stable. Conjunctive with data_quality_enabled — the base flag must ALSO be True.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="developer_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="licensed_regulation_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                help_text="Regulation keys this tenant is licensed for (e.g. GDPR, UK_GDPR).",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="marketplace_integrations_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Phase 285 — when True, marketplace integration sync features are enabled for this tenant (AWS Data Exchange, GCP Marketplace). Default False.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="mfa_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="ml_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="pipeline_dependency_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_dq_warehouse_profile",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-tenant DQ warehouse profile configuration."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="transformation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="ux_v2_enabled",
            field=models.BooleanField(
                default=hub.apps.tenants.models._default_ux_v2_enabled,
                help_text="Phase 285.12.8 — when True, the tenant has access to UX v2 (redesigned UI). Default True for new tenants via ``_default_ux_v2_enabled``.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="virtualization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="warehouse_compliance_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="warehouse_dq_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tenantconfig",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-channel notification opt-out preferences"
            ),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="tier",
            field=models.CharField(
                choices=[("FREE", "Free"), ("PRO", "Pro"), ("ENTERPRISE", "Enterprise")],
                help_text="Plan tier: FREE, PRO, or ENTERPRISE",
                max_length=20,
            ),
        ),
    ]
