# Generated by Django 6.0.4 on 2026-06-05 16:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0103_add_notification_opt_outs_to_usage_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="LimitDimension",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Machine-readable limit key (e.g. 'max_assets')",
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(help_text="Human-readable name", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="What this limit controls"),
                ),
                (
                    "category",
                    models.CharField(
                        default="base",
                        help_text="Grouping category for admin UI (base, compliance, ml, marketplace)",
                        max_length=64,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="count",
                        help_text="Unit of measurement (count, bytes, requests, seconds)",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, help_text="Display ordering")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "limit_dimensions",
                "ordering": ["category", "sort_order", "key"],
            },
        ),
        migrations.RemoveField(
            model_name="impersonationsession",
            name="notification_opt_outs",
        ),
        migrations.RemoveField(
            model_name="tenantplan",
            name="notification_opt_outs",
        ),
        migrations.AlterField(
            model_name="planpricechangeapproval",
            name="notification_opt_outs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="baas_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable Backend-as-a-Service features."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="data_mesh_enabled",
            field=models.BooleanField(default=False, help_text="Enable data mesh features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="data_movement_enabled",
            field=models.BooleanField(default=False, help_text="Enable data movement features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="developer_enabled",
            field=models.BooleanField(default=False, help_text="Enable developer features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="licensed_regulation_keys",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                help_text="Phase 270.C.5 — uppercase regulation tokens this tenant is licensed to scan against (e.g. ``['GDPR', 'PIPL_CN']``). Empty list disables the check (backward-compat for pre-Phase-270.C.5 tenants). Out-of-set requests yield REGULATION_NOT_LICENSED warnings; strict_license_check elevates the warning to an HTTP 422 rejection.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="marketplace_integrations_enabled",
            field=models.BooleanField(default=False, help_text="Enable marketplace integrations."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="mfa_required",
            field=models.BooleanField(default=False, help_text="Require MFA for this tenant."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="ml_enabled",
            field=models.BooleanField(default=False, help_text="Enable ML features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-tenant notification opt-out configuration."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="pipeline_dependency_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable pipeline dependency features."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_dq_warehouse_profile",
            field=models.JSONField(
                blank=True, default=dict, help_text="DQ warehouse profile assigned to this tenant."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="transformation_enabled",
            field=models.BooleanField(default=False, help_text="Enable transformation features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="virtualization_enabled",
            field=models.BooleanField(default=False, help_text="Enable virtualization features."),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="warehouse_compliance_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable compliance warehouse integration."
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="warehouse_dq_enabled",
            field=models.BooleanField(default=False, help_text="Enable DQ warehouse integration."),
        ),
        migrations.AlterField(
            model_name="tenantconfig",
            name="notification_opt_outs",
            field=models.JSONField(
                blank=True, default=dict, help_text="Per-tenant notification opt-out configuration."
            ),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="flsc_estimate_cents",
            field=models.IntegerField(blank=True, help_text="Estimated FLSC in cents", null=True),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="marketplace_take_rate_bps",
            field=models.IntegerField(default=0, help_text="Marketplace take rate in basis points"),
        ),
        migrations.AlterField(
            model_name="tenantplan",
            name="markup_bps",
            field=models.IntegerField(blank=True, help_text="Markup in basis points", null=True),
        ),
        migrations.AlterField(
            model_name="tierprofile",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
