# Generated by Django 6.0 on 2026-01-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0003_add_observability_query_indexes'),
        ('observability', '0003_remove_transformation_pipeline_type'),
    ]

    operations = [
    ]
