# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0004_merge_20260116_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataincident',
            name='title',
            field=models.TextField(help_text='Incident title (supports long descriptions)'),
        ),
    ]
