/**
 * ProvenanceViewer — Phase 31 (29.6)
 *
 * Fetches DESCRIBE for a resource IRI and renders PROV-O as a timeline.
 * Collapsed by default; expandable.
 */

import { useState } from 'react';
import { useResolveURI } from '../hooks/useSemantic';

interface ProvenanceViewerProps {
  resourceType: string;
  resourceId: string;
}

export function ProvenanceViewer({ resourceType, resourceId }: ProvenanceViewerProps) {
  const [expanded, setExpanded] = useState(false);
  const { data, isLoading, error } = useResolveURI(resourceType, resourceId);

  return (
    <div className="provenance-viewer" style={{ margin: '1rem 0' }}>
      <button
        type="button"
        onClick={() => setExpanded(!expanded)}
        style={{
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          fontWeight: 600,
          fontSize: '0.875rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.25rem',
        }}
      >
        {expanded ? '\u25BC' : '\u25B6'} Provenance
      </button>
      {expanded && (
        <div style={{ padding: '0.5rem 0 0 1rem' }}>
          {isLoading && <p>Loading provenance...</p>}
          {error && <p style={{ color: 'var(--color-error, red)' }}>Failed to load provenance.</p>}
          {data && (
            <div style={{ fontSize: '0.8rem' }}>
              <p><strong>URI:</strong> {data['@id']}</p>
              <p><strong>Type:</strong> {data['@type']}</p>
              {!!data['prov:wasGeneratedBy'] && (
                <p><strong>Generated by:</strong> {String(data['prov:wasGeneratedBy'])}</p>
              )}
              {!!data['prov:wasDerivedFrom'] && (
                <p><strong>Derived from:</strong> {String(data['prov:wasDerivedFrom'])}</p>
              )}
              {!!data['dct:created'] && (
                <p><strong>Created:</strong> {String(data['dct:created'])}</p>
              )}
              <pre style={{ maxHeight: '200px', overflow: 'auto', background: 'var(--color-background-secondary, #f5f5f5)', padding: '0.5rem', borderRadius: '4px', fontSize: '0.75rem' }}>
                {JSON.stringify(data, null, 2)}
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
