"""
Phase 216.X.3 layer 3 — backend management command that sweeps test
artefacts that escaped the in-process cleanup_registry and the
per-session persona teardown.

Run by a CI CronJob nightly:

    python manage.py purge_test_data --older-than=24h

The command finds every Tenant whose name matches the
``fresh_id`` prefix patterns used by Phase 216 test fixtures
(``test-*``, ``asset-*``, ``contract-*``, ``tenant-*``, ``webhook-*``,
``user-*``) AND whose ``created_at`` is older than the cutoff, then
deletes them via the regular Django ORM (cascading to all related
rows). Defaults to a dry-run; pass ``--apply`` to actually delete.

The command is idempotent and safe to run multiple times.
"""

from __future__ import annotations

import re
from datetime import timedelta

from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

# Test resource name patterns generated by ``cli/tests/fixtures/test_data.py::fresh_id``
# and the SDK mirror. Anchored to the start of the string and require
# the worker-id segment to keep us from clobbering production names.
_TEST_NAME_RE = re.compile(
    r"^(test|asset|contract|tenant|webhook|user|persona|fixture)-"
    r"(master|gw\d+)-[0-9a-f]{8}$"
)


def _parse_duration(spec: str) -> timedelta:
    """Parse a short duration string like ``24h`` / ``7d`` / ``30m``."""
    match = re.fullmatch(r"(\d+)([smhd])", spec)
    if not match:
        raise CommandError(f"--older-than must be like '24h', '7d', '30m', '120s'; got {spec!r}")
    n = int(match.group(1))
    unit = match.group(2)
    if unit == "s":
        return timedelta(seconds=n)
    if unit == "m":
        return timedelta(minutes=n)
    if unit == "h":
        return timedelta(hours=n)
    if unit == "d":
        return timedelta(days=n)
    raise CommandError(f"unknown unit {unit!r}")  # pragma: no cover


class Command(BaseCommand):
    help = (
        "Phase 216 test data sweeper. Deletes Tenants whose name matches "
        "the Phase 216 fresh_id pattern AND that are older than the cutoff. "
        "Defaults to dry-run; pass --apply to delete."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--older-than",
            default="24h",
            help="Cutoff age (e.g. 24h, 7d, 30m, 120s). Default 24h.",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Actually delete. Without this flag the command is a dry-run.",
        )

    def handle(self, *args, **options):  # noqa: ARG002
        from hub.apps.tenants.models import Tenant  # local import: Django setup time

        cutoff = timezone.now() - _parse_duration(options["older_than"])
        candidates = []
        for tenant in Tenant.objects.filter(created_at__lt=cutoff).iterator():
            name = getattr(tenant, "name", "") or ""
            if _TEST_NAME_RE.match(name):
                candidates.append(tenant)
        if not candidates:
            self.stdout.write(self.style.SUCCESS("0 test tenants matched the cutoff"))
            return
        self.stdout.write(
            f"Found {len(candidates)} test tenant(s) older than {options['older_than']}:"
        )
        for tenant in candidates:
            self.stdout.write(f"  - {tenant.name}  (created {tenant.created_at!s})")
        if not options["apply"]:
            self.stdout.write(
                self.style.WARNING("Dry-run only. Re-run with --apply to actually delete.")
            )
            return
        deleted = 0
        for tenant in candidates:
            tenant.delete()
            deleted += 1
        self.stdout.write(self.style.SUCCESS(f"Deleted {deleted} test tenant(s)"))
