# Generated by Django 5.2.8 on 2026-05-05 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0043_phase232_dsar_and_tenant_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSARRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('ACCESS', 'Right of access'), ('ERASURE', 'Erasure / RTBF'), ('RECTIFICATION', 'Rectification'), ('PORTABILITY', 'Data portability'), ('RESTRICTION', 'Restriction of processing'), ('OBJECTION', 'Object to processing'), ('AUTOMATED_DECISION_REVIEW', 'Automated decision-making review')], max_length=40)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IDV_PENDING', 'Identity verification pending'), ('UNDER_REVIEW', 'Under review'), ('PACKAGE_IN_PROGRESS', 'Packaging response'), ('AWAITING_DOWNLOAD', 'Response ready for download'), ('CLOSED_FULFILLED', 'Closed — fulfilled'), ('CLOSED_REJECTED', 'Closed — rejected')], db_index=True, default='SUBMITTED', max_length=40)),
                ('regimes', models.JSONField(default=list, help_text='Applicable regime keys (uppercase strings), ordered by applicability.')),
                ('subject_email', models.EmailField(help_text='Requester email (may differ from authenticated user)', max_length=254)),
                ('subject_name', models.CharField(blank=True, default='', max_length=255)),
                ('subject_timezone', models.CharField(default='UTC', help_text='IANA TZ for countdown UI (regulator SLA remains UTC in stored deadlines).', max_length=64)),
                ('regulator_timezone', models.CharField(default='UTC', help_text='IANA TZ for supervisory calendar presentation (defaults to UTC).', max_length=64)),
                ('verification_method', models.CharField(choices=[('EMAIL_OTP', 'Email OTP'), ('MANUAL_REVIEW', 'Manual identity review'), ('INTERNAL_API_TOKEN', 'Internal API token (tenant systems)')], default='EMAIL_OTP', max_length=32)),
                ('email_otp_digest', models.CharField(blank=True, default='', max_length=64)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, default='', help_text='Client-supplied idempotency key (matched with "Idempotency-Key" header).', max_length=128)),
                ('public_reference_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('statutory_ack_deadline_utc', models.DateTimeField(blank=True, null=True)),
                ('statutory_fulfil_deadline_utc', models.DateTimeField(blank=True, null=True)),
                ('extension_path_selected', models.BooleanField(default=False, help_text='Whether the extended statutory window is used for fulfilment deadlines.')),
                ('legal_hold', models.BooleanField(default=False, help_text='When True, SLA timers are frozen per D232 / OpenSpec DSAR SLA scenario.')),
                ('legal_hold_reason', models.TextField(blank=True, default='')),
                ('sla_suspended_event_logged', models.BooleanField(default=False)),
                ('last_sla_level', models.CharField(choices=[('NONE', 'None'), ('WARN', 'Warning window'), ('ALERT', 'Alert window'), ('ESCALATED', 'Escalated / overdue')], default='NONE', max_length=20)),
                ('response_object_key', models.CharField(blank=True, default='', max_length=1024)),
                ('response_manifest_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('response_kms_key_id', models.CharField(blank=True, default='', max_length=512)),
                ('response_generated_at', models.DateTimeField(blank=True, null=True)),
                ('download_url_issued_at', models.DateTimeField(blank=True, null=True)),
                ('download_consumed_at', models.DateTimeField(blank=True, help_text='Set when a one-time presigned download is redeemed.', null=True)),
                ('handler_notes', models.TextField(blank=True, default='')),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsar_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsar_requests', to='tenants.tenant')),
            ],
            options={
                'db_table': 'dsar_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupAffectedBySubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_email_normalized', models.EmailField(max_length=254)),
                ('backup_identifier', models.CharField(help_text='Opaque backup job / snapshot label (S3 inventory id, etc.).', max_length=512)),
                ('exempt_from_cascade', models.BooleanField(default=True, help_text='True when regulatory posture keeps backups immutable for a window.')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_affected_subjects', to='tenants.tenant')),
                ('dsar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_affected_rows', to='dsar.dsarrequest')),
            ],
            options={
                'db_table': 'dsar_backup_affected_subjects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['tenant', 'status'], name='dsar_reques_tenant__91e09d_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['tenant', 'statutory_fulfil_deadline_utc'], name='dsar_reques_tenant__63a585_idx'),
        ),
        migrations.AddIndex(
            model_name='dsarrequest',
            index=models.Index(fields=['subject_email'], name='dsar_reques_subject_27afab_idx'),
        ),
        migrations.AddConstraint(
            model_name='dsarrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uq_dsar_tenant_idempotency'),
        ),
        migrations.AddIndex(
            model_name='backupaffectedbysubject',
            index=models.Index(fields=['tenant', 'subject_email_normalized'], name='dsar_backup_tenant__1db1f6_idx'),
        ),
    ]
