# Generated by Django 6.0 on 2025-12-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'default_permissions': (), 'ordering': ['-timestamp']},
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_tenant__86be43_idx',
            old_name='audit_events_tenant_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_actor_u_c55dbe_idx',
            old_name='audit_events_actor_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_resourc_917803_idx',
            old_name='audit_events_resource_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_action_db888c_idx',
            old_name='audit_events_action_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_event_timesta_0a9e3b_idx',
            old_name='audit_events_timestamp_idx',
        ),
    ]
