# Generated by Django 6.0 on 2026-04-17 21:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditevent_options_and_more"),
        ("tenants", "0023_add_archival_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When this event was archived (UTC)", null=True
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this event has been archived by the retention policy",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["is_archived", "timestamp"], name="audit_event_is_arch_1ae14b_idx"
            ),
        ),
    ]
