# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_audit_event_retention_policy'),
        ('audit', '0011_audit_event_tsvector_index_concurrent'),
        ('audit', '0012_enable_rls_audit_merkle_snapshots'),
    ]

    operations = [
    ]
