# Generated by Django 6.0.4 on 2026-05-14 03:05

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auditevent_trace_id'),
        ('tenants', '0078_rename_ffa_tenant_flag_status_ix_feature_fla_tenant__2ccaae_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditmerklesnapshot',
            new_name='audit_merkl_tenant__480222_idx',
            old_name='audit_merkle_tenant_pend_idx',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='chain_hash',
            field=models.CharField(blank=True, help_text='Phase 234.1 — SHA-256 hex of ``canonical_form(self) || prev_chain_hash || timestamp_iso``. NULL only on pre-backfill rows.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='chain_sequence',
            field=models.BigIntegerField(blank=True, help_text='Phase 234.1 — per-tenant monotonic sequence (1-indexed). NULL only on pre-backfill rows; ``save()`` will never write a row with NULL ``chain_sequence``.', null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='prev_chain_hash',
            field=models.CharField(blank=True, help_text="Phase 234.1 — SHA-256 hex of the immediately-preceding event in this tenant's chain. NULL on the genesis (first-per-tenant) row.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred (UTC). Phase 234.1: ``auto_now_add`` was replaced with ``default=timezone.now`` so the value is settable BEFORE ``save()`` runs (the chain hash MUST cover the exact timestamp that gets persisted). ``default=`` keeps ``bulk_create``/``Manager.create`` behaviour identical to the previous ``auto_now_add`` contract — every legitimate write still gets a non-null UTC timestamp without the caller having to remember to set it.'),
        ),
        migrations.AlterField(
            model_name='auditeventretentionpolicy',
            name='regulation_keys',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, help_text='Uppercase regime tokens (e.g. ``["GDPR", "UK_GDPR"]``). When non-empty, ``retention_days`` is derived from ``data_retention_period_days_for_regime_keys`` — the same registry Phase 232.7 ``RetentionPolicy`` consults — so audit retention stays aligned with data-resource retention.'),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='event_count',
            field=models.PositiveIntegerField(help_text='Number of AuditEvent rows folded into ``root_hex``.'),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='first_chain_sequence',
            field=models.BigIntegerField(blank=True, help_text='``chain_sequence`` of the earliest event in the window (NULL when empty).', null=True),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='last_chain_sequence',
            field=models.BigIntegerField(blank=True, help_text='``chain_sequence`` of the latest event in the window (NULL when empty).', null=True),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='signature_hex',
            field=models.CharField(help_text="HMAC-SHA256 of ``root_hex`` keyed on the tenant's current ``AUDIT_CHAIN_SIGNING_KEYS_JSON`` entry (index 0). 64 hex chars in practice; column sized at 128 to leave room for a future migration to a longer primitive.", max_length=128),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='signing_key_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Index of the key in the rolling 3-key ring that produced ``signature_hex``. ``verify_root_signature`` walks the whole ring on lookup so a post-rotation verifier still works.'),
        ),
        migrations.AlterField(
            model_name='auditmerklesnapshot',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant whose chain this snapshot covers. ``NULL`` for the platform-level (no-tenant) audit chain — same dual-track shape as ``AuditEvent.tenant``.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_merkle_snapshots', to='tenants.tenant'),
        ),
    ]
