# Generated by Django 6.0.2 on 2026-03-10 00:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0001_initial"),
        ("tenants", "0014_add_user_tenant_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportruncost",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexport",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexportrun",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="exportruncost",
            index=models.Index(fields=["run"], name="export_run__run_id_08e74f_idx"),
        ),
        migrations.AddIndex(
            model_name="exportruncost",
            index=models.Index(
                fields=["tenant", "calculated_at"], name="export_run__tenant__25405b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportruncost",
            index=models.Index(fields=["calculated_at"], name="export_run__calcula_d38fb4_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(fields=["tenant", "status"], name="scheduled_e_tenant__f6808c_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(fields=["tenant", "name"], name="scheduled_e_tenant__77aba5_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(
                fields=["tenant", "destination_type"], name="scheduled_e_tenant__2e6692_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(fields=["next_run_at"], name="scheduled_e_next_ru_059c67_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledexport",
            index=models.Index(
                fields=["status", "next_run_at"], name="scheduled_e_status_a4e602_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(
                fields=["scheduled_export", "status"], name="scheduled_e_schedul_cc51d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(
                fields=["scheduled_export", "created_at"], name="scheduled_e_schedul_bdbb1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(fields=["tenant", "status"], name="scheduled_e_tenant__b73cde_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(
                fields=["tenant", "created_at"], name="scheduled_e_tenant__cbd3fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(
                fields=["status", "created_at"], name="scheduled_e_status_ace833_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledexportrun",
            index=models.Index(
                fields=["prefect_flow_run_id"], name="scheduled_e_prefect_46810e_idx"
            ),
        ),
    ]
