# Generated by Django 6.0.3 on 2026-03-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0002_alter_exportruncost_id_alter_scheduledexport_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledexport",
            name="deployment_sync_status",
            field=models.CharField(
                choices=[("SYNCED", "Synced"), ("PENDING", "Pending"), ("FAILED", "Failed")],
                default="PENDING",
                help_text="Prefect deployment sync status: SYNCED, PENDING, FAILED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="scheduledexport",
            name="prefect_deployment_id",
            field=models.CharField(
                blank=True,
                help_text="Prefect deployment ID returned by integration service",
                max_length=255,
                null=True,
            ),
        ),
    ]
