# Generated by Django 6.0 on 2026-03-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0005_encrypt_destination_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledexport",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("ERROR", "Error"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                help_text="Status: ACTIVE, PAUSED, ERROR",
                max_length=20,
            ),
        ),
    ]
