# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_export', '0009_enable_rls_export_run_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexport',
            name='destination_type',
            field=models.CharField(choices=[('S3', 'Amazon S3'), ('GCS', 'Google Cloud Storage'), ('AZURE_BLOB', 'Azure Blob Storage'), ('SNOWFLAKE_TABLE', 'Snowflake Table'), ('BIGQUERY_TABLE', 'BigQuery Table'), ('DATABRICKS_TABLE', 'Databricks Table'), ('ATHENA_TABLE', 'Athena Table')], help_text='Destination type: S3, GCS, AZURE_BLOB', max_length=50),
        ),
    ]
