# Generated by Django 6.0.4 on 2026-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0011_credential_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledexport",
            name="credential_ref",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="AWS SM ARN, Prefect block name, or dlt secrets key for dlt credential resolution",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexport",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("S3", "Amazon S3"),
                    ("GCS", "Google Cloud Storage"),
                    ("AZURE_BLOB", "Azure Blob Storage"),
                    ("SNOWFLAKE_TABLE", "Snowflake Table"),
                    ("BIGQUERY_TABLE", "BigQuery Table"),
                    ("DATABRICKS_TABLE", "Databricks Table"),
                    ("ATHENA_TABLE", "Athena Table"),
                    ("HTTP", "HTTP"),
                    ("FTP", "FTP"),
                ],
                help_text="Destination type: S3, GCS, AZURE_BLOB",
                max_length=50,
            ),
        ),
    ]
