# Generated by Django 5.2.8 on 2026-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_export', '0012_alter_scheduledexport_credential_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexport',
            name='last_run_status',
            field=models.CharField(blank=True, choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING_DEPENDENCY', 'Pending Dependency'), ('SKIPPED_UPSTREAM_FAILED', 'Skipped (Upstream Failed)')], help_text='Status of last run: RUNNING, COMPLETED, FAILED, CANCELLED, PENDING_DEPENDENCY, SKIPPED_UPSTREAM_FAILED', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledexportrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING_DEPENDENCY', 'Pending Dependency'), ('SKIPPED_UPSTREAM_FAILED', 'Skipped (Upstream Failed)')], default='RUNNING', help_text='Run status: RUNNING, COMPLETED, FAILED, CANCELLED, PENDING_DEPENDENCY, SKIPPED_UPSTREAM_FAILED', max_length=24),
        ),
    ]
