# Generated by Django 6.0 on 2026-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0015_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledexport",
            name="credential_ref",
        ),
        migrations.RemoveField(
            model_name="scheduledexport",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="scheduledexport",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("S3", "Amazon S3"),
                    ("GCS", "Google Cloud Storage"),
                    ("AZURE_BLOB", "Azure Blob Storage"),
                    ("SNOWFLAKE_TABLE", "Snowflake Table"),
                    ("BIGQUERY_TABLE", "BigQuery Table"),
                    ("DATABRICKS_TABLE", "Databricks Table"),
                    ("ATHENA_TABLE", "Athena Table"),
                ],
                help_text="Destination type: S3, GCS, AZURE_BLOB",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexport",
            name="last_run_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                help_text="Status of last run: RUNNING, COMPLETED, FAILED, CANCELLED",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledexportrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="RUNNING",
                help_text="Run status: RUNNING, COMPLETED, FAILED, CANCELLED",
                max_length=20,
            ),
        ),
    ]
