# Generated by Django 6.0.4 on 2026-06-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_export", "0016_remove_scheduledexport_credential_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledexport",
            name="credential_ref",
            field=models.CharField(
                blank=True,
                help_text="AWS SM ARN (arn:aws:secretsmanager:...) or prefect://block-slug for dlt credential resolution",
                max_length=1024,
                null=True,
            ),
        ),
    ]
