# Generated by Django 6.0 on 2025-12-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_add_search_query_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='search_anal_tenant__f24a36_idx',
            old_name='search_anal_tenant__created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='search_anal_tenant__e34e38_idx',
            old_name='search_anal_tenant__query_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='search_anal_tenant__a8d24e_idx',
            old_name='search_anal_tenant__no_results_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='search_anal_tenant__8442d1_idx',
            old_name='search_anal_tenant__user_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalytics',
            new_name='search_anal_created_b2167e_idx',
            old_name='search_anal_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_tenant__474b07_idx',
            old_name='search_inde_tenant__resource_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_tenant__b4bae7_idx',
            old_name='search_inde_tenant__resource_type_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_tenant__58721c_idx',
            old_name='search_inde_tenant__classification_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_tenant__b1f2ab_idx',
            old_name='search_inde_tenant__owner_id_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_tenant__1cfea4_idx',
            old_name='search_inde_tenant__domain_idx',
        ),
        migrations.RenameIndex(
            model_name='searchindex',
            new_name='search_inde_search__511705_gin',
            old_name='search_inde_search_vector_gin_idx',
        ),
        migrations.AlterField(
            model_name='searchindex',
            name='resource_type',
            field=models.CharField(choices=[('CONTRACT', 'Contract'), ('ASSET', 'Asset'), ('DATASET', 'Dataset'), ('VIRTUAL_DATASET', 'Virtual Dataset')], help_text='Type of resource being indexed', max_length=50),
        ),
    ]
