/* tslint:disable */
/* eslint-disable */
/**
 * Interoperable Data Hub API
 *  # Meshant API  Complete REST API for managing data contracts, assets, datasets, compliance, data quality, and marketplace operations.  ## Features  - **Contract Management**: Create, update, and manage data contracts with ODCS support - **Multi-Level Lineage**: Track data dependencies at contract, model, and field levels - **Data Quality**: Define and enforce data quality rules - **Compliance**: Track privacy and compliance requirements - **Search**: Full-text search across contracts and assets - **Observability**: Monitor data freshness, volume, and pipeline health  ## Authentication  All API requests require authentication using Bearer tokens. See the Authentication section for details.  ## Rate Limiting  API requests are rate-limited per tenant. See response headers for rate limit information.  ## Versioning  The API uses URL-based versioning. Current version: v1  ## Support  For API support, contact: support@datahub.example.com 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@datahub.example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';

export const BASE_PATH = "/api/v1".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: RawAxiosRequestConfig;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath ?? basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    constructor(public field: string, msg?: string) {
        super(msg);
        this.name = "RequiredError"
    }
}

interface ServerMap {
    [key: string]: {
        url: string,
        description: string,
    }[];
}

/**
 *
 * @export
 */
export const operationServerMap: ServerMap = {
}
