# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancerun",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                    ("UNKNOWN", "Unknown"),
                ],
                help_text="Risk level: NONE, LOW, MEDIUM, HIGH, CRITICAL",
                max_length=20,
                null=True,
            ),
        ),
    ]
