# Generated by Django 6.0 on 2026-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0104_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliancerun",
            name="error_code",
        ),
        migrations.RemoveField(
            model_name="compliancerun",
            name="error_message",
        ),
        migrations.AlterField(
            model_name="compliancerun",
            name="scan_mode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Scan mode: FILE_SCAN or WAREHOUSE_SQL",
                max_length=32,
            ),
        ),
    ]
