# Generated by Django 6.0 on 2026-05-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0106_add_back_webhook_fired_at_warehouse_config"),
        ("jobs", "0025_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancerun",
            name="job",
            field=models.ForeignKey(
                help_text="Job that orchestrates this compliance run (nullable: assigned after run creation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_runs",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="compliancerun",
            name="webhook_fired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a compliance.completed webhook was successfully emitted for this terminal run",
                null=True,
            ),
        ),
    ]
