# Generated by Django 6.0 on 2026-05-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0107_make_job_nullable"),
        ("jobs", "0025_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancerun",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Job that orchestrates this compliance run (nullable: assigned after run creation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_runs",
                to="jobs.job",
            ),
        ),
    ]
