# Generated by Django 6.x migration stub — D232.17 recursive DPIA lineage

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dpia", "0002_enable_rls_dpia"),
    ]

    operations = [
        migrations.AddField(
            model_name="dpia",
            name="derived_from",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "D232.17 — parent assessment for recursive/platform DPIA chains "
                    "(tenant row may inherit scope from a platform or supplier template)."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nested_assessments",
                to="dpia.dpia",
            ),
        ),
        migrations.AddIndex(
            model_name="dpia",
            index=models.Index(fields=["tenant", "derived_from"], name="dpia_tenant_derived_idx"),
        ),
    ]
