# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpia', '0003_dpia_derived_from_recursive'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dpia',
            new_name='dpia_tenant__5fcbda_idx',
            old_name='dpia_tenant_i_9f80b2_idx',
        ),
        migrations.RenameIndex(
            model_name='dpia',
            new_name='dpia_tenant__ad9dbd_idx',
            old_name='dpia_tenant_i_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='dpia',
            new_name='dpia_tenant__088a0e_idx',
            old_name='dpia_tenant_i_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='dpia',
            new_name='dpia_tenant__a3afcd_idx',
            old_name='dpia_tenant_derived_idx',
        ),
    ]
