# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gdpr", "0002_dataexportjob_download_url_max_length"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dataexportjob",
            new_name="data_export_user_id_4da15a_idx",
            old_name="data_export_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="dataexportjob",
            new_name="data_export_tenant__d88cd2_idx",
            old_name="data_export_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="dataexportjob",
            new_name="data_export_status_2c075d_idx",
            old_name="data_export_status_created_idx",
        ),
        migrations.RenameIndex(
            model_name="erasurerequest",
            new_name="erasure_req_user_id_30cc15_idx",
            old_name="erasure_req_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="erasurerequest",
            new_name="erasure_req_tenant__968adc_idx",
            old_name="erasure_req_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="erasurerequest",
            new_name="erasure_req_status_545238_idx",
            old_name="erasure_req_status_requested_idx",
        ),
    ]
