# Generated by Django 4.2.16 on 2025-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="file",
            new_name="files_tenant__3f0e67_idx",
            old_name="files_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="file",
            new_name="files_tenant__cd8bdf_idx",
            old_name="files_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="file",
            new_name="files_content_6ca322_idx",
            old_name="files_content_sha256_idx",
        ),
        migrations.RenameIndex(
            model_name="file",
            new_name="files_status_179a06_idx",
            old_name="files_status_idx",
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                ],
                default="PENDING",
                help_text="File status: PENDING, UPLOADING, ACTIVE, FAILED, DELETED",
                max_length=20,
            ),
        ),
    ]
