# Generated by Django 6.0 on 2026-04-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_scan_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['tenant', 'scan_status'], name='files_tenant__0c3493_idx'),
        ),
    ]
