# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_drop_completed_file_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='file',
            new_name='files_tenant__d2fa97_idx',
            old_name='files_tenant_status_deleted_idx',
        ),
        migrations.AlterField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Phase 260.1.A — when the file entered DELETING (API delete) or legacy DELETED; drives purge_deleted_files eligibility.', null=True),
        ),
    ]
