# Generated by Django 6.0 on 2026-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0012_merge"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="file",
            name="unique_active_filename_per_tenant",
        ),
        migrations.RemoveIndex(
            model_name="file",
            name="files_tenant__d2fa97_idx",
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                    ("DELETING", "Deleting"),
                ],
                default="PENDING",
                help_text="File status: PENDING, UPLOADING, ACTIVE, FAILED, DELETED, DELETING",
                max_length=20,
            ),
        ),
    ]
