# Generated by Django 6.0 on 2026-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0014_add_back_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the file entered DELETING (API delete) or legacy DELETED",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("ACTIVE", "Active"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                    ("DELETING", "Deleting"),
                ],
                default="PENDING",
                help_text="File status: PENDING, UPLOADING, ACTIVE, FAILED, DELETED",
                max_length=20,
            ),
        ),
    ]
