# Generated by Django 6.0 on 2026-05-26 19:00

import hub.apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0015_alter_file_deleted_at_alter_file_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("PENDING_SCAN", "Pending scan"),
                    ("CLEAN", "Clean"),
                    ("INFECTED", "Infected"),
                    ("SCAN_UNAVAILABLE", "Scan unavailable"),
                    ("SCAN_ERROR", "Scan error"),
                ],
                db_index=True,
                default=hub.apps.files.models.FileScanStatus._default_scan_status,
                help_text="Malware scan status (ClamAV); independent of upload status",
                max_length=32,
            ),
        ),
    ]
