# Generated by Django 6.0.6 on 2026-06-18 03:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0016_alter_file_scan_status_default"),
        ("tenants", "0105_enable_developer_for_existing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="deleted_at",
            field=models.DateTimeField(blank=True, help_text="Soft-delete timestamp", null=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("UPLOADING", "Uploading"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("DELETED", "Deleted"),
                    ("DELETING", "Deleting"),
                ],
                default="PENDING",
                help_text="File status: PENDING, UPLOADING, ACTIVE, FAILED, DELETED",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("tenant", "name"),
                name="unique_active_filename_per_tenant",
            ),
        ),
    ]
