# Generated by Django 6.0 on 2025-12-08 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_tenant_key_idx_assets_tenant__76965e_idx_and_more'),
        ('contracts', '0001_initial'),
        ('tenants', '0003_rename_tenant_configs_tenant_idx_tenant_conf_tenant__37e737_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_tenant__910299_idx',
            old_name='contracts_tenant_asset_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_tenant__3657e3_idx',
            old_name='contracts_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contracts_tenant__53f1c8_idx',
            old_name='contracts_tenant_validation_idx',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('asset__isnull', False)), fields=('tenant', 'asset', 'version'), name='unique_contract_version_per_asset'),
        ),
    ]
