# Generated by Django 5.2.8 on 2025-12-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_set_default_hub_contract_version'),
        ('contracts', '0004_remove_datacontract_com_from_original_spec_type'),
    ]

    operations = [
    ]
