# Generated by Django 6.0 on 2025-12-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_merge_20251208_1803"),
        ("contracts", "0007_add_comprehensive_indexes_phase15"),
    ]

    operations = []
