# Generated by Django 6.0 on 2026-01-02 17:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_add_odps_query_indexes'),
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Type of security event (e.g., EXTERNAL_REF_FETCH, RATE_LIMIT_EXCEEDED, CACHE_HIT, CACHE_MISS, CACHE_EVICTION, SECURITY_VIOLATION)', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred (UTC)')),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Severity level (for security violations)', max_length=20, null=True)),
                ('ref_type', models.CharField(blank=True, help_text='Reference type (internal, local, external)', max_length=20, null=True)),
                ('ref_path', models.CharField(blank=True, help_text='The $ref path/URL', max_length=2048, null=True)),
                ('resolved_path', models.CharField(blank=True, help_text='Resolved path/URL', max_length=2048, null=True)),
                ('rate_limit_level', models.CharField(blank=True, help_text='Rate limit level (global, tenant, user)', max_length=20, null=True)),
                ('cache_operation', models.CharField(blank=True, help_text='Cache operation type (hit, miss, eviction)', max_length=20, null=True)),
                ('cache_key', models.CharField(blank=True, help_text='Cache key (for cache operations)', max_length=512, null=True)),
                ('eviction_reason', models.CharField(blank=True, help_text='Eviction reason (for cache evictions)', max_length=50, null=True)),
                ('violation_type', models.CharField(blank=True, help_text='Human-readable violation type', max_length=100, null=True)),
                ('attempted_path', models.CharField(blank=True, help_text='Attempted path (for path traversal)', max_length=2048, null=True)),
                ('attempted_url', models.CharField(blank=True, help_text='Attempted URL (for URL violations)', max_length=2048, null=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the event', null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', null=True)),
                ('request_id', models.CharField(blank=True, help_text='Request ID for tracing', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent string', max_length=500, null=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Contract associated with the event (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='contracts.contract')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this event belongs to (null for platform-level events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the event (null for system events)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_audit_logs',
                'ordering': ['-timestamp'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Incident title', max_length=255)),
                ('description', models.TextField(help_text='Incident description')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, help_text='Incident severity level', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', help_text='Incident status', max_length=20)),
                ('event_type', models.CharField(db_index=True, help_text='Type of security event that triggered the incident', max_length=50)),
                ('violation_count', models.IntegerField(default=1, help_text='Number of violations that contributed to this incident')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the incident was first detected')),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='When the incident was last updated')),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, help_text='When the incident was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the incident was resolved', null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', null=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Contract associated with the incident (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='contracts.contract')),
                ('related_audit_logs', models.ManyToManyField(blank=True, help_text='Security audit logs related to this incident', related_name='security_incidents', to='contracts.securityauditlog')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_incidents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this incident belongs to (null for platform-level incidents)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with the incident (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_incidents',
                'ordering': ['-first_detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['event_type', 'timestamp'], name='security_au_event_t_48883e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['tenant', 'timestamp'], name='security_au_tenant__78b36d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='security_au_user_id_75039c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['tenant', 'event_type', 'timestamp'], name='security_au_tenant__f36acc_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='security_au_tenant__8a74f1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['ref_type', 'timestamp'], name='security_au_ref_typ_f8e4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['cache_operation', 'timestamp'], name='security_au_cache_o_ac0b05_idx'),
        ),
        migrations.AddIndex(
            model_name='securityauditlog',
            index=models.Index(fields=['timestamp'], name='security_au_timesta_33b43f_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['severity', 'status', 'first_detected_at'], name='security_in_severit_925f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['tenant', 'status', 'first_detected_at'], name='security_in_tenant__f41a23_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['event_type', 'status', 'first_detected_at'], name='security_in_event_t_91ae1b_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'first_detected_at'], name='security_in_status_0c1017_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['first_detected_at'], name='security_in_first_d_9c112f_idx'),
        ),
    ]
