# Generated by Django 6.0.2 on 2026-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_create_security_audit_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="hub_contract_json",
            field=models.JSONField(blank=True, help_text="Normalized HubContract JSON", null=True),
        ),
    ]
