# Generated by Django 6.0 on 2026-03-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0020_contract_status_check_constraint"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contract",
            name="contracts_tenant_version_idx",
        ),
        migrations.RemoveIndex(
            model_name="contract",
            name="contracts_norm_status_created_idx",
        ),
    ]
