# Generated by Django 6.0 on 2026-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0021_remove_contract_contracts_tenant_version_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="validation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VALID", "Valid"),
                    ("INVALID", "Invalid"),
                    ("WARNING_ONLY", "Warning Only"),
                    ("ERROR", "Error"),
                    ("SKIPPED", "Skipped"),
                ],
                help_text="CLI validation status: VALID, INVALID, WARNING_ONLY, ERROR",
                max_length=20,
                null=True,
            ),
        ),
    ]
