# Generated by Django 6.0.3 on 2026-05-01 01:26

import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0024_unrevert_structureless_assets"),
        ("tenants", "0023_add_archival_fields"),
    ]

    # Phase 228 (228.0.8) — additive-only. CI gate via
    # ``django-strong-migrations`` rejects DROP COLUMN / column type
    # changes / non-concurrent index creation; this migration ships
    # only ``CreateModel`` + B-tree index creation + a partial unique
    # constraint, all of which are safe under load.
    operations = [
        migrations.CreateModel(
            name="LineageEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source model name (HubContract.models[*].name).",
                        max_length=255,
                    ),
                ),
                (
                    "source_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Source field name (HubContract.models[*].fields[*].name).",
                        max_length=255,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, default="", help_text="Target model name.", max_length=255
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        blank=True, default="", help_text="Target field name.", max_length=255
                    ),
                ),
                (
                    "edge_type",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("transformation", "Transformation"),
                            ("derivation", "Derivation"),
                            ("export", "Export"),
                            ("reference", "Reference"),
                        ],
                        default="reference",
                        help_text="Edge classification (upload / transformation / derivation / export / reference).",
                        max_length=32,
                    ),
                ),
                (
                    "transformation_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to the transformation that produced the edge (e.g. dbt model id, SQL expression).",
                        max_length=512,
                    ),
                ),
                (
                    "job_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reference to the job/pipeline that ran the transformation (e.g. Airflow run id).",
                        max_length=512,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        db_index=True,
                        help_text="When this edge became current (DB NOW()).",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this edge stopped being current; NULL means still current.",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Row insert timestamp (audit-only; NOT the validity start — see ``valid_from``).",
                    ),
                ),
                (
                    "created_by_run",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identifier for the run that created this edge — typically the lineage-sync handler's run-id, or the backfill command's checkpoint key.",
                        max_length=255,
                    ),
                ),
                (
                    "source_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Upstream contract; NULL for cross-tenant or external sources.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_lineage_edges",
                        to="contracts.contract",
                    ),
                ),
                (
                    "target_contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Downstream contract; NULL for cross-tenant or external targets.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_lineage_edges",
                        to="contracts.contract",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant owning the edge (cascade deletes the row).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineage_edges",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lineage Edge",
                "verbose_name_plural": "Lineage Edges",
                "db_table": "contracts_lineage_edge",
                "indexes": [
                    models.Index(
                        fields=["source_contract", "valid_from", "valid_to"],
                        name="lin_edge_src_validity_idx",
                    ),
                    models.Index(
                        fields=["target_contract", "valid_from", "valid_to"],
                        name="lin_edge_tgt_validity_idx",
                    ),
                    models.Index(fields=["tenant", "edge_type"], name="lin_edge_tenant_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_to__isnull", True)),
                        fields=(
                            "tenant",
                            "source_contract",
                            "target_contract",
                            "source_model",
                            "source_field",
                            "target_model",
                            "target_field",
                            "edge_type",
                        ),
                        name="lin_edge_open_unique",
                    )
                ],
            },
        ),
    ]
