# Generated by Django 6.0 on 2026-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0028_contract_semantic_federate_optout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="migrationcheckpoint",
            name="migration_name",
            field=models.CharField(
                db_index=True,
                help_text="Logical migration name (operator-supplied via the ``--checkpoint-table`` flag). Becomes the partition key for resumability — different migrations with the same contract_id do not collide.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="migrationcheckpoint",
            name="status",
            field=models.CharField(
                choices=[("done", "Done"), ("failed", "Failed"), ("in_progress", "In Progress")],
                db_index=True,
                default="done",
                help_text="Per-contract outcome. ``done`` = success (skip on resume); ``failed`` = error captured (skip on resume; ops can rerun by deleting the row); ``in_progress`` = reserved.",
                max_length=16,
            ),
        ),
    ]
