# Generated by Django 5.2.8 on 2026-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_enable_rls_contracts_lineage_edge_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineageedge',
            name='edge_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('transformation', 'Transformation'), ('derivation', 'Derivation'), ('export', 'Export'), ('reference', 'Reference'), ('ingestion', 'Ingestion'), ('pipeline_trigger', 'Pipeline Trigger')], default='reference', help_text='Edge classification (upload / transformation / derivation / export / reference).', max_length=32),
        ),
        migrations.AlterField(
            model_name='lineageedgearchive',
            name='edge_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('transformation', 'Transformation'), ('derivation', 'Derivation'), ('export', 'Export'), ('reference', 'Reference'), ('ingestion', 'Ingestion'), ('pipeline_trigger', 'Pipeline Trigger')], default='reference', max_length=32),
        ),
    ]
