# Generated by Django 6.0 on 2026-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0040_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="original_spec_type",
            field=models.CharField(
                choices=[
                    ("ODCS", "ODCS"),
                    ("ODPS", "ODPS"),
                    ("DATACONTRACT_COM", "DataContract.com"),
                ],
                help_text="Original spec type: ODCS (Open Data Contract Standard) or ODPS (Open Data Product Standard)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="lineageedge",
            name="edge_type",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("transformation", "Transformation"),
                    ("derivation", "Derivation"),
                    ("export", "Export"),
                    ("reference", "Reference"),
                    ("INGESTION", "Ingestion"),
                ],
                default="reference",
                help_text="Edge classification (upload / transformation / derivation / export / reference).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="lineageedgearchive",
            name="edge_type",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("transformation", "Transformation"),
                    ("derivation", "Derivation"),
                    ("export", "Export"),
                    ("reference", "Reference"),
                    ("INGESTION", "Ingestion"),
                ],
                default="reference",
                max_length=32,
            ),
        ),
    ]
