# Generated by Django 6.0 on 2026-05-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0041_alter_contract_original_spec_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="original_spec_type",
            field=models.CharField(
                choices=[("ODCS", "ODCS"), ("ODPS", "ODPS")],
                help_text="Original spec type: ODCS (Open Data Contract Standard) or ODPS (Open Data Product Standard)",
                max_length=50,
            ),
        ),
    ]
