# Generated by Django 6.0.2 on 2026-03-10 00:54

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0008_extend_external_resource_url"),
        ("contracts", "0013_remove_hub_contract_json_db_index"),
        ("scheduled_ingestion", "0004_file_pattern_blank_null"),
        ("tenants", "0014_add_user_tenant_membership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ingestiontemplate",
            name="ingestion_te_tenant__idx",
        ),
        migrations.RemoveIndex(
            model_name="ingestiontemplate",
            name="ingestion_te_is_syst_idx",
        ),
        migrations.RemoveConstraint(
            model_name="ingestiontemplate",
            name="unique_template_name_per_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="ingestiontemplate",
            name="unique_system_template_name",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueueitem",
            new_name="scheduled_i_schedul_6eb04a_idx",
            old_name="scheduled_i_schedul_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueueitem",
            new_name="scheduled_i_schedul_386670_idx",
            old_name="scheduled_i_schedul_idx2",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueueitem",
            new_name="scheduled_i_resolut_628131_idx",
            old_name="scheduled_i_resolut_idx",
        ),
        migrations.RenameIndex(
            model_name="ingestioncost",
            new_name="scheduled_i_schedul_00bcc3_idx",
            old_name="scheduled_i_schedul_idx3",
        ),
        migrations.RenameIndex(
            model_name="ingestioncost",
            new_name="scheduled_i_schedul_b7a993_idx",
            old_name="scheduled_i_schedul_idx4",
        ),
        migrations.RenameIndex(
            model_name="ingestioncost",
            new_name="scheduled_i_run_id_ba49f2_idx",
            old_name="scheduled_i_run_id_idx",
        ),
        migrations.AlterField(
            model_name="deadletterqueueitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ingestioncost",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="auto_create_asset",
            field=models.BooleanField(default=False, help_text="Create asset if it doesn't exist"),
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="source_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Source configuration (connection details, credentials, paths) stored securely",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestionrun",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestion",
            index=models.Index(fields=["tenant", "status"], name="scheduled_i_tenant__ffd3a2_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledingestion",
            index=models.Index(fields=["tenant", "name"], name="scheduled_i_tenant__4ef582_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledingestion",
            index=models.Index(
                fields=["tenant", "source_type"], name="scheduled_i_tenant__aa442a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestion",
            index=models.Index(fields=["next_run_at"], name="scheduled_i_next_ru_37e088_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduledingestion",
            index=models.Index(
                fields=["status", "next_run_at"], name="scheduled_i_status_df7ce4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestionrun",
            index=models.Index(
                fields=["scheduled_ingestion", "status"], name="scheduled_i_schedul_151ff7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestionrun",
            index=models.Index(
                fields=["scheduled_ingestion", "created_at"], name="scheduled_i_schedul_e7948f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestionrun",
            index=models.Index(
                fields=["status", "created_at"], name="scheduled_i_status_d63bd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestionrun",
            index=models.Index(
                fields=["prefect_flow_run_id"], name="scheduled_i_prefect_598093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduledingestionrun",
            index=models.Index(fields=["job_id"], name="scheduled_i_job_id_ebbbfe_idx"),
        ),
        migrations.DeleteModel(
            name="IngestionTemplate",
        ),
    ]
