# Generated by Django 6.0.3 on 2026-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0005_remove_ingestiontemplate_ingestion_te_tenant__idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledingestion",
            name="deployment_sync_status",
            field=models.CharField(
                choices=[("SYNCED", "Synced"), ("PENDING", "Pending"), ("FAILED", "Failed")],
                default="PENDING",
                help_text="Prefect deployment sync status: SYNCED, PENDING, FAILED",
                max_length=10,
            ),
        ),
    ]
