# Generated by Django 6.0.3 on 2026-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0007_add_failure_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledingestionrun",
            name="dlq_sync_status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("SYNCED", "Synced"), ("FAILED", "Failed")],
                default="PENDING",
                help_text="Phase 72: DLQ sync status after run completion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("ERROR", "Error"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                help_text="Status: ACTIVE, PAUSED, ERROR",
                max_length=20,
            ),
        ),
    ]
