# Generated by Django 6.0 on 2026-04-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0010_recreate_ingestion_templates"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="ingestiontemplate",
            new_name="ingestion_t_tenant__766711_idx",
            old_name="ingestion_te_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="ingestiontemplate",
            new_name="ingestion_t_is_syst_b2f67f_idx",
            old_name="ingestion_te_is_syst_idx",
        ),
        migrations.AlterField(
            model_name="ingestiontemplate",
            name="file_pattern_template",
            field=models.CharField(
                help_text="File pattern template (e.g., 'data_{date}.csv' where {date} is a placeholder)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="ingestiontemplate",
            name="ingestion_config_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Ingestion configuration template (DQ settings, auto-create asset, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ingestiontemplate",
            name="source_config_template",
            field=models.JSONField(
                help_text="Source configuration template with placeholders (e.g., {bucket_name}, {api_key})"
            ),
        ),
    ]
