# Generated by Django 6.0.4 on 2026-05-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0012_credential_ref"),
        ("scheduled_ingestion", "0012_enable_rls_scheduled_ingestions"),
    ]

    operations = []
