# Generated by Django 6.0.4 on 2026-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0013_merge_20260518_1634"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledingestion",
            name="credential_ref",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="AWS SM ARN, Prefect block name, or dlt secrets key for dlt credential resolution",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("S3", "Amazon S3"),
                    ("GCS", "Google Cloud Storage"),
                    ("AZURE_BLOB", "Azure Blob Storage"),
                    ("HTTP", "HTTP"),
                    ("HTTPS", "HTTPS"),
                    ("FTP", "FTP"),
                    ("SFTP", "SFTP"),
                    ("DATABASE", "Database"),
                    ("SNOWFLAKE_SOURCE", "Snowflake (source)"),
                    ("BIGQUERY_SOURCE", "BigQuery (source)"),
                    ("DATABRICKS_SOURCE", "Databricks (source)"),
                    ("ATHENA_SOURCE", "Athena (source)"),
                ],
                help_text="Source type: S3, GCS, AZURE_BLOB, HTTP, FTP, SFTP, DATABASE",
                max_length=50,
            ),
        ),
    ]
