# Generated by Django 5.2.8 on 2026-05-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_ingestion', '0015_add_dependency_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledingestion',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata. For dependency discovery, set source_asset_id and source_dataset_id keys.'),
        ),
    ]
