# Generated by Django 6.0 on 2026-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduled_ingestion", "0018_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledingestion",
            name="credential_ref",
        ),
        migrations.RemoveField(
            model_name="scheduledingestion",
            name="metadata",
        ),
        migrations.AlterField(
            model_name="scheduledingestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("S3", "Amazon S3"),
                    ("GCS", "Google Cloud Storage"),
                    ("AZURE_BLOB", "Azure Blob Storage"),
                    ("HTTP", "HTTP"),
                    ("HTTPS", "HTTPS"),
                    ("FTP", "FTP"),
                    ("SFTP", "SFTP"),
                    ("DATABASE", "Database"),
                ],
                help_text="Source type: S3, GCS, AZURE_BLOB, HTTP, FTP, SFTP, DATABASE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scheduledingestionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Run status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED",
                max_length=20,
            ),
        ),
    ]
