# Generated by Django 6.0.4 on 2026-05-14 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0078_rename_ffa_tenant_flag_status_ix_feature_fla_tenant__2ccaae_idx_and_more'),
        ('warehouses', '0003_enable_rls_warehouse_connection_acls'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='warehouseconnection',
            new_name='warehouse_c_tenant__33eaab_idx',
            old_name='wh_conn_type_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouseconnection',
            new_name='warehouse_c_tenant__c203cf_idx',
            old_name='wh_conn_active_idx',
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='config',
            field=models.JSONField(default=dict, help_text='Encrypted connection config (host, credentials, etc.)'),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivation without deletion'),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='name',
            field=models.CharField(help_text='Human-readable connection name', max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='private_endpoint_url',
            field=models.CharField(blank=True, default='', help_text='PrivateLink / PSC endpoint URL (empty = public hostname)', max_length=512),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='region',
            field=models.CharField(blank=True, default='', help_text='Warehouse region (validated against tenant compliance regime)', max_length=64),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_connections', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='warehouseconnection',
            name='warehouse_type',
            field=models.CharField(choices=[('SNOWFLAKE', 'Snowflake'), ('BIGQUERY', 'BigQuery'), ('DATABRICKS', 'Databricks'), ('ATHENA', 'Athena')], help_text='Target warehouse type', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseconnectionacl',
            name='connection',
            field=models.ForeignKey(help_text='Connection this ACL applies to', on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='warehouses.warehouseconnection'),
        ),
        migrations.AlterField(
            model_name='warehouseconnectionacl',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='warehouseconnectionacl',
            name='role',
            field=models.CharField(default='VIEWER', help_text='Access role: ADMIN, OPERATOR, VIEWER', max_length=50),
        ),
    ]
