# Generated by Django 6.0.4 on 2026-05-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouses", "0002_enable_rls_warehouses"),
        ("warehouses", "0004_rename_wh_conn_type_idx_warehouse_c_tenant__33eaab_idx_and_more"),
    ]

    operations = []
