# Generated by Django 6.0.1 on 2026-01-29 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Plugin name (unique)", max_length=255, unique=True),
                ),
                ("description", models.TextField(help_text="Plugin description")),
                (
                    "version",
                    models.CharField(
                        help_text="Plugin version (semantic versioning)", max_length=50
                    ),
                ),
                (
                    "author",
                    models.CharField(help_text="Plugin author/organization", max_length=255),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONNECTOR", "Connector"),
                            ("TRANSFORMER", "Transformer"),
                            ("VALIDATOR", "Validator"),
                            ("ANALYZER", "Analyzer"),
                            ("INTEGRATION", "Integration"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        help_text="Plugin category",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEPRECATED", "Deprecated"),
                            ("BETA", "Beta"),
                            ("ALPHA", "Alpha"),
                        ],
                        default="AVAILABLE",
                        help_text="Plugin status: AVAILABLE, DEPRECATED, BETA, ALPHA",
                        max_length=20,
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(
                        default=0, help_text="Number of times plugin has been downloaded"
                    ),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, help_text="Average rating (0-5)", null=True),
                ),
                (
                    "metadata_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional plugin metadata (tags, dependencies, etc.)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "plugins",
                "ordering": ["-download_count", "-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="plugins_status_c8c5f9_idx"),
                    models.Index(fields=["category"], name="plugins_categor_9333fb_idx"),
                    models.Index(fields=["name"], name="plugins_name_587dc4_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SDKDocumentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("typescript", "TypeScript"),
                            ("r", "R"),
                            ("go", "Go"),
                        ],
                        help_text="SDK language",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="SDK version (semantic versioning)", max_length=50),
                ),
                (
                    "documentation",
                    models.TextField(help_text="SDK documentation (markdown format)"),
                ),
                (
                    "installation",
                    models.CharField(
                        help_text="Installation instructions (e.g., 'pip install datahub-sdk')",
                        max_length=255,
                    ),
                ),
                ("quick_start", models.TextField(help_text="Quick start code snippet")),
                (
                    "examples_json",
                    models.JSONField(
                        blank=True, default=list, help_text="Code examples as JSON array", null=True
                    ),
                ),
                (
                    "api_reference_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="API reference documentation", null=True
                    ),
                ),
                (
                    "documentation_url",
                    models.URLField(blank=True, help_text="External documentation URL", null=True),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this SDK version is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sdk_documentation",
                "ordering": ["language", "-version"],
                "indexes": [
                    models.Index(
                        fields=["language", "is_active"], name="sdk_documen_languag_7fe040_idx"
                    ),
                    models.Index(fields=["version"], name="sdk_documen_version_ce3ef1_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language", "version"), name="unique_sdk_language_version"
                    )
                ],
            },
        ),
    ]
