# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_transformation_feature"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="eventoutbox",
            name="event_outbox_status_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventoutbox",
            name="event_outbox_tenant_status_idx",
        ),
        migrations.DeleteModel(
            name="EventOutbox",
        ),
        # IdempotencyKey and RequestDeduplication kept (bug_prevention)
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="dead_letter_event_t_e69a9b_idx",
            old_name="dead_letter_queue_event_type_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="dead_letter_subscri_40924d_idx",
            old_name="dead_letter_queue_subscriber_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="deadletterqueue",
            new_name="dead_letter_resolve_43b3ec_idx",
            old_name="dead_letter_queue_resolved_at_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_event_t_55886d_idx",
            old_name="events_event_type_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_tenant__a0995b_idx",
            old_name="events_tenant_id_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_source__5cc34e_idx",
            old_name="events_source_service_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_created_9e2206_idx",
            old_name="events_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="eventsubscription",
            new_name="event_subsc_subscri_73f605_idx",
            old_name="event_subscriptions_subscriber_name_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="eventsubscription",
            new_name="event_subsc_event_t_c7bdd5_idx",
            old_name="event_subscriptions_event_type_pattern_is_active_idx",
        ),
    ]
