# Generated by Django 6.0 on 2026-03-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_eventoutbox_event_outbox_status_created_idx_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="idempotency_tenant__875a5d_idx",
            old_name="idempotency_tenant_key_method_path_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencykey",
            new_name="idempotency_expires_6c9d28_idx",
            old_name="idempotency_expires_at_idx",
        ),
        migrations.RenameIndex(
            model_name="requestdeduplication",
            new_name="request_ded_tenant__72b04f_idx",
            old_name="request_dedup_tenant_fingerprint_idx",
        ),
        migrations.RenameIndex(
            model_name="requestdeduplication",
            new_name="request_ded_expires_bc5491_idx",
            old_name="request_dedup_expires_at_idx",
        ),
    ]
