# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fix_form_draft_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formdraft',
            new_name='form_drafts_user_id_7147b5_idx',
            old_name='form_drafts_user_resource_idx',
        ),
        migrations.RenameIndex(
            model_name='formdraft',
            new_name='form_drafts_tenant__0efcfa_idx',
            old_name='form_drafts_tenant_resource_idx',
        ),
    ]
