# Generated by Django 6.0 on 2026-05-24 00:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge"),
        ("tenants", "0097_fix_notification_opt_outs_on_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formdraft",
            name="unique_form_draft_per_user_tenant_resource_key",
        ),
        migrations.AddConstraint(
            model_name="formdraft",
            constraint=models.UniqueConstraint(
                fields=("user", "resource_type", "draft_key"),
                name="unique_form_draft_per_user_resource_key",
            ),
        ),
    ]
