# Generated by Django 6.0 on 2026-05-25 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_formdraft_unique_form_draft_per_user_tenant_resource_key_and_more"),
        ("tenants", "0098_add_boolean_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="formdraft",
            name="unique_form_draft_per_user_resource_key",
        ),
        migrations.AddConstraint(
            model_name="formdraft",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant", "resource_type", "draft_key"),
                name="unique_form_draft_per_user_tenant_resource_key",
            ),
        ),
    ]
