# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apiusagemetric",
            new_name="api_usage_m_tenant__be6b47_idx",
            old_name="api_usage_metrics_tenant_endpoint_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusagemetric",
            new_name="api_usage_m_tenant__b786fe_idx",
            old_name="api_usage_metrics_tenant_method_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusagemetric",
            new_name="api_usage_m_tenant__6764a6_idx",
            old_name="api_usage_metrics_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="apiusagemetric",
            new_name="api_usage_m_created_86c821_idx",
            old_name="api_usage_metrics_created_at_idx",
        ),
    ]
