# Generated by Django 6.0.3 on 2026-03-22 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0010_asset_status_check_constraint"),
        ("jobs", "0012_initial_115a"),
        ("orchestration", "0006_unique_constraint_and_check_constraints"),
        ("tenants", "0019_add_plan_category_and_ml_plan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransformationPipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the pipeline",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Pipeline name (e.g., 'Customer Data Enrichment', 'Sales Aggregation')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Pipeline description and purpose", null=True
                    ),
                ),
                (
                    "pipeline_definition",
                    models.JSONField(
                        help_text="Complete pipeline definition (JSON format) including nodes, connections, transformations"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Pipeline version (semantic versioning: major.minor.patch)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        help_text="Pipeline status: DRAFT, ACTIVE, INACTIVE, ARCHIVED",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the pipeline was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the pipeline was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (tags, categories, source/target assets, etc.)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_transformation_pipelines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this pipeline belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_pipelines",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "transformation_pipelines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransformationNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the node",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        help_text="Type of transformation node (filter, join, aggregate, transform, output)",
                        max_length=50,
                    ),
                ),
                (
                    "node_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Node configuration (JSON format) - filter expressions, join keys, aggregation functions, etc.",
                    ),
                ),
                (
                    "position",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Visual position coordinates (JSON format: {'x': number, 'y': number})",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Execution order within the pipeline (1-based, lower numbers execute first)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="When the node was created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="When the node was last updated"),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="Pipeline this node belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_nodes",
                        to="transformation.transformationpipeline",
                    ),
                ),
            ],
            options={
                "db_table": "transformation_nodes",
                "ordering": ["pipeline", "order"],
            },
        ),
        migrations.CreateModel(
            name="PreviewResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the preview result",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preview_id",
                    models.CharField(
                        db_index=True,
                        help_text="Preview ID (hash-based identifier)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        help_text="Complete preview result data (input_sample, output_sample, analysis, etc.)"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        db_index=True,
                        help_text="Cache key used to store the preview result",
                        max_length=255,
                    ),
                ),
                ("sample_size", models.IntegerField(help_text="Number of rows sampled")),
                (
                    "sampling_method",
                    models.CharField(
                        help_text="Sampling method used (first_n, random)", max_length=50
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the preview was generated"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When the preview expires (typically 1 hour after generation)"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Source asset that was previewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_results",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the preview",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_preview_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this preview belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_results",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="Pipeline that was previewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_results",
                        to="transformation.transformationpipeline",
                    ),
                ),
            ],
            options={
                "db_table": "preview_results",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the execution",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[
                            ("SYNC", "Synchronous"),
                            ("ASYNC", "Asynchronous"),
                            ("SCHEDULED", "Scheduled"),
                            ("MANUAL", "Manual"),
                            ("AUTOMATED", "Automated"),
                        ],
                        default="MANUAL",
                        help_text="Execution mode: SYNC, ASYNC, SCHEDULED, MANUAL, AUTOMATED",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED",
                        max_length=20,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the execution started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the execution completed", null=True
                    ),
                ),
                (
                    "execution_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Execution log entries (JSON array of log messages, errors, warnings)",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Execution metrics (duration, throughput, items processed, etc.)",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Idempotency key for retry safety (uses execution_id by default)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the execution record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the execution record was last updated"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Source asset that was transformed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transformation_executions",
                        to="assets.asset",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job record for async execution (null for sync executions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_executions",
                        to="jobs.job",
                    ),
                ),
                (
                    "result_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Result asset created by the transformation (null if execution failed or not yet completed)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transformation_result_executions",
                        to="assets.asset",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Workflow instance that orchestrates this execution (null if not using workflow)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_executions",
                        to="orchestration.workflowinstance",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        help_text="Transformation pipeline that was executed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="transformation.transformationpipeline",
                    ),
                ),
            ],
            options={
                "db_table": "transformation_pipeline_executions",
                "ordering": ["-started_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WranglingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the wrangling session",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Session name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Session description", null=True),
                ),
                (
                    "current_state",
                    models.JSONField(
                        blank=True,
                        help_text="Current state snapshot after all operations",
                        null=True,
                    ),
                ),
                (
                    "operation_history",
                    models.JSONField(
                        default=list, help_text="List of operations performed in this session"
                    ),
                ),
                (
                    "history_position",
                    models.IntegerField(
                        default=-1, help_text="Current position in operation history (-1 = at end)"
                    ),
                ),
                (
                    "wrangling_script",
                    models.TextField(
                        blank=True,
                        help_text="Generated script representation of operations",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional metadata", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the session was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the session was last updated"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Source asset being wrangled",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrangling_sessions",
                        to="assets.asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_wrangling_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this session belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrangling_sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "wrangling_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WranglingOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the operation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("FILTER", "Filter"),
                            ("SORT", "Sort"),
                            ("TRANSFORM", "Transform"),
                            ("AGGREGATE", "Aggregate"),
                            ("JOIN", "Join"),
                            ("GROUP", "Group"),
                            ("PIVOT", "Pivot"),
                            ("UNPIVOT", "Unpivot"),
                            ("RENAME_COLUMN", "Rename Column"),
                            ("DROP_COLUMN", "Drop Column"),
                            ("ADD_COLUMN", "Add Column"),
                            ("SPLIT_COLUMN", "Split Column"),
                            ("MERGE_COLUMNS", "Merge Columns"),
                            ("DEDUPLICATE", "Deduplicate"),
                            ("FILL_NULLS", "Fill Nulls"),
                            ("REMOVE_NULLS", "Remove Nulls"),
                            ("TYPE_CONVERSION", "Type Conversion"),
                        ],
                        help_text="Type of operation",
                        max_length=50,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(help_text="Operation parameters (operation-specific)"),
                ),
                (
                    "result_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="Result snapshot after operation (optional)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional operation metadata",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the operation was created"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Wrangling session this operation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="transformation.wranglingsession",
                    ),
                ),
            ],
            options={
                "db_table": "wrangling_operations",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(fields=["tenant"], name="transformat_tenant__e114c3_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(fields=["created_by"], name="transformat_created_98ae25_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(fields=["status"], name="transformat_status_ebd480_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(fields=["created_at"], name="transformat_created_af306c_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(fields=["tenant", "status"], name="transformat_tenant__df79a7_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationpipeline",
            index=models.Index(
                fields=["tenant", "created_at"], name="transformat_tenant__d6b259_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transformationpipeline",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name", "version"), name="unique_pipeline_name_version_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="transformationnode",
            index=models.Index(fields=["pipeline"], name="transformat_pipelin_d5d944_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationnode",
            index=models.Index(fields=["node_type"], name="transformat_node_ty_a4aed0_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationnode",
            index=models.Index(fields=["order"], name="transformat_order_05d13e_idx"),
        ),
        migrations.AddIndex(
            model_name="transformationnode",
            index=models.Index(fields=["pipeline", "order"], name="transformat_pipelin_a2c545_idx"),
        ),
        migrations.AddIndex(
            model_name="previewresult",
            index=models.Index(fields=["preview_id"], name="preview_res_preview_ef5718_idx"),
        ),
        migrations.AddIndex(
            model_name="previewresult",
            index=models.Index(
                fields=["tenant", "generated_at"], name="preview_res_tenant__46de84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="previewresult",
            index=models.Index(
                fields=["pipeline", "generated_at"], name="preview_res_pipelin_db2685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="previewresult",
            index=models.Index(
                fields=["asset", "generated_at"], name="preview_res_asset_i_bd8b74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="previewresult",
            index=models.Index(fields=["expires_at"], name="preview_res_expires_c87ddf_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["pipeline"], name="transformat_pipelin_d04742_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["asset"], name="transformat_asset_i_55c20e_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["status"], name="transformat_status_1e4d7f_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["started_at"], name="transformat_started_c0dfa9_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(
                fields=["pipeline", "status"], name="transformat_pipelin_1fbcf0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(
                fields=["pipeline", "started_at"], name="transformat_pipelin_70dc1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["asset", "status"], name="transformat_asset_i_b83da0_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["idempotency_key"], name="transformat_idempot_83819f_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["workflow_instance"], name="transformat_workflo_5f346a_idx"),
        ),
        migrations.AddConstraint(
            model_name="pipelineexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("idempotency_key",),
                name="unique_idempotency_key_when_set",
            ),
        ),
        migrations.AddIndex(
            model_name="wranglingsession",
            index=models.Index(fields=["tenant", "asset"], name="wrangling_s_tenant__293d16_idx"),
        ),
        migrations.AddIndex(
            model_name="wranglingsession",
            index=models.Index(
                fields=["created_by", "created_at"], name="wrangling_s_created_0b86b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wranglingoperation",
            index=models.Index(
                fields=["session", "created_at"], name="wrangling_o_session_fdf5cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wranglingoperation",
            index=models.Index(fields=["operation_type"], name="wrangling_o_operati_b07a87_idx"),
        ),
    ]
