# Generated by Django 6.0 on 2025-12-24 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the pipeline', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Pipeline name (e.g., 'Customer Data Enrichment', 'Sales Aggregation')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Pipeline description and purpose', null=True)),
                ('pipeline_definition', models.JSONField(help_text='Complete pipeline definition (JSON format) including nodes, connections, transformations')),
                ('version', models.CharField(default='1.0.0', help_text='Pipeline version (semantic versioning: major.minor.patch)', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Pipeline status: DRAFT, ACTIVE, INACTIVE, ARCHIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the pipeline was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the pipeline was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (tags, categories, source/target assets, etc.)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the pipeline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transformation_pipelines', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this pipeline belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transformation_pipelines', to='tenants.tenant')),
            ],
            options={
                'db_table': 'transformation_pipelines',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='transformat_tenant__e114c3_idx'), models.Index(fields=['created_by'], name='transformat_created_98ae25_idx'), models.Index(fields=['status'], name='transformat_status_ebd480_idx'), models.Index(fields=['created_at'], name='transformat_created_af306c_idx'), models.Index(fields=['tenant', 'status'], name='transformat_tenant__df79a7_idx'), models.Index(fields=['tenant', 'created_at'], name='transformat_tenant__d6b259_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name', 'version'), name='unique_pipeline_name_version_per_tenant')],
            },
        ),
    ]
