# Generated by Django 6.0 on 2025-12-25 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assets_tenant_health_idx_and_more'),
        ('transformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the execution', primary_key=True, serialize=False)),
                ('execution_mode', models.CharField(choices=[('SYNC', 'Synchronous'), ('ASYNC', 'Asynchronous'), ('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual'), ('AUTOMATED', 'Automated')], default='MANUAL', help_text='Execution mode: SYNC, ASYNC, SCHEDULED, MANUAL, AUTOMATED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the execution completed', null=True)),
                ('execution_log', models.JSONField(blank=True, default=list, help_text='Execution log entries (JSON array of log messages, errors, warnings)')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Execution metrics (duration, throughput, items processed, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the execution record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the execution record was last updated')),
                ('asset', models.ForeignKey(help_text='Source asset that was transformed', on_delete=django.db.models.deletion.CASCADE, related_name='transformation_executions', to='assets.asset')),
                ('pipeline', models.ForeignKey(help_text='Transformation pipeline that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='transformation.transformationpipeline')),
                ('result_asset', models.ForeignKey(blank=True, help_text='Result asset created by the transformation (null if execution failed or not yet completed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformation_result_executions', to='assets.asset')),
            ],
            options={
                'db_table': 'transformation_pipeline_executions',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['pipeline'], name='transformat_pipelin_d04742_idx'), models.Index(fields=['asset'], name='transformat_asset_i_55c20e_idx'), models.Index(fields=['status'], name='transformat_status_1e4d7f_idx'), models.Index(fields=['started_at'], name='transformat_started_c0dfa9_idx'), models.Index(fields=['pipeline', 'status'], name='transformat_pipelin_1fbcf0_idx'), models.Index(fields=['pipeline', 'started_at'], name='transformat_pipelin_70dc1f_idx'), models.Index(fields=['asset', 'status'], name='transformat_asset_i_b83da0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransformationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the node', primary_key=True, serialize=False)),
                ('node_type', models.CharField(help_text='Type of transformation node (filter, join, aggregate, transform, output)', max_length=50)),
                ('node_config', models.JSONField(blank=True, default=dict, help_text='Node configuration (JSON format) - filter expressions, join keys, aggregation functions, etc.')),
                ('position', models.JSONField(blank=True, default=dict, help_text="Visual position coordinates (JSON format: {'x': number, 'y': number})")),
                ('order', models.IntegerField(help_text='Execution order within the pipeline (1-based, lower numbers execute first)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the node was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the node was last updated')),
                ('pipeline', models.ForeignKey(help_text='Pipeline this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transformation_nodes', to='transformation.transformationpipeline')),
            ],
            options={
                'db_table': 'transformation_nodes',
                'ordering': ['pipeline', 'order'],
                'indexes': [models.Index(fields=['pipeline'], name='transformat_pipelin_d5d944_idx'), models.Index(fields=['node_type'], name='transformat_node_ty_a4aed0_idx'), models.Index(fields=['order'], name='transformat_order_05d13e_idx'), models.Index(fields=['pipeline', 'order'], name='transformat_pipelin_a2c545_idx')],
            },
        ),
    ]
