# Generated by Django 6.0 on 2025-12-25 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assets_tenant_health_idx_and_more'),
        ('tenants', '0006_add_odps_refs_config'),
        ('transformation', '0004_add_idempotency_key_to_pipeline_execution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WranglingOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the operation', primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('FILTER', 'Filter'), ('SORT', 'Sort'), ('TRANSFORM', 'Transform'), ('AGGREGATE', 'Aggregate'), ('JOIN', 'Join'), ('GROUP', 'Group'), ('PIVOT', 'Pivot'), ('UNPIVOT', 'Unpivot'), ('RENAME_COLUMN', 'Rename Column'), ('DROP_COLUMN', 'Drop Column'), ('ADD_COLUMN', 'Add Column'), ('SPLIT_COLUMN', 'Split Column'), ('MERGE_COLUMNS', 'Merge Columns'), ('DEDUPLICATE', 'Deduplicate'), ('FILL_NULLS', 'Fill Nulls'), ('REMOVE_NULLS', 'Remove Nulls'), ('TYPE_CONVERSION', 'Type Conversion')], help_text='Type of operation', max_length=50)),
                ('parameters', models.JSONField(help_text='Operation parameters (operation-specific)')),
                ('result_snapshot', models.JSONField(blank=True, help_text='Result snapshot after operation (optional)', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional operation metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the operation was created')),
            ],
            options={
                'db_table': 'wrangling_operations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WranglingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the wrangling session', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Session name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description', null=True)),
                ('current_state', models.JSONField(blank=True, help_text='Current state snapshot after all operations', null=True)),
                ('operation_history', models.JSONField(default=list, help_text='List of operations performed in this session')),
                ('history_position', models.IntegerField(default=-1, help_text='Current position in operation history (-1 = at end)')),
                ('wrangling_script', models.TextField(blank=True, help_text='Generated script representation of operations', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the session was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the session was last updated')),
            ],
            options={
                'db_table': 'wrangling_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='pipelineexecution',
            new_name='transformat_idempot_83819f_idx',
            old_name='transformat_idempo_idx',
        ),
        migrations.AddField(
            model_name='wranglingsession',
            name='asset',
            field=models.ForeignKey(help_text='Source asset being wrangled', on_delete=django.db.models.deletion.CASCADE, related_name='wrangling_sessions', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='wranglingsession',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wrangling_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wranglingsession',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='wrangling_sessions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='wranglingoperation',
            name='session',
            field=models.ForeignKey(help_text='Wrangling session this operation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='transformation.wranglingsession'),
        ),
        migrations.AddIndex(
            model_name='wranglingsession',
            index=models.Index(fields=['tenant', 'asset'], name='wrangling_s_tenant__293d16_idx'),
        ),
        migrations.AddIndex(
            model_name='wranglingsession',
            index=models.Index(fields=['created_by', 'created_at'], name='wrangling_s_created_0b86b2_idx'),
        ),
        migrations.AddIndex(
            model_name='wranglingoperation',
            index=models.Index(fields=['session', 'created_at'], name='wrangling_o_session_fdf5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='wranglingoperation',
            index=models.Index(fields=['operation_type'], name='wrangling_o_operati_b07a87_idx'),
        ),
    ]
