# Generated by Django 6.0 on 2025-12-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assets_tenant_health_idx_and_more'),
        ('jobs', '0003_add_workflow_instance_to_pipeline_execution'),
        ('orchestration', '0002_add_workflow_instance_to_pipeline_execution'),
        ('transformation', '0006_add_preview_result_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineexecution',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, help_text='Workflow instance that orchestrates this execution (null if not using workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_executions', to='orchestration.workflowinstance'),
        ),
        migrations.AddIndex(
            model_name='pipelineexecution',
            index=models.Index(fields=['workflow_instance'], name='transformat_workflo_5f346a_idx'),
        ),
    ]
