# Generated by Django 5.2.8 on 2026-05-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0008_add_prefect_flow_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PENDING_DEPENDENCY', 'Pending Dependency'), ('SKIPPED_UPSTREAM_FAILED', 'Skipped (Upstream Failed)')], default='PENDING', help_text='Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED, PENDING_DEPENDENCY, SKIPPED_UPSTREAM_FAILED', max_length=24),
        ),
    ]
