# Generated by Django 5.2.8 on 2026-05-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformation', '0009_add_dependency_statuses'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='transformationnode',
            table_comment='DEPRECATED: dbt-native engine replaces visual nodes. Sunset: 2027-03-01.',
        ),
        migrations.AlterModelTableComment(
            name='wranglingoperation',
            table_comment='DEPRECATED: dbt-native engine replaces wrangling. Sunset: 2027-03-01.',
        ),
        migrations.AlterModelTableComment(
            name='wranglingsession',
            table_comment='DEPRECATED: dbt-native engine replaces wrangling. Sunset: 2027-03-01.',
        ),
    ]
