# Generated by Django 6.0 on 2026-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0012_merge"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="transformationnode",
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name="wranglingoperation",
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name="wranglingsession",
            table_comment=None,
        ),
        migrations.RemoveField(
            model_name="pipelineexecution",
            name="prefect_flow_run_id",
        ),
        migrations.RemoveField(
            model_name="transformationpipeline",
            name="git_credential_ref",
        ),
        migrations.RemoveField(
            model_name="transformationpipeline",
            name="source_config",
        ),
        migrations.RemoveField(
            model_name="transformationpipeline",
            name="warehouse_credential_ref",
        ),
        migrations.AlterField(
            model_name="pipelineexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED",
                max_length=20,
            ),
        ),
    ]
