# Generated by Django 6.0.4 on 2026-06-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0013_alter_transformationnode_table_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transformationpipeline",
            name="git_credential_ref",
            field=models.CharField(
                blank=True,
                help_text="AWS Secrets Manager ARN for git credentials (dbt project clone).",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transformationpipeline",
            name="git_repository_url",
            field=models.CharField(
                blank=True,
                help_text="Git repository URL for the dbt project (e.g., https://github.com/org/repo.git).",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transformationpipeline",
            name="warehouse_credential_ref",
            field=models.CharField(
                blank=True,
                help_text="AWS Secrets Manager ARN for warehouse credentials (required for dbt-native pipelines).",
                max_length=2048,
                null=True,
            ),
        ),
    ]
