# Generated by Django 6.0.6 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transformation", "0015_ensure_prefect_flow_run_id_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING_DEPENDENCY", "Pending Dependency"),
                    ("SKIPPED_UPSTREAM_FAILED", "Skipped (Upstream Failed)"),
                ],
                default="PENDING",
                help_text="Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED, PENDING_DEPENDENCY, SKIPPED_UPSTREAM_FAILED, COMPENSATED",
                max_length=50,
            ),
        ),
    ]
