# Generated by Django 4.2.16 on 2025-11-25 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0002_rename_files_tenant_status_idx_files_tenant__3f0e67_idx_and_more"),
        ("datasets", "0002_rename_datasets_tenant_asset_idx_datasets_tenant__5d12ce_idx_and_more"),
        ("tenants", "0001_initial"),
        ("jobs", "0002_rename_jobs_tenant_status_idx_jobs_tenant__a46df1_idx_and_more"),
        ("assets", "0002_rename_assets_tenant_key_idx_assets_tenant__76965e_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DQRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "profile_key",
                    models.CharField(
                        help_text="DQ profile key (e.g., intake_basic_gx, intake_basic_soda)",
                        max_length=100,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("GREAT_EXPECTATIONS", "Great Expectations"), ("SODA", "Soda")],
                        help_text="DQ engine used: GREAT_EXPECTATIONS or SODA",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="DQ run status: PENDING, RUNNING, SUCCEEDED, FAILED",
                        max_length=20,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        blank=True,
                        help_text="Overall DQ status: PASS, FAIL, WARN, UNKNOWN (from result)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(blank=True, help_text="Quality score (0-100)", null=True),
                ),
                (
                    "checks_json",
                    models.JSONField(
                        blank=True, help_text="List of DQ checks with results", null=True
                    ),
                ),
                (
                    "details_json",
                    models.JSONField(
                        blank=True, help_text="Detailed DQ results and metadata", null=True
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, help_text="When DQ run started", null=True),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When DQ run completed", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Asset this DQ run is for (nullable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_runs",
                        to="assets.asset",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dataset this DQ run is for (nullable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_runs",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        help_text="File this DQ run is for (scan-only, nullable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_runs",
                        to="files.file",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job that orchestrates this DQ run",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_runs",
                        to="jobs.job",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this DQ run belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dq_runs",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "dq_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant", "asset"], name="dq_runs_tenant__d958e8_idx"),
                    models.Index(fields=["tenant", "dataset"], name="dq_runs_tenant__276abf_idx"),
                    models.Index(fields=["tenant", "status"], name="dq_runs_tenant__729dc1_idx"),
                    models.Index(fields=["tenant", "file"], name="dq_runs_tenant__3ced8a_idx"),
                    models.Index(fields=["job"], name="dq_runs_job_id_5a146c_idx"),
                ],
            },
        ),
    ]
