# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0003_add_alerting_rules_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="dqalertingrule",
            new_name="dq_alerting_tenant__a200c2_idx",
            old_name="dq_alertin_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="dqalertingrule",
            new_name="dq_alerting_tenant__b69788_idx",
            old_name="dq_alertin_tenant__idx2",
        ),
        migrations.RenameIndex(
            model_name="dqalertingrule",
            new_name="dq_alerting_tenant__b9e8ea_idx",
            old_name="dq_alertin_tenant__idx3",
        ),
        migrations.RenameIndex(
            model_name="dqalertingrule",
            new_name="dq_alerting_tenant__416206_idx",
            old_name="dq_alertin_tenant__idx4",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_tenant__717358_idx",
            old_name="dq_anomalie_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_tenant__7871a2_idx",
            old_name="dq_anomalie_tenant__idx2",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_tenant__a16f86_idx",
            old_name="dq_anomalie_tenant__idx3",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_tenant__e6ecbf_idx",
            old_name="dq_anomalie_tenant__idx4",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_tenant__abbe8a_idx",
            old_name="dq_anomalie_tenant__idx5",
        ),
        migrations.RenameIndex(
            model_name="dqanomaly",
            new_name="dq_anomalie_detecte_285ebf_idx",
            old_name="dq_anomalie_detecte_idx",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_tenant__592c7c_idx",
            old_name="dq_trends_tenant__idx",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_tenant__95dfcc_idx",
            old_name="dq_trends_tenant__idx2",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_tenant__af4b6c_idx",
            old_name="dq_trends_tenant__idx3",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_tenant__088d86_idx",
            old_name="dq_trends_tenant__idx4",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_period__e57348_idx",
            old_name="dq_trends_period__idx",
        ),
        migrations.RenameIndex(
            model_name="dqtrend",
            new_name="dq_trends_directi_98644c_idx",
            old_name="dq_trends_directi_idx",
        ),
    ]
