# Generated by Django 6.0.4 on 2026-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0009_alter_alerting_rule_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dqrun",
            name="engine",
            field=models.CharField(
                choices=[
                    ("GREAT_EXPECTATIONS", "Great Expectations"),
                    ("SODA", "Soda"),
                    ("WAREHOUSE_SQL", "Warehouse SQL"),
                ],
                help_text="DQ engine used: GREAT_EXPECTATIONS or SODA",
                max_length=50,
            ),
        ),
    ]
