# Generated by Django 6.0.4 on 2026-05-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0010_alter_dqrun_engine"),
        ("dq", "0100_add_warehouse_config_to_dqrun"),
    ]

    operations = []
