# Generated by Django 5.2.8 on 2026-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dq', '0101_merge_20260519_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqrun',
            name='error_code',
            field=models.CharField(blank=True, db_index=True, help_text='Machine-readable error code (e.g. STUCK_RUN_DETECTED, TIMEOUT)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dqrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Human-readable error message when run failed', null=True),
        ),
    ]
