# Generated by Django 6.0 on 2026-05-24 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0104_merge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dqrun",
            name="error_code",
        ),
        migrations.RemoveField(
            model_name="dqrun",
            name="error_message",
        ),
    ]
