# Generated by Django 6.0 on 2026-05-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0106_add_back_warehouse_config"),
        ("jobs", "0025_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dqrun",
            name="job",
            field=models.ForeignKey(
                help_text="Job that orchestrates this DQ run (nullable: assigned after run creation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dq_runs",
                to="jobs.job",
            ),
        ),
    ]
