# Generated by Django 6.0 on 2026-05-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dq", "0107_make_job_nullable"),
        ("jobs", "0025_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dqrun",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Job that orchestrates this DQ run (nullable: assigned after run creation)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dq_runs",
                to="jobs.job",
            ),
        ),
        migrations.AlterField(
            model_name="dqrun",
            name="profile_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DQ profile key (e.g., intake_basic_gx, intake_basic_soda)",
                max_length=100,
            ),
        ),
    ]
