# Generated by Django 6 — Phase 232.3 breach workflow

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0045_tenant_compliance_ropa_enabled"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreachIncident",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=512)),
                ("summary", models.TextField(blank=True, default="")),
                ("regimes", models.JSONField(default=list, help_text="Applicable regime keys (uppercase strings).")),
                ("discovered_at", models.DateTimeField(db_index=True)),
                ("status", models.CharField(
                    choices=[
                        ("OPEN", "Open"),
                        ("CONTAINED", "Contained"),
                        ("NOTIFIED", "Notifications issued"),
                        ("CLOSED", "Closed"),
                    ],
                    db_index=True,
                    default="OPEN",
                    max_length=32,
                )),
                ("statutory_authority_deadline_utc", models.DateTimeField(db_index=True, help_text="Soonest supervisory-notification deadline (UTC).")),
                ("legal_hold", models.BooleanField(
                    default=False,
                    help_text="When True, breach SLA scans skip this incident.",
                )),
                ("legal_hold_reason", models.TextField(blank=True, default="")),
                ("last_sla_level", models.CharField(
                    choices=[
                        ("NONE", "None"),
                        ("WARN", "Warning window"),
                        ("ALERT", "Alert window"),
                        ("ESCALATED", "Escalated / overdue"),
                    ],
                    default="NONE",
                    max_length=20,
                )),
                ("details_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="breach_incidents_created",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("tenant", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="breach_incidents",
                    to="tenants.tenant",
                )),
            ],
            options={
                "db_table": "breach_incident",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="BreachNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("regime", models.CharField(db_index=True, max_length=32)),
                ("supervisory_authority_id", models.CharField(
                    blank=True,
                    default="",
                    help_text="Id from regulation_authorities.yaml (empty when none).",
                    max_length=64,
                )),
                ("status", models.CharField(
                    choices=[
                        ("PENDING", "Pending"),
                        ("SENT", "Sent"),
                        ("FAILED", "Failed"),
                    ],
                    db_index=True,
                    default="PENDING",
                    max_length=16,
                )),
                ("channel", models.CharField(
                    choices=[
                        ("EMAIL", "Email"),
                        ("MANUAL", "Manual / portal"),
                    ],
                    default="MANUAL",
                    max_length=16,
                )),
                ("statutory_due_at_utc", models.DateTimeField()),
                ("rendered_subject", models.TextField(blank=True, default="")),
                ("rendered_body", models.TextField(blank=True, default="")),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("delivery_proof_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("proof_storage_path", models.CharField(blank=True, default="", max_length=1024)),
                ("proof_s3_version_id", models.CharField(blank=True, default="", max_length=256)),
                ("object_lock_retention_days", models.PositiveIntegerField(
                    default=0,
                    help_text="Days requested for S3 Object Lock retention when archiving proof.",
                )),
                ("outbound_reference", models.CharField(
                    blank=True,
                    default="",
                    help_text="Operator reference (ticket id, case number, message id).",
                    max_length=512,
                )),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("incident", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="notifications",
                    to="breach.breachincident",
                )),
                ("tenant", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="breach_notifications",
                    to="tenants.tenant",
                )),
            ],
            options={
                "db_table": "breach_notification",
                "ordering": ["regime", "supervisory_authority_id"],
            },
        ),
        migrations.CreateModel(
            name="BreachTenantTemplateOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("regime", models.CharField(db_index=True, max_length=32)),
                ("subject_template", models.TextField(blank=True, default="")),
                ("body_template", models.TextField(blank=True, default="")),
                ("template_version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="breach_template_overrides",
                    to="tenants.tenant",
                )),
                ("updated_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="breach_template_updates",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={"db_table": "breach_tenant_template_override"},
        ),
        migrations.AddConstraint(
            model_name="breachtenanttemplateoverride",
            constraint=models.UniqueConstraint(
                fields=("tenant", "regime"),
                name="breach_templ_override_tenant_regime_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="breachincident",
            index=models.Index(fields=["tenant", "status"], name="breach_inci_tenant__d2ee18_idx"),
        ),
        migrations.AddIndex(
            model_name="breachincident",
            index=models.Index(
                fields=["tenant", "statutory_authority_deadline_utc"],
                name="breach_inci_tenant__3648d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="breachnotification",
            index=models.Index(fields=["tenant", "status"], name="breach_noti_tenant__f7ab90_idx"),
        ),
        migrations.AddIndex(
            model_name="breachnotification",
            index=models.Index(
                fields=["tenant", "statutory_due_at_utc"],
                name="breach_noti_tenant__4821fa_idx",
            ),
        ),
    ]
