# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breach', '0003_rename_template_override_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='breachincident',
            new_name='breach_inci_tenant__cd4ae0_idx',
            old_name='breach_inci_tenant__d2ee18_idx',
        ),
        migrations.RenameIndex(
            model_name='breachincident',
            new_name='breach_inci_tenant__fb5539_idx',
            old_name='breach_inci_tenant__3648d8_idx',
        ),
        migrations.RenameIndex(
            model_name='breachnotification',
            new_name='breach_noti_tenant__2c8639_idx',
            old_name='breach_noti_tenant__f7ab90_idx',
        ),
        migrations.RenameIndex(
            model_name='breachnotification',
            new_name='breach_noti_tenant__3ebfd8_idx',
            old_name='breach_noti_tenant__4821fa_idx',
        ),
    ]
