# Generated by Django 6.0.4 on 2026-06-05 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breach", "0005_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breachincident",
            name="statutory_authority_deadline_utc",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Soonest supervisory-notification deadline (UTC).",
            ),
        ),
    ]
