# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ropa', '0002_enable_rls_ropa_generations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ropageneration',
            new_name='ropa_genera_tenant__ae8056_idx',
            old_name='ropa_gener_tenant__6e4e6d_idx',
        ),
        migrations.RenameIndex(
            model_name='ropageneration',
            new_name='ropa_genera_tenant__b3331f_idx',
            old_name='ropa_gener_tenant__dfc7e4_idx',
        ),
    ]
