# Generated by Django 4.2.16 on 2025-11-23 19:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address (unique across platform)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('display_name', models.CharField(blank=True, help_text='User display name', max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('DISABLED', 'Disabled')], default='INVITED', help_text='User status: ACTIVE, INVITED, or DISABLED', max_length=20)),
                ('is_platform_admin', models.BooleanField(default=False, help_text='Platform-level admin privileges (transcends tenant boundaries)')),
                ('invitation_token', models.UUIDField(blank=True, help_text='UUID token for invitation acceptance', null=True)),
                ('invitation_token_expires_at', models.DateTimeField(blank=True, help_text='Invitation token expiration time', null=True)),
                ('invitation_token_used_at', models.DateTimeField(blank=True, help_text='When invitation token was used', null=True)),
                ('password_reset_token', models.UUIDField(blank=True, help_text='UUID token for password reset', null=True)),
                ('password_reset_token_expires_at', models.DateTimeField(blank=True, help_text='Password reset token expiration time', null=True)),
                ('password_reset_token_used_at', models.DateTimeField(blank=True, help_text='When password reset token was used', null=True)),
                ('token_version', models.IntegerField(default=1, help_text='Token version, incremented on password reset or role change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant this user belongs to (null for platform admins)', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='tenants.tenant')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Role name (e.g., TENANT_ADMIN, DATA_PROVIDER)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.tenant')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'ordering': ['user', 'role'],
                'indexes': [models.Index(fields=['user', 'role'], name='user_roles_user_id_801a9e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'name'], name='roles_tenant__74cc42_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_role_name'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='users_tenant__afadfd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['invitation_token'], name='users_invitat_eaafe0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['password_reset_token'], name='users_passwor_dda668_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'email'), name='unique_tenant_email'),
        ),
    ]
