# Generated by Django 6.0 on 2025-12-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited'), ('DISABLED', 'Disabled'), ('SUSPENDED', 'Suspended')], default='INVITED', help_text='User status: ACTIVE, INVITED, or DISABLED', max_length=20),
        ),
    ]
