# Generated by Django 6.0.3 on 2026-03-06 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_add_user_tenant_membership"),
        ("users", "0004_user_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTenantMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Tenant this membership grants access to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this membership belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_tenant_memberships",
                "ordering": ["user", "tenant"],
                "indexes": [
                    models.Index(fields=["user", "tenant"], name="user_tenant_user_id_47ab36_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "tenant"), name="unique_user_tenant_membership"
                    )
                ],
            },
        ),
    ]
