# Generated by Django 6.0 on 2026-03-23 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_null_display_name_avatar_url"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="userrole",
            new_name="user_roles_user_id_93c493_idx",
            old_name="user_roles_user_tenant_idx",
        ),
    ]
