# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_phase260_pii_viewer_role_backfill'),
        ('users', '0022_add_account_lockout_fields'),
    ]

    operations = [
    ]
