# Generated by Django 6.0.4 on 2026-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20260513_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unsubscribe_token',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hex hash of the 1-click unsubscribe token', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribe_token_created_at',
            field=models.DateTimeField(blank=True, help_text='When the current unsubscribe token was issued', null=True),
        ),
    ]
