# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_add_has_seen_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_views',
            field=models.JSONField(blank=True, default=list, help_text='Saved list filters/views (URL-shareable).'),
        ),
    ]
