# Generated by Django 6.0 on 2026-05-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_merge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="has_seen_tour",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("INVITED", "Invited"),
                    ("DISABLED", "Disabled"),
                    ("SUSPENDED", "Suspended"),
                    ("INACTIVE", "Inactive"),
                ],
                default="INVITED",
                help_text="User status: ACTIVE, INVITED, or DISABLED",
                max_length=20,
            ),
        ),
    ]
