# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="webhook",
            new_name="webhooks_tenant__3268c0_idx",
            old_name="webhooks_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhook",
            new_name="webhooks_tenant__a89f44_idx",
            old_name="webhooks_tenant_events_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_webhook_071d92_idx",
            old_name="webhook_deliveries_webhook_status_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_webhook_3e57f9_idx",
            old_name="webhook_deliveries_webhook_retry_idx",
        ),
        migrations.RenameIndex(
            model_name="webhookdelivery",
            new_name="webhook_del_status_741062_idx",
            old_name="webhook_deliveries_status_retry_idx",
        ),
    ]
