# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_webhookdelivery_signing_key_uuid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhooksigningkey',
            new_name='webhook_sig_webhook_375250_idx',
            old_name='wh_signing_keys_wh_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksigningkey',
            new_name='webhook_sig_status_f367b6_idx',
            old_name='wh_signing_keys_stat_ret_idx',
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead Letter'), ('RATE_LIMITED', 'Rate Limited')], default='PENDING', help_text='Delivery status', max_length=20),
        ),
    ]
