#!/usr/bin/env python3
"""Generate a local dev .env for quickstart (Phase 313.4/313.6 review).

Idempotent: refuses to overwrite an existing .env. Values are random
DEV-ONLY secrets (never committed — .env is gitignored) plus the required
compose interpolation vars (MINIO_ROOT_PASSWORD, POSTGRES_PASSWORD,
FUSEKI_ADMIN_PASSWORD) so a fresh public clone can `make quickstart`
without any prior setup.

Usage: python scripts/make_dev_env.py
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

DEV_ENV_TEMPLATE = """\
# Local dev environment — generated by scripts/make_dev_env.py (dev-only).
# NEVER commit this file (it is gitignored); rotate freely.
ENVIRONMENT=development
DEBUG=True
SECRET_KEY={secret_key}
JWT_SECRET_KEY={jwt_secret_key}
ENCRYPTION_KEY={encryption_key}
ALLOWED_HOSTS=localhost,127.0.0.1,api-service
POSTGRES_USER=hub
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=hub
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
MINIO_ROOT_USER={minio_user}
MINIO_ROOT_PASSWORD={minio_password}
AWS_ACCESS_KEY_ID={minio_user}
AWS_SECRET_ACCESS_KEY={minio_password}
AWS_STORAGE_BUCKET_NAME=hub-files
AWS_S3_ENDPOINT_URL=http://minio:9000
FUSEKI_ADMIN_PASSWORD={fuseki_password}
GRAFANA_ADMIN_PASSWORD={grafana_password}
"""


def main() -> int:
    target = Path(__file__).resolve().parents[1] / ".env"
    if target.exists():
        print(f"{target} already exists — leaving it untouched")
        return 0
    values = {
        "secret_key": secrets.token_urlsafe(48),
        "jwt_secret_key": secrets.token_urlsafe(48),
        "encryption_key": secrets.token_urlsafe(32),
        "postgres_password": secrets.token_urlsafe(18),
        "minio_user": "minio-dev",
        "minio_password": secrets.token_urlsafe(18),
        "fuseki_password": secrets.token_urlsafe(18),
        "grafana_password": secrets.token_urlsafe(18),
    }
    target.write_text(DEV_ENV_TEMPLATE.format(**values))
    print(f"dev .env generated at {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
