#!/bin/bash
# Setup CKAN Test Credentials
#
# This script helps set up CKAN test credentials for integration tests.
# It provides instructions and can optionally set environment variables.
#
# Usage:
#   ./scripts/setup_ckan_test_credentials.sh
#   source .env.test.ckan  # To load credentials

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="${PROJECT_DIR}/.env.test.ckan"

echo "=========================================="
echo "CKAN Test Credentials Setup"
echo "=========================================="
echo ""

# Check if .env.test.ckan already exists
if [ -f "$ENV_FILE" ]; then
    echo "✓ Found existing .env.test.ckan file"
    echo "  Current configuration:"
    grep -E "^CKAN_" "$ENV_FILE" || echo "  (no CKAN variables set)"
    echo ""
    read -p "Do you want to update it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
fi

echo "To run push operation tests, you need:"
echo "1. A CKAN instance URL (e.g., https://demo.ckan.org)"
echo "2. An API key with write permissions"
echo ""

# Get CKAN URL
read -p "CKAN Instance URL (default: https://demo.ckan.org): " CKAN_URL
CKAN_URL=${CKAN_URL:-https://demo.ckan.org}

echo ""
echo "For API key setup:"
echo "1. Visit ${CKAN_URL}"
echo "2. Create an account (if you don't have one)"
echo "3. Go to your user profile"
echo "4. Generate an API key"
echo "5. Copy the API key"
echo ""

read -p "CKAN API Key (leave empty to skip): " CKAN_API_KEY

# Write to .env.test.ckan
cat > "$ENV_FILE" << EOF
# CKAN Test Credentials
# Generated by setup_ckan_test_credentials.sh
# Source this file before running tests: source .env.test.ckan

export CKAN_TEST_URL="${CKAN_URL}"
EOF

if [ -n "$CKAN_API_KEY" ]; then
    echo "export CKAN_TEST_API_KEY=\"${CKAN_API_KEY}\"" >> "$ENV_FILE"
    echo ""
    echo "✓ Credentials saved to .env.test.ckan"
    echo ""
    echo "To use these credentials:"
    echo "  source .env.test.ckan"
    echo "  pytest hub/apps/integrations/tests/test_ckan_connector_push.py -v"
else
    echo ""
    echo "⚠ No API key provided. Write operation tests will be skipped."
    echo "  You can add it later by editing .env.test.ckan"
fi

echo ""
echo "Note: .env.test.ckan is in .gitignore and won't be committed."

