# Generated by Django 6.0 on 2025-12-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_to_emai_5d5179_idx',
            old_name='email_deli_to_emai_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_email_t_f23e6a_idx',
            old_name='email_deli_email_t_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_created_272233_idx',
            old_name='email_deli_created_idx',
        ),
        migrations.RenameIndex(
            model_name='emaildelivery',
            new_name='email_deliv_tenant__4830a9_idx',
            old_name='email_deli_tenant__idx',
        ),
    ]
