# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_rename_email_deli_to_emai_idx_email_deliv_to_emai_5d5179_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("USER_INVITATION", "User Invitation"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("JOB_COMPLETION", "Job Completion"),
                    ("JOB_FAILURE", "Job Failure"),
                    ("API_DEPRECATION", "API Deprecation"),
                    ("ODPS_CREATION_COMPLETION", "ODPS Creation Completion"),
                    ("ODPS_NORMALIZATION_FAILURE", "ODPS Normalization Failure"),
                    ("ODPS_LINKING_STATUS", "ODPS Linking Status"),
                    ("MARKETPLACE_SYNC_COMPLETION", "Marketplace Sync Completion"),
                    ("MARKETPLACE_SYNC_FAILURE", "Marketplace Sync Failure"),
                    ("MARKETPLACE_CONNECTION_TEST_FAILURE", "Marketplace Connection Test Failure"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                ],
                help_text="Type of email sent",
                max_length=50,
            ),
        ),
    ]
