# Generated by Django 6.0 on 2026-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_add_ml_email_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("USER_INVITATION", "User Invitation"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("JOB_COMPLETION", "Job Completion"),
                    ("JOB_FAILURE", "Job Failure"),
                    ("API_DEPRECATION", "API Deprecation"),
                    ("ODPS_CREATION_COMPLETION", "ODPS Creation Completion"),
                    ("ODPS_NORMALIZATION_FAILURE", "ODPS Normalization Failure"),
                    ("ODPS_LINKING_STATUS", "ODPS Linking Status"),
                    ("MARKETPLACE_SYNC_COMPLETION", "Marketplace Sync Completion"),
                    ("MARKETPLACE_SYNC_FAILURE", "Marketplace Sync Failure"),
                    ("MARKETPLACE_CONNECTION_TEST_FAILURE", "Marketplace Connection Test Failure"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                    ("CUSTOMER_BILLING_REPORT", "Customer Billing Report"),
                    ("ML_TRAINING_COMPLETION", "ML Training Completion"),
                    ("ML_TRAINING_FAILURE", "ML Training Failure"),
                    ("ML_INFERENCE_FAILURE", "ML Inference Failure"),
                    ("ML_MODEL_DEPLOYED", "ML Model Deployed"),
                ],
                help_text="Type of email sent",
                max_length=50,
            ),
        ),
    ]
