# Generated by Django 6.0 on 2026-04-23 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_add_archival_fields"),
        ("notifications", "0007_usernotification"),
        ("tenants", "0023_add_archival_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="usernotification",
            new_name="user_notifi_user_id_304d2d_idx",
            old_name="user_notif_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="usernotification",
            new_name="user_notifi_tenant__32b3d5_idx",
            old_name="user_notif_tenant_idx",
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("USER_INVITATION", "User Invitation"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("JOB_COMPLETION", "Job Completion"),
                    ("JOB_FAILURE", "Job Failure"),
                    ("API_DEPRECATION", "API Deprecation"),
                    ("ODPS_CREATION_COMPLETION", "ODPS Creation Completion"),
                    ("ODPS_NORMALIZATION_FAILURE", "ODPS Normalization Failure"),
                    ("ODPS_LINKING_STATUS", "ODPS Linking Status"),
                    ("MARKETPLACE_SYNC_COMPLETION", "Marketplace Sync Completion"),
                    ("MARKETPLACE_SYNC_FAILURE", "Marketplace Sync Failure"),
                    ("MARKETPLACE_CONNECTION_TEST_FAILURE", "Marketplace Connection Test Failure"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                    ("CUSTOMER_BILLING_REPORT", "Customer Billing Report"),
                    ("ML_TRAINING_COMPLETION", "ML Training Completion"),
                    ("ML_TRAINING_FAILURE", "ML Training Failure"),
                    ("ML_INFERENCE_FAILURE", "ML Inference Failure"),
                    ("ML_MODEL_DEPLOYED", "ML Model Deployed"),
                    ("TRANSFORMATION_COMPLETION", "Transformation Completion"),
                    ("TRANSFORMATION_FAILURE", "Transformation Failure"),
                ],
                help_text="Type of email sent",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="audit_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to the underlying audit event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_notifications",
                to="audit.auditevent",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="resource_id",
            field=models.UUIDField(
                blank=True, help_text="Resource UUID the notification points at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="resource_type",
            field=models.CharField(
                blank=True,
                help_text="Resource type the notification points at (matches AuditEvent.resource_type)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="tenant",
            field=models.ForeignKey(
                help_text="Tenant this notification belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="user",
            field=models.ForeignKey(
                help_text="Recipient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
