# Generated by Django 6.0 on 2026-05-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0008_rename_user_notif_user_read_idx_user_notifi_user_id_304d2d_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaildelivery",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("USER_INVITATION", "User Invitation"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("JOB_COMPLETION", "Job Completion"),
                    ("JOB_FAILURE", "Job Failure"),
                    ("API_DEPRECATION", "API Deprecation"),
                    ("ODPS_CREATION_COMPLETION", "ODPS Creation Completion"),
                    ("ODPS_NORMALIZATION_FAILURE", "ODPS Normalization Failure"),
                    ("ODPS_LINKING_STATUS", "ODPS Linking Status"),
                    ("MARKETPLACE_SYNC_COMPLETION", "Marketplace Sync Completion"),
                    ("MARKETPLACE_SYNC_FAILURE", "Marketplace Sync Failure"),
                    ("MARKETPLACE_CONNECTION_TEST_FAILURE", "Marketplace Connection Test Failure"),
                    ("API_KEY_CREATED", "API Key Created"),
                    ("API_KEY_REVOKED", "API Key Revoked"),
                    ("CUSTOMER_BILLING_REPORT", "Customer Billing Report"),
                    ("ML_TRAINING_COMPLETION", "ML Training Completion"),
                    ("ML_TRAINING_FAILURE", "ML Training Failure"),
                    ("ML_INFERENCE_FAILURE", "ML Inference Failure"),
                    ("ML_MODEL_DEPLOYED", "ML Model Deployed"),
                    ("TRANSFORMATION_COMPLETION", "Transformation Completion"),
                    ("TRANSFORMATION_FAILURE", "Transformation Failure"),
                    (
                        "ASSET_CONTRACT_STRUCTURELESS_PENDING",
                        "Asset Contract Structureless — Pending Remediation",
                    ),
                    (
                        "SCHEMA_EDITOR_AVAILABLE",
                        "Schema editor now available — triage your contracts",
                    ),
                    (
                        "SCHEMA_EDITOR_RESIDUE_REMINDER",
                        "Schema editor — residue reminder + 30-day deadline",
                    ),
                    (
                        "ASSET_AUTO_REVERT_WARNING",
                        "Final warning — assets will be auto-reverted to DRAFT",
                    ),
                    (
                        "ASSET_AUTO_REVERTED_NOTIFICATION",
                        "Asset auto-reverted to DRAFT (Phase 227 Wave 5)",
                    ),
                ],
                help_text="Type of email sent",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("GOVERNANCE", "Governance"),
                    ("MARKETPLACE", "Marketplace"),
                    ("JOBS", "Jobs"),
                    ("CONTRACTS", "Contracts"),
                    ("SYSTEM", "System"),
                    ("LINEAGE_IMPACT", "Lineage Impact"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
