apiVersion: v1
kind: Service
metadata:
  name: {{ include "datahub-core.name" . }}-frontend
  labels: {{ include "datahub-core.labels" . | nindent 4 }}
spec:
  ports: [{ port: {{ .Values.service.frontendPort }}, targetPort: 80 }]
  selector: { app: {{ include "datahub-core.name" . }}-frontend }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datahub-core.name" . }}-frontend
  labels: {{ include "datahub-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: {{ include "datahub-core.name" . }}-frontend }
  template:
    metadata:
      labels: { app: {{ include "datahub-core.name" . }}-frontend }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports: [{ containerPort: 80 }]
