# Generated by Django 4.2.16 on 2025-11-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_tenant__76965e_idx",
            old_name="assets_tenant_key_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_tenant__41780b_idx",
            old_name="assets_tenant_visibility_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_tenant__e899e7_idx",
            old_name="assets_tenant_dq_status_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_tenant__b73896_idx",
            old_name="assets_tenant_compliance_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="assets_tenant__6a5802_idx",
            old_name="assets_tenant_status_idx",
        ),
    ]
