# Generated by Django 6.0 on 2025-12-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_popularity_metrics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_tenant_health_idx',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='assets_tenant_popularity_idx',
        ),
    ]
