# Generated by Django 6.0 on 2026-01-05 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_assets_tenant_health_idx_and_more'),
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='source_metadata',
            field=models.JSONField(blank=True, help_text='Source metadata for federated assets: marketplace_type, marketplace_id, listing_id, listing_url, synced_at, sync_job_id', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_type',
            field=models.CharField(choices=[('HUB_NATIVE', 'Hub Native'), ('FEDERATED', 'Federated')], default='HUB_NATIVE', help_text='Asset source: HUB_NATIVE (created in Hub) or FEDERATED (imported from marketplace)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'source_type'], name='assets_tenant__69c445_idx'),
        ),
    ]
