# Generated by Django 6.0 on 2026-01-07 17:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_source_metadata_asset_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResourceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.CharField(help_text='External resource identifier from marketplace', max_length=255)),
                ('name', models.CharField(help_text='Resource name', max_length=255)),
                ('url', models.URLField(help_text='External resource URL')),
                ('format', models.CharField(help_text='Resource format (CSV, JSON, PARQUET, etc.)', max_length=50)),
                ('size_bytes', models.BigIntegerField(blank=True, help_text='Resource size in bytes', null=True)),
                ('marketplace_type', models.CharField(help_text='Marketplace type (e.g., CKAN_INSTANCE, DADOS_GOV_BR)', max_length=50)),
                ('connection_id', models.UUIDField(help_text='Reference to MarketplaceConnection used to access this resource')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the external resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(help_text='Asset this external resource belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='external_resource_references', to='assets.asset')),
            ],
            options={
                'db_table': 'external_resource_references',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['asset', 'resource_id'], name='external_re_asset_i_394b67_idx'), models.Index(fields=['connection_id'], name='external_re_connect_658633_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'resource_id'), name='unique_external_resource_per_asset')],
            },
        ),
    ]
