# Generated by Django 6.0 on 2026-01-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_external_resource_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='data_strategy',
            field=models.CharField(choices=[('METADATA_ONLY', 'Metadata Only'), ('DOWNLOAD_SELECTIVE', 'Selective Download'), ('DOWNLOAD_ALL', 'Download All')], default='METADATA_ONLY', help_text='Data strategy for federated assets: METADATA_ONLY (store references only), DOWNLOAD_SELECTIVE (download specific resources), DOWNLOAD_ALL (download all resources)', max_length=20),
        ),
    ]
