# Generated by Django 6.0.4 on 2026-05-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_asset_warehouse_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='data_strategy',
            field=models.CharField(choices=[('METADATA_ONLY', 'Metadata Only'), ('DOWNLOAD_SELECTIVE', 'Selective Download'), ('DOWNLOAD_ALL', 'Download All'), ('LIVE_QUERY', 'Live Query')], default='METADATA_ONLY', help_text='Data strategy: METADATA_ONLY, DOWNLOAD_SELECTIVE, DOWNLOAD_ALL, LIVE_QUERY (Phase 275)', max_length=30),
        ),
    ]
