"""
285.13.2.1-4 — Canonical plan definitions.

PLATFORM_PLANS (7 tiers, incl. SANDBOX) + ML_PLANS (3 tiers).  Every plan includes
all required fields with non-None limits_json and tier_profile dict.
Imported by ``seed_default_plans.py`` and ``PersonalTenantService``.
"""

from __future__ import annotations

from typing import Any

from .models import PlanCategory, PlanTier

# ── Platform Plans (6 tiers) ──────────────────────────────────────────

PLATFORM_PLANS: list[dict[str, Any]] = [
    # ── 303.1: Developer sandbox (lowest tier, minimal limits) ──────────
    {
        "slug": "sandbox",
        "name": "Sandbox",
        "tier": PlanTier.SANDBOX,
        "category": PlanCategory.BASE,
        "order": -1,  # Below FREE — sandbox is for dev/testing only
        "price_amount_cents": 0,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 25,
        "markup_bps": 0,
        "marketplace_take_rate_bps": 1500,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_assets": 5,
            "max_datasets": 5,
            "max_contracts": 3,
            "max_webhooks": 1,
            "max_mesh_domains": 0,
            "max_users": 1,
            "max_marketplace_listings": 0,
            "max_marketplace_connections": 1,
            "max_marketplace_orders_per_month": 5,
            "max_virtual_datasets": 1,
            "max_scheduled_ingestions": 1,
            "max_scheduled_exports": 0,
            "max_scheduled_runs_per_month": 10,
            "max_export_runs_per_month": 5,
            "max_api_calls_per_month": 500,
            "max_compliance_runs_per_month": 5,
            "max_dq_runs_per_month": 5,
            "max_access_requests_per_month": 0,
        },
        "tier_profile": {
            "headline": "For development and testing",
            "description_markdown": "Minimal limits for sandbox development. Not for production use.",
            "features_highlight": "5 assets, 5 datasets, 3 contracts",
            "is_recommended": False,
            "is_public": False,
            "self_serve": True,
            "sales_only": False,
            "sort_order": -1,
        },
    },
    {
        "slug": "free",
        "name": "Free",
        "tier": PlanTier.FREE,
        "category": PlanCategory.BASE,
        "order": 0,
        "price_amount_cents": 0,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 50,
        "markup_bps": 0,
        "marketplace_take_rate_bps": 1500,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_assets": 3,
            "max_datasets": 5,
            "max_contracts": 3,
            "max_webhooks": 1,
            "max_mesh_domains": 1,
            "max_users": 3,
            "max_marketplace_listings": 1,
            "max_marketplace_connections": 1,
            "max_marketplace_orders_per_month": 10,
            "max_virtual_datasets": 1,
            "max_scheduled_ingestions": 1,
            "max_scheduled_exports": 1,
            "max_scheduled_runs_per_month": 30,
            "max_export_runs_per_month": 30,
            "max_api_calls_per_month": 1000,
            "max_compliance_runs_per_month": 10,
            "max_dq_runs_per_month": 10,
            "max_access_requests_per_month": 5,
        },
        "tier_profile": {
            "headline": "For exploring the platform",
            "description_markdown": "Free tier with basic limits. No credit card required.",
            "features_highlight": "3 assets, 5 datasets, basic DQ & compliance",
            "is_recommended": False,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 0,
        },
    },
    {
        "slug": "starter",
        "name": "Starter",
        "tier": PlanTier.STARTER,
        "category": PlanCategory.BASE,
        "order": 1,
        "price_amount_cents": 4900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 200,
        "markup_bps": 2350,
        "marketplace_take_rate_bps": 1200,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_assets": 10,
            "max_datasets": 20,
            "max_contracts": 10,
            "max_webhooks": 3,
            "max_mesh_domains": 2,
            "max_users": 10,
            "max_marketplace_listings": 3,
            "max_marketplace_connections": 3,
            "max_marketplace_orders_per_month": 50,
            "max_virtual_datasets": 3,
            "max_scheduled_ingestions": 3,
            "max_scheduled_exports": 3,
            "max_scheduled_runs_per_month": 100,
            "max_export_runs_per_month": 100,
            "max_api_calls_per_month": 10000,
            "max_compliance_runs_per_month": 50,
            "max_dq_runs_per_month": 50,
            "max_access_requests_per_month": 20,
        },
        "tier_profile": {
            "headline": "For small teams getting started",
            "description_markdown": "Essential features for small data teams.",
            "features_highlight": "10 assets, 20 datasets, 10 users",
            "is_recommended": False,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 1,
        },
    },
    {
        "slug": "growth",
        "name": "Growth",
        "tier": PlanTier.GROWTH,
        "category": PlanCategory.BASE,
        "order": 2,
        "price_amount_cents": 19900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 800,
        "markup_bps": 2375,
        "marketplace_take_rate_bps": 1000,
        "includes_regulations": ["GDPR"],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_assets": 50,
            "max_datasets": 100,
            "max_contracts": 50,
            "max_webhooks": 10,
            "max_mesh_domains": 5,
            "max_users": 25,
            "max_marketplace_listings": 10,
            "max_marketplace_connections": 10,
            "max_marketplace_orders_per_month": 200,
            "max_virtual_datasets": 10,
            "max_scheduled_ingestions": 10,
            "max_scheduled_exports": 10,
            "max_scheduled_runs_per_month": 500,
            "max_export_runs_per_month": 500,
            "max_api_calls_per_month": 50000,
            "max_compliance_runs_per_month": 200,
            "max_dq_runs_per_month": 200,
            "max_access_requests_per_month": 50,
        },
        "tier_profile": {
            "headline": "For growing data teams",
            "description_markdown": "GDPR compliance included. Higher limits for production use.",
            "features_highlight": "50 assets, GDPR, 25 users",
            "is_recommended": False,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 2,
        },
    },
    {
        "slug": "pro",
        "name": "Pro",
        "tier": PlanTier.PRO,
        "category": PlanCategory.BASE,
        "order": 3,
        "price_amount_cents": 49900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 2000,
        "markup_bps": 2395,
        "marketplace_take_rate_bps": 800,
        "includes_regulations": ["GDPR", "CCPA", "UK_GDPR"],
        "compliance_pro_pack": True,
        "limits_json": {
            "max_assets": 200,
            "max_datasets": 500,
            "max_contracts": 200,
            "max_webhooks": 30,
            "max_mesh_domains": 10,
            "max_users": 100,
            "max_marketplace_listings": 50,
            "max_marketplace_connections": 30,
            "max_marketplace_orders_per_month": 1000,
            "max_virtual_datasets": 50,
            "max_scheduled_ingestions": 30,
            "max_scheduled_exports": 30,
            "max_scheduled_runs_per_month": 2000,
            "max_export_runs_per_month": 2000,
            "max_api_calls_per_month": 250000,
            "max_compliance_runs_per_month": 500,
            "max_dq_runs_per_month": 500,
            "max_access_requests_per_month": 200,
        },
        "tier_profile": {
            "headline": "For professional data platforms",
            "description_markdown": "Full compliance suite. Marketplace access. Priority support.",
            "features_highlight": "200 assets, GDPR+CCPA+UK_GDPR, Compliance Pro, 100 users",
            "is_recommended": True,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 3,
        },
    },
    {
        "slug": "scale",
        "name": "Scale",
        "tier": PlanTier.SCALE,
        "category": PlanCategory.BASE,
        "order": 4,
        "price_amount_cents": 99900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 5000,
        "markup_bps": 1898,
        "marketplace_take_rate_bps": 500,
        "includes_regulations": ["GDPR", "CCPA", "UK_GDPR", "PIPL_CN", "LGPD_BR"],
        "compliance_pro_pack": True,
        "limits_json": {
            "max_assets": 1000,
            "max_datasets": 5000,
            "max_contracts": 1000,
            "max_webhooks": 100,
            "max_mesh_domains": 50,
            "max_users": 500,
            "max_marketplace_listings": 200,
            "max_marketplace_connections": 100,
            "max_marketplace_orders_per_month": 5000,
            "max_virtual_datasets": 200,
            "max_scheduled_ingestions": 100,
            "max_scheduled_exports": 100,
            "max_api_calls_per_month": 1000000,
            "max_compliance_runs_per_month": 2000,
            "max_dq_runs_per_month": 2000,
            "max_access_requests_per_month": 500,
        },
        "tier_profile": {
            "headline": "For scaling enterprise data mesh",
            "description_markdown": "High-volume data mesh with global compliance coverage.",
            "features_highlight": "1000 assets, 5 global regulations, Compliance Pro, 500 users",
            "is_recommended": False,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 4,
        },
    },
    {
        "slug": "enterprise",
        "name": "Enterprise",
        "tier": PlanTier.ENTERPRISE,
        "category": PlanCategory.BASE,
        "order": 5,
        "price_amount_cents": None,
        "price_currency": "USD",
        "billing_interval": "annual",
        "flsc_estimate_cents": None,
        "markup_bps": None,
        "marketplace_take_rate_bps": 300,
        "includes_regulations": [
            "GDPR",
            "CCPA",
            "UK_GDPR",
            "PIPL_CN",
            "LGPD_BR",
            "POPIA_ZA",
            "PDPA_SG",
        ],
        "compliance_pro_pack": True,
        "limits_json": {},  # unlimited — all keys omitted = no cap
        "tier_profile": {
            "headline": "For the whole organization",
            "description_markdown": "Custom contract. Unlimited everything. Dedicated support.",
            "features_highlight": "Unlimited assets, all 7 regulations, Compliance Pro, SSO",
            "is_recommended": False,
            "is_public": True,
            "self_serve": False,
            "sales_only": True,
            "sort_order": 5,
        },
    },
]

# ── ML Plans (3 tiers) ────────────────────────────────────────────────

ML_PLANS: list[dict[str, Any]] = [
    {
        "slug": "ml-starter",
        "name": "ML Starter",
        "tier": PlanTier.STARTER,
        "category": PlanCategory.ML_AI,
        "order": 10,
        "price_amount_cents": 9900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 500,
        "markup_bps": 1880,
        "marketplace_take_rate_bps": 1200,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_ml_training_jobs_per_month": 5,
            "max_ml_inference_requests_per_month": 10000,
            "max_ml_models": 3,
        },
        "tier_profile": {
            "headline": "For ML experimentation",
            "description_markdown": "Get started with ML training and inference.",
            "features_highlight": "5 training jobs/month, 3 models, 10K inference requests",
            "is_recommended": False,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 10,
        },
    },
    {
        "slug": "ml-pro",
        "name": "ML Pro",
        "tier": PlanTier.PRO,
        "category": PlanCategory.ML_AI,
        "order": 11,
        "price_amount_cents": 49900,
        "price_currency": "USD",
        "billing_interval": "monthly",
        "flsc_estimate_cents": 2500,
        "markup_bps": 1896,
        "marketplace_take_rate_bps": 800,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {
            "max_ml_training_jobs_per_month": 50,
            "max_ml_inference_requests_per_month": 500000,
            "max_ml_models": 20,
        },
        "tier_profile": {
            "headline": "For production ML pipelines",
            "description_markdown": "Production-grade ML with higher limits.",
            "features_highlight": "50 training jobs/month, 20 models, 500K inference requests",
            "is_recommended": True,
            "is_public": True,
            "self_serve": True,
            "sales_only": False,
            "sort_order": 11,
        },
    },
    {
        "slug": "ml-enterprise",
        "name": "ML Enterprise",
        "tier": PlanTier.ENTERPRISE,
        "category": PlanCategory.ML_AI,
        "order": 12,
        "price_amount_cents": None,
        "price_currency": "USD",
        "billing_interval": "annual",
        "flsc_estimate_cents": None,
        "markup_bps": None,
        "marketplace_take_rate_bps": 300,
        "includes_regulations": [],
        "compliance_pro_pack": False,
        "limits_json": {},  # unlimited
        "tier_profile": {
            "headline": "For enterprise AI teams",
            "description_markdown": "Custom ML contract. Unlimited everything.",
            "features_highlight": "Unlimited training, models, and inference",
            "is_recommended": False,
            "is_public": True,
            "self_serve": False,
            "sales_only": True,
            "sort_order": 12,
        },
    },
]
