# Generated by Django 6.0 on 2025-12-26 00:57

import django.db.models.deletion
import hub.apps.virtualization.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_add_odps_refs_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the virtual dataset', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Virtual dataset name (unique per tenant)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Virtual dataset description', null=True)),
                ('query', models.TextField(help_text='Query definition (SQL, SPARQL, federated query, etc.)')),
                ('query_type', models.CharField(choices=[('SQL', 'SQL Query'), ('SPARQL', 'SPARQL Query'), ('FEDERATED', 'Federated Query'), ('GRAPHQL', 'GraphQL Query'), ('REST', 'REST API Query')], help_text='Type of query: SQL, SPARQL, FEDERATED, GRAPHQL, REST', max_length=20)),
                ('schema', models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_dict, help_text='Output schema definition as JSON (fields, types, constraints, etc.)')),
                ('sources', models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_list, help_text='Source system configurations as JSON array (connection details, mappings, etc.)')),
                ('version', models.CharField(default='1.0.0', help_text='Virtual dataset version (semantic versioning: major.minor.patch)', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Virtual dataset status: DRAFT, ACTIVE, INACTIVE, ARCHIVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the virtual dataset was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the virtual dataset was last updated')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the virtual dataset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_virtual_datasets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this virtual dataset belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='virtual_datasets', to='tenants.tenant')),
            ],
            options={
                'db_table': 'virtual_datasets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='virtual_dat_tenant__03bd99_idx'), models.Index(fields=['created_by'], name='virtual_dat_created_ce48c5_idx'), models.Index(fields=['query_type'], name='virtual_dat_query_t_3e7604_idx'), models.Index(fields=['status'], name='virtual_dat_status_19f0fa_idx'), models.Index(fields=['created_at'], name='virtual_dat_created_945d8c_idx'), models.Index(fields=['tenant', 'status'], name='virtual_dat_tenant__bb3c12_idx'), models.Index(fields=['tenant', 'query_type'], name='virtual_dat_tenant__7e2064_idx'), models.Index(fields=['tenant', 'created_at'], name='virtual_dat_tenant__4fcb10_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name', 'version'), name='unique_virtual_dataset_name_version_per_tenant')],
            },
        ),
    ]
