# Generated by Django 6.0 on 2025-12-26 01:14

import hub.apps.virtualization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualdataset',
            name='schema',
            field=models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_dict, help_text='Output schema definition as JSON (fields, types, constraints, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='virtualdataset',
            name='sources',
            field=models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_list, help_text='Source system configurations as JSON array (connection details, mappings, etc.)', null=True),
        ),
    ]
