# Generated by Django 6.0 on 2025-12-26 08:27

import django.db.models.deletion
import hub.apps.virtualization.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualization', '0002_alter_virtualdataset_schema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the query execution', primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='Query text that was executed (may include parameter substitution)')),
                ('parameters', models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_dict, help_text='Query parameters as JSON object (parameter name -> value mapping)', null=True)),
                ('execution_mode', models.CharField(choices=[('SYNC', 'Synchronous'), ('ASYNC', 'Asynchronous'), ('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual'), ('AUTOMATED', 'Automated')], default='MANUAL', help_text='Execution mode: SYNC, ASYNC, SCHEDULED, MANUAL, AUTOMATED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Execution status: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the execution started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the execution completed', null=True)),
                ('result_cache_key', models.CharField(blank=True, help_text='Cache key for result storage (optional)', max_length=255, null=True)),
                ('result_storage_path', models.CharField(blank=True, help_text='Path to stored result file (optional)', max_length=512, null=True)),
                ('execution_log', models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_list, help_text='Execution logs as JSON array (log entries with timestamp, level, message)', null=True)),
                ('metrics', models.JSONField(blank=True, default=hub.apps.virtualization.models.default_empty_dict, help_text='Execution metrics as JSON object (duration_ms, rows_processed, memory_used, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the query execution was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the query execution was last updated')),
                ('virtual_dataset', models.ForeignKey(help_text='Virtual dataset that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='virtualization.virtualdataset')),
            ],
            options={
                'db_table': 'query_executions',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['virtual_dataset'], name='query_execu_virtual_2b04c6_idx'), models.Index(fields=['status'], name='query_execu_status_039f93_idx'), models.Index(fields=['started_at'], name='query_execu_started_95954a_idx'), models.Index(fields=['virtual_dataset', 'status'], name='query_execu_virtual_437783_idx'), models.Index(fields=['virtual_dataset', 'started_at'], name='query_execu_virtual_805915_idx')],
            },
        ),
    ]
