# Generated by Django 6.0 on 2025-12-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_workflow_instance_to_query_execution'),
        ('orchestration', '0002_add_workflow_instance_to_pipeline_execution'),
        ('virtualization', '0004_add_job_to_query_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryexecution',
            name='workflow_instance',
            field=models.ForeignKey(blank=True, help_text='Workflow instance that orchestrates this execution (null if not using workflow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_executions', to='orchestration.workflowinstance'),
        ),
        migrations.AddIndex(
            model_name='queryexecution',
            index=models.Index(fields=['workflow_instance'], name='query_execu_workflo_e2dabe_idx'),
        ),
    ]
