# Generated by Django 6.0 on 2025-12-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_tenant__fbfac6_idx',
            old_name='api_keys_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_key_has_8f2f29_idx',
            old_name='api_keys_key_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_user_id_973457_idx',
            old_name='refresh_tokens_user_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_token_h_2fa7c6_idx',
            old_name='refresh_tokens_token_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='refresh_tok_expires_a128d9_idx',
            old_name='refresh_tokens_expires_at_idx',
        ),
    ]
