# Generated by Django for Phase 9 API Gateway per-API-key rate limits

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth', '0002_rename_api_keys_tenant_user_idx_api_keys_tenant__fbfac6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='rate_limit_per_hour',
            field=models.IntegerField(
                blank=True,
                help_text='Custom API gateway rate limit (requests per hour); null uses tier/tenant default',
                null=True
            ),
        ),
    ]
