# Generated by Django 6.0.2 on 2026-03-10 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub_auth", "0004_apikey_tier_revoked_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apikey",
            new_name="api_keys_tier_id_811cbc_idx",
            old_name="api_keys_tier_id_idx",
        ),
    ]
