# Generated by Django 6.0 on 2026-03-22 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub_auth", "0007_backfill_refresh_token_expires_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="login_attem_email_61a0cd_idx",
            old_name="login_attempts_email_created_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="login_attem_ip_addr_f68fb5_idx",
            old_name="login_attempts_ip_created_idx",
        ),
        migrations.RenameIndex(
            model_name="refreshtoken",
            new_name="refresh_tok_family__5b3991_idx",
            old_name="refresh_tokens_family_id_idx",
        ),
        migrations.AddField(
            model_name="apikey",
            name="customer_email",
            field=models.EmailField(
                blank=True, help_text="Customer billing email address", max_length=254, null=True
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="External customer identifier for billing",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="customer_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional customer metadata (plan, region, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="apikey",
            name="customer_name",
            field=models.CharField(
                blank=True,
                help_text="Customer display name for billing reports",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="refreshtoken",
            name="family_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                help_text="Shared UUID for all tokens in one rotation chain",
            ),
        ),
    ]
