# Generated by Django 6.0.4 on 2026-05-13 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub_auth', '0009_refreshtoken_tenant_id'),
        ('hub_auth', '0011_add_api_key_rotation_reminder_field'),
    ]

    operations = [
    ]
